'use client';

import type { ReactNode } from 'react';
import { PlatformIcon, PLATFORM_META } from '@/components/home/dashboard-ui';
import type { PreviewPlatform } from '@/components/landing/social-preview/constants';
import { platformThemeVars } from '@/components/landing/social-preview/platform-theme';

type PreviewDeviceFrameProps = {
  platform: PreviewPlatform;
  children: ReactNode;
  /** When true, inner mockup handles its own column scrolling instead of the frame. */
  nestedScroll?: boolean;
};

export function PreviewDeviceFrame({
  platform,
  children,
  nestedScroll = false,
}: PreviewDeviceFrameProps) {
  const meta = PLATFORM_META[platform];

  return (
    <div className="overflow-hidden rounded-3xl border border-default bg-default">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-default px-4 py-3 sm:px-6">
        <div className="flex items-center gap-3">
          <PlatformIcon
            platform={platform}
            className="h-10 w-10 sm:h-11 sm:w-11"
          />
          <div>
            <p className="text-subsection text-default">{meta.label}</p>
            <p className="text-xs text-tertiary">
              Every post below was generated by SocioGenie
            </p>
          </div>
        </div>
        <span className="brand-pill">AI-generated</span>
      </div>
      {/* Platform palette enters the tree here; everything below reads
          `var(--pf-*)` and themes itself to the active network. */}
      <div
        style={platformThemeVars(platform)}
        className={
          nestedScroll
            ? 'h-[min(92vh,1100px)] overflow-hidden bg-[var(--pf-bg)]'
            : 'max-h-[min(92vh,1100px)] overflow-y-auto bg-[var(--pf-bg)]'
        }
      >
        {children}
      </div>
    </div>
  );
}
