'use client';

import { useEffect } from 'react';
import {
  Bookmark,
  ChevronLeft,
  ChevronRight,
  Heart,
  MessageCircle,
  Send,
  Share2,
  ThumbsUp,
  X,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import type { PreviewPlatform } from '@/components/landing/social-preview/constants';
import Link from 'next/link';
import { Sparkles } from 'lucide-react';
import {
  formatRelativePostTime,
  getPostTypeLabel,
  type ShowcaseBrand,
  type ShowcasePost,
} from '@/components/landing/social-preview/showcase-data';
import { ShowcaseMedia } from '@/components/landing/social-preview/showcase-media';

type ShowcasePostDetailProps = {
  brand: ShowcaseBrand;
  platform: PreviewPlatform;
  posts: ShowcasePost[];
  selectedPostId: string | null;
  onClose: () => void;
  onSelect: (postId: string) => void;
};

/**
 * The point of the whole page, stated at the moment of peak attention.
 *
 * Sits *outside* the platform replica — deliberately in SocioGenie's own
 * visual language, so a visitor can tell what is a copy of Instagram and what
 * is us talking. Every value here comes from the fixture itself; the
 * originating feature is not claimed because the export does not record it.
 */
function GeneratedByStrip({
  brand,
  post,
}: {
  brand: ShowcaseBrand;
  post: ShowcasePost;
}) {
  return (
    <div className="mx-auto mt-3 max-w-xl rounded-2xl border border-default bg-element p-4">
      <div className="flex flex-wrap items-center gap-2">
        <span className="brand-pill">
          <Sparkles className="size-3.5" aria-hidden />
          Generated by SocioGenie
        </span>
        <span className="rounded-full border border-default px-2.5 py-1 font-mono text-[11px] tracking-[-0.3px] text-secondary">
          {getPostTypeLabel(post)}
        </span>
        <span className="rounded-full border border-default px-2.5 py-1 font-mono text-[11px] tracking-[-0.3px] text-secondary">
          Scheduled {formatRelativePostTime(post.scheduleAt)}
        </span>
      </div>
      <p className="mt-3 text-sm leading-relaxed text-secondary">
        The caption, the visual and the posting time were all produced from{' '}
        {brand.name}&apos;s brand profile — then reviewed before publishing.
      </p>
      <Link
        href="/product#how-it-works"
        className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-[var(--brand-violet-text)] underline-offset-4 transition-expo hover:underline"
      >
        See how it&apos;s made
      </Link>
    </div>
  );
}

function MockAvatar({ className = 'h-9 w-9' }: { className?: string }) {
  return (
    <div
      className={`${className} shrink-0 rounded-full bg-gradient-to-br from-primary-purple/80 to-primary-blue/80 ring-2 ring-[var(--pf-surface)]`}
      aria-hidden
    />
  );
}

export function ShowcasePostDetail({
  brand,
  platform,
  posts,
  selectedPostId,
  onClose,
  onSelect,
}: ShowcasePostDetailProps) {
  const index = posts.findIndex((p) => p.id === selectedPostId);
  const post = index >= 0 ? posts[index] : null;

  useEffect(() => {
    if (!post) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'ArrowLeft' && index > 0) onSelect(posts[index - 1].id);
      if (e.key === 'ArrowRight' && index < posts.length - 1) {
        onSelect(posts[index + 1].id);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [post, index, posts, onClose, onSelect]);

  const goPrev = () => {
    if (index > 0) onSelect(posts[index - 1].id);
  };
  const goNext = () => {
    if (index < posts.length - 1) onSelect(posts[index + 1].id);
  };

  return (
    <AnimatePresence>
      {post && (
        <motion.div
          key={post.id}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="absolute inset-0 z-40 flex flex-col bg-black/55 backdrop-blur-[2px]"
          role="dialog"
          aria-modal="true"
          aria-label="Post detail"
          onClick={onClose}
        >
          <div
            className="flex items-center justify-between px-3 py-2 text-white"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              type="button"
              onClick={onClose}
              className="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-sm font-medium hover:bg-white/10"
            >
              <X className="h-4 w-4" />
              Close
            </button>
            <p className="text-xs text-white/80">
              {index + 1} / {posts.length}
            </p>
            <div className="flex items-center gap-1">
              <button
                type="button"
                onClick={goPrev}
                disabled={index <= 0}
                className="rounded-lg p-1.5 hover:bg-white/10 disabled:text-quaternary"
                aria-label="Previous post"
              >
                <ChevronLeft className="h-5 w-5" />
              </button>
              <button
                type="button"
                onClick={goNext}
                disabled={index >= posts.length - 1}
                className="rounded-lg p-1.5 hover:bg-white/10 disabled:text-quaternary"
                aria-label="Next post"
              >
                <ChevronRight className="h-5 w-5" />
              </button>
            </div>
          </div>

          <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-3 sm:px-4 sm:pb-4">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
              className="mx-auto max-w-xl"
              onClick={(e) => e.stopPropagation()}
            >
              {platform === 'instagram' && (
                <InstagramDetail brand={brand} post={post} />
              )}
              {platform === 'facebook' && (
                <FacebookDetail brand={brand} post={post} />
              )}
              {platform === 'linkedin' && (
                <LinkedInDetail brand={brand} post={post} />
              )}
              <GeneratedByStrip brand={brand} post={post} />
            </motion.div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

function detailMediaFrameClass(post: ShowcasePost, rounded = false): string {
  const base = rounded
    ? 'relative mx-4 mt-3 overflow-hidden rounded-lg bg-[var(--pf-surface-2)]'
    : 'relative w-full overflow-hidden bg-[var(--pf-surface-2)]';
  // Generated assets are mostly square; carousels are portrait 4:5.
  // Always leave room for object-contain so nothing is cropped.
  if (post.mediaType === 'carousel') return `${base} aspect-[4/5]`;
  return `${base} aspect-square`;
}

function InstagramDetail({
  brand,
  post,
}: {
  brand: ShowcaseBrand;
  post: ShowcasePost;
}) {
  return (
    <article className="overflow-hidden rounded-xl border border-[var(--pf-border)] bg-[var(--pf-surface)] shadow-xl">
      <div className="flex items-center gap-2 border-b border-[var(--pf-border)] px-3 py-2.5">
        <MockAvatar className="h-8 w-8" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-[13px] font-semibold text-[var(--pf-text)]">
            {brand.handle}
          </p>
          <p className="text-[11px] text-[var(--pf-text-muted)]">
            {formatRelativePostTime(post.scheduleAt)}
          </p>
        </div>
      </div>
      <div className={detailMediaFrameClass(post)}>
        <ShowcaseMedia
          post={post}
          playVideo
          mediaClassName="object-contain"
          sizes="(max-width: 768px) 100vw, 560px"
        />
      </div>
      <div className="px-3 py-2.5">
        <div className="flex items-center justify-between text-[var(--pf-text)]">
          <div className="flex items-center gap-4">
            <Heart className="h-6 w-6" strokeWidth={1.75} />
            <MessageCircle className="h-6 w-6" strokeWidth={1.75} />
            <Send className="h-6 w-6" strokeWidth={1.75} />
          </div>
          <Bookmark className="h-6 w-6" strokeWidth={1.75} />
        </div>
        <p className="mt-2 text-[13px] leading-snug text-[var(--pf-text)]">
          <span className="font-semibold">{brand.handle} </span>
          {post.caption}
        </p>
      </div>
    </article>
  );
}

function FacebookDetail({
  brand,
  post,
}: {
  brand: ShowcaseBrand;
  post: ShowcasePost;
}) {
  return (
    <article className="overflow-hidden rounded-xl border border-[var(--pf-border)] bg-[var(--pf-surface)] shadow-xl">
      <div className="flex items-start gap-3 px-4 pt-4">
        <MockAvatar className="h-10 w-10" />
        <div>
          <p className="text-[15px] font-semibold text-[var(--pf-text)]">
            {brand.name}
          </p>
          <p className="text-xs text-[var(--pf-text-muted)]">
            {formatRelativePostTime(post.scheduleAt)} · Public
          </p>
        </div>
      </div>
      <p className="px-4 pt-3 text-[15px] leading-snug text-[var(--pf-text)]">
        {post.caption}
      </p>
      <div className={detailMediaFrameClass(post, true)}>
        <ShowcaseMedia
          post={post}
          playVideo
          mediaClassName="object-contain"
          sizes="(max-width: 680px) 100vw, 680px"
        />
      </div>
      <div className="mx-4 mt-3 border-t border-[var(--pf-border)]" />
      <div
        className="grid grid-cols-3 gap-1 px-2 py-1 text-[var(--pf-text-muted)]"
        aria-hidden
      >
        <div className="flex items-center justify-center gap-1.5 rounded-lg py-2 text-sm font-medium">
          <ThumbsUp className="h-4 w-4" />
          Like
        </div>
        <div className="flex items-center justify-center gap-1.5 rounded-lg py-2 text-sm font-medium">
          <MessageCircle className="h-4 w-4" />
          Comment
        </div>
        <div className="flex items-center justify-center gap-1.5 rounded-lg py-2 text-sm font-medium">
          <Share2 className="h-4 w-4" />
          Share
        </div>
      </div>
    </article>
  );
}

function LinkedInDetail({
  brand,
  post,
}: {
  brand: ShowcaseBrand;
  post: ShowcasePost;
}) {
  return (
    <article className="overflow-hidden rounded-xl border border-[var(--pf-border)] bg-[var(--pf-surface)] shadow-xl">
      <div className="flex items-start gap-3 px-4 pt-4">
        <MockAvatar className="h-12 w-12" />
        <div>
          <p className="text-[14px] font-semibold text-[var(--pf-text)]">
            {brand.name}
          </p>
          <p className="text-xs text-[var(--pf-text-muted)]">
            {brand.followersLabel} followers
          </p>
          <p className="text-xs text-[var(--pf-text-muted)]">
            {formatRelativePostTime(post.scheduleAt)} · Public
          </p>
        </div>
      </div>
      <p className="px-4 pt-3 text-[14px] leading-relaxed text-[var(--pf-text)] whitespace-pre-wrap">
        {post.caption}
      </p>
      <div className={detailMediaFrameClass(post, true)}>
        <ShowcaseMedia
          post={post}
          playVideo
          mediaClassName="object-contain"
          sizes="(max-width: 552px) 100vw, 552px"
        />
      </div>
      <div className="mx-4 mt-3 border-t border-[var(--pf-border)]" />
      <div
        className="grid grid-cols-4 gap-1 px-2 py-1 text-[var(--pf-text-muted)]"
        aria-hidden
      >
        <div className="flex items-center justify-center gap-1 rounded-lg py-2 text-xs font-semibold sm:text-sm">
          <ThumbsUp className="h-4 w-4" />
          Like
        </div>
        <div className="flex items-center justify-center gap-1 rounded-lg py-2 text-xs font-semibold sm:text-sm">
          <MessageCircle className="h-4 w-4" />
          Comment
        </div>
        <div className="flex items-center justify-center gap-1 rounded-lg py-2 text-xs font-semibold sm:text-sm">
          <Share2 className="h-4 w-4" />
          Repost
        </div>
        <div className="flex items-center justify-center gap-1 rounded-lg py-2 text-xs font-semibold sm:text-sm">
          <Send className="h-4 w-4" />
          Send
        </div>
      </div>
    </article>
  );
}
