import type { PreviewPlatform } from '@/components/landing/social-preview/constants';
import {
  GENERATED_SHOWCASE_BRAND,
  GENERATED_SHOWCASE_POSTS,
} from '@/components/landing/social-preview/showcase-posts.generated';

export type ShowcaseMediaType = 'image' | 'video' | 'carousel';

export type ShowcaseCarouselSlide = {
  imageUrl: string;
};

export type ShowcasePost = {
  id: string;
  platform: PreviewPlatform;
  scheduleAt: string;
  mediaType: ShowcaseMediaType;
  caption: string;
  imageUrl?: string;
  videoUrl?: string;
  posterUrl?: string;
  carouselSlides?: ShowcaseCarouselSlide[];
};

/** Brand from demo export (regenerated by export-how-it-looks). */
export const SHOWCASE_BRAND = GENERATED_SHOWCASE_BRAND;

/**
 * Posts from demo user scheduledPosts.
 * Captions = Firestore `message` on each post (exported automatically).
 * Re-run: `pnpm export-how-it-looks` in backend/apps/api
 */
export const SHOWCASE_POSTS: ShowcasePost[] =
  GENERATED_SHOWCASE_POSTS as unknown as ShowcasePost[];

export function getShowcasePostsForPlatform(
  platform: PreviewPlatform
): ShowcasePost[] {
  return SHOWCASE_POSTS.filter((p) => p.platform === platform).sort(
    (a, b) => new Date(b.scheduleAt).getTime() - new Date(a.scheduleAt).getTime()
  );
}

/** Still thumbnail for grid cells (never a video file). */
export function getPostThumbnailUrl(post: ShowcasePost): string {
  if (post.mediaType === 'carousel') {
    return post.carouselSlides?.[0]?.imageUrl || '';
  }
  if (post.mediaType === 'video') {
    return post.posterUrl || post.imageUrl || '';
  }
  return post.imageUrl || '';
}

/** Deterministic fake engagement from post id (stable across renders). */
export function getPostEngagement(post: ShowcasePost): {
  likes: number;
  comments: number;
  shares: number;
} {
  let hash = 0;
  for (let i = 0; i < post.id.length; i++) {
    hash = (hash * 31 + post.id.charCodeAt(i)) >>> 0;
  }
  return {
    likes: 120 + (hash % 1800),
    comments: 8 + (hash % 90),
    shares: 3 + (hash % 40),
  };
}

export function formatRelativePostTime(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return 'Just now';
  const day = date.getUTCDate();
  const month = date.toLocaleString('en-US', { month: 'short', timeZone: 'UTC' });
  return `${month} ${day}`;
}
