import { ShieldAlert } from 'lucide-react';
import { LegalDocument, LegalPage } from '../_components/legal-page';

export default function AcceptableUsePolicyPage() {
  return (
    <LegalPage
      title="Acceptable Use Policy"
      subtitle="Effective date: 28 May 2026 · Last updated: 28 May 2026"
      icon={ShieldAlert}
      iconTone="amber"
    >
      <LegalDocument>
        <p>
          This Acceptable Use Policy (“<strong>AUP</strong>”) governs your use
          of the SocioGenie platform operated by <strong>MAGNATEX LLP</strong>{' '}
          (“we”, “our”, “us”). It supplements and is incorporated by reference
          into our <a href="/legal/terms">Terms of Service</a>. By using
          SocioGenie you agree to comply with this AUP. Violating this AUP may
          result in content removal, denial of AI generations, suspension or
          termination of your account, reporting to law enforcement, and
          recovery of any costs we incur as a result of your violation.
        </p>

        <h2>1. Scope</h2>
        <p>
          This AUP applies to all use of SocioGenie, including the AI Engine,
          Content Studio, Product Ads, Event Studio, the AI Chatbot Assistant,
          brand-onboarding scraping, the Approval Workflow, the Media Library, and any content scheduled
          or published to your Connected Social Accounts through our platform.
          It applies whether content is generated by you, by our AI, or by our
          operations team in Managed Approval Mode.
        </p>

        <h2>2. Your Responsibility</h2>
        <p>
          You are solely responsible for the content you create, upload,
          generate, schedule, or publish through SocioGenie. AI-generated
          content does not transfer responsibility to MAGNATEX LLP or to any
          AI provider. Before publishing, you must review every post for
          accuracy, legality, brand fit, and compliance with the policies of
          the social-media platforms you are posting to.
        </p>

        <h2>3. Prohibited Content</h2>
        <p>
          You must not use SocioGenie to create, store, schedule, publish, or
          otherwise distribute content that:
        </p>

        <h3>3.1 Illegal &amp; criminal</h3>
        <ul>
          <li>
            violates any law applicable to you, MAGNATEX LLP, the destination
            social-media platform, or the audience receiving the content;
          </li>
          <li>
            promotes, glorifies, facilitates, or instructs how to commit
            criminal activity, terrorism, organised violence, human trafficking,
            illegal drugs, weapons of mass destruction, or any other unlawful
            act;
          </li>
          <li>
            constitutes child sexual abuse material (CSAM), grooming, or any
            sexualised content involving minors. CSAM is reported to law
            enforcement without prior notice to you;
          </li>
          <li>
            incites or threatens violence against any individual or group;
          </li>
          <li>contains terrorist or violent-extremist propaganda;</li>
          <li>
            facilitates regulated activity for which you do not hold the
            required licence (e.g., financial advice, medical advice, gambling,
            pharmaceuticals, alcohol/tobacco marketing in restricted
            jurisdictions).
          </li>
        </ul>

        <h3>3.2 Hateful, abusive &amp; harmful</h3>
        <ul>
          <li>
            promotes hatred, discrimination, or violence against any individual
            or group on the basis of race, ethnicity, national origin, caste,
            religion, gender, gender identity, sexual orientation, age,
            disability, or any other protected characteristic;
          </li>
          <li>
            harasses, bullies, doxxes, stalks, intimidates, or shames any
            identifiable individual;
          </li>
          <li>contains gratuitous gore, cruelty, or self-harm promotion;</li>
          <li>contains non-consensual sexual or intimate imagery.</li>
        </ul>

        <h3>3.3 Deceptive &amp; manipulative content</h3>
        <ul>
          <li>
            impersonates any person, business, public figure, or government
            agency without lawful authorisation;
          </li>
          <li>
            creates synthetic or “deepfake” media that depicts an identifiable
            real person doing or saying something they did not, in a manner
            likely to deceive an ordinary viewer, without that person’s
            documented consent;
          </li>
          <li>
            constitutes coordinated inauthentic behaviour, including fake
            engagement, click farms, follower farming, like/comment swap
            schemes, or sockpuppet networks;
          </li>
          <li>
            spreads health misinformation, vaccine misinformation, climate
            denialism, or any content reasonably likely to cause physical harm
            if relied upon;
          </li>
          <li>
            promotes financial scams, pump-and-dump schemes, fraudulent ICO/NFT
            offerings, unauthorised investment advice, or “get rich quick”
            schemes;
          </li>
          <li>
            includes election misinformation, voter suppression, manipulated
            media of political figures during an election period, or content
            that violates election-period rules in any country where the post
            will be visible.
          </li>
        </ul>

        <h3>3.4 Intellectual-property violations</h3>
        <ul>
          <li>
            infringes any copyright, trademark, trade-secret, design right, or
            other intellectual-property right of a third party;
          </li>
          <li>
            uses brand assets, logos, characters, music, fonts, or stock media
            for which you do not have a valid licence;
          </li>
          <li>
            misrepresents official endorsement by another business or person.
          </li>
        </ul>

        <h3>3.5 Privacy violations</h3>
        <ul>
          <li>
            publishes another person’s personal data without their consent or
            other lawful basis (including phone numbers, addresses, financial
            data, identity documents, medical information, biometric data, or
            location data);
          </li>
          <li>
            scrapes or uploads data about audiences, leads, or contacts that
            you do not have permission to process under the DPDP Act, GDPR,
            CCPA, or other applicable laws;
          </li>
          <li>
            uses SocioGenie to send unsolicited bulk messages, scrape
            user-generated content for resale, or build shadow profiles of
            individuals.
          </li>
        </ul>

        <h2>4. Prohibited Conduct on the Platform</h2>
        <p>You must not:</p>
        <ul>
          <li>
            share your account credentials with anyone, sell or transfer your
            account, or operate multiple accounts to evade limits or bans;
          </li>
          <li>
            use SocioGenie to compete with us — including training or
            evaluating a competing AI model, dataset, or social-media
            automation product;
          </li>
          <li>
            reverse-engineer, decompile, disassemble, scrape the platform UI or
            APIs, or attempt to extract source code, prompts, model weights,
            or internal data;
          </li>
          <li>
            probe, scan, or test the vulnerability of any system or network
            without our prior written permission (responsible-disclosure
            reports can be sent to{' '}
            <a href="mailto:founder@magnatex.co">founder@magnatex.co</a>);
          </li>
          <li>
            upload malware, viruses, worms, trojans, ransomware, or any code
            that could disable, overburden, damage, or impair the Services;
          </li>
          <li>
            attempt to circumvent rate limits, credit limits, paywalls, or any
            other technical or contractual restriction;
          </li>
          <li>
            interfere with another user’s use of the Services or with our
            payment partner Dodo Payments;
          </li>
          <li>
            use the Services in any way that violates the export-control or
            sanctions laws of India, the United States, the European Union, or
            any other jurisdiction applicable to you.
          </li>
        </ul>

        <h2>5. Restrictions on AI-Generated Content</h2>
        <p>
          SocioGenie uses third-party generative-AI providers (OpenAI,
          Anthropic, Google AI). In addition to this AUP, you must comply with
          their usage policies. You specifically must not use the AI features
          to:
        </p>
        <ul>
          <li>
            generate sexually explicit content, fetish content, or any
            sexualised depiction of a real identifiable person;
          </li>
          <li>
            generate political-campaign content that misrepresents real events,
            voting procedures, or candidates;
          </li>
          <li>
            generate content for purposes regulated by these providers —
            including high-stakes medical diagnoses, legal opinions, or
            financial-advisory content — without the involvement of a qualified
            professional;
          </li>
          <li>
            generate content intended to be passed off as human-authored when
            applicable platform rules require AI-disclosure (see our{' '}
            <a href="/legal/ai-disclosure">AI Disclosure</a>);
          </li>
          <li>
            extract personal data, biometric identifiers, or facial recognition
            from images you upload.
          </li>
        </ul>

        <h2>6. Web-Scraping &amp; Brand Onboarding</h2>
        <p>
          During onboarding, SocioGenie may fetch publicly accessible pages
          from a website you submit, to extract business descriptions, brand
          colours, logos, and contact details for your Brand DNA. You confirm
          and agree that:
        </p>
        <ul>
          <li>
            you own the website or have authorisation from the owner to perform
            this fetch;
          </li>
          <li>
            you will not submit websites whose terms of service or{' '}
            <code>robots.txt</code> prohibit automated access;
          </li>
          <li>
            you will not use SocioGenie or its scraping integrations to harvest
            personal data, prices, content, or user-generated content from
            third-party websites in violation of their terms or applicable law
            (including the Computer Fraud and Abuse Act in the US, the
            Information Technology Act in India, or the Database Directive in
            the EU);
          </li>
          <li>
            you will not use SocioGenie to power a competing scraping or
            data-aggregation service.
          </li>
        </ul>

        <h2>7. Connected Social-Media Platforms</h2>
        <p>
          When you connect Instagram, Facebook, LinkedIn, or any other
          platform, you remain bound by the rules of that platform. We do not
          waive, override, or modify those rules. In particular you agree to
          comply with:
        </p>
        <ul>
          <li>
            <strong>Meta Platforms</strong> — Meta Terms of Service, Community
            Standards, Branded Content Policies, Commerce Policies, Advertising
            Standards, and Platform Terms;
          </li>
          <li>
            <strong>LinkedIn</strong> — LinkedIn User Agreement, Professional
            Community Policies, and API Terms;
          </li>
          <li>
            <strong>any other connected platform’s</strong> terms and policies.
          </li>
        </ul>
        <p>
          Violation of those rules by you — including content you publish via
          SocioGenie — may result in your account being restricted or banned by
          the relevant platform. MAGNATEX LLP is not responsible for such
          actions and is under no obligation to restore connectivity.
        </p>

        <h2>8. Spam, Marketing &amp; Communications</h2>
        <p>You must not use SocioGenie to:</p>
        <ul>
          <li>
            send unsolicited commercial communications (spam) on any social
            platform, in violation of CAN-SPAM (US), GDPR ePrivacy (EU), or
            equivalent anti-spam law in your jurisdiction;
          </li>
          <li>
            misrepresent the source, identity, or origin of any post or
            message;
          </li>
          <li>
            run pyramid schemes, multi-level-marketing recruitment funnels, or
            similar.
          </li>
        </ul>

        <h2>9. Reporting Violations</h2>
        <p>
          If you encounter content or behaviour that violates this AUP, please
          report it to{' '}
          <a href="mailto:founder@magnatex.co">founder@magnatex.co</a> with
          (where possible) a description, the URL or post identifier, and the
          time it was observed. Reports involving CSAM or imminent threats of
          violence are escalated to law enforcement and the relevant platform.
        </p>

        <h2>10. Enforcement</h2>
        <p>
          We may take any of the following actions, with or without prior
          notice, in our sole reasonable discretion, when we believe this AUP
          has been violated:
        </p>
        <ul>
          <li>refuse to generate or publish particular content;</li>
          <li>remove content from your Account, Media Library, or queue;</li>
          <li>throttle your usage or suspend AI generations;</li>
          <li>
            suspend or terminate your Account (with forfeiture of remaining
            subscription time and Credits, in line with our{' '}
            <a href="/legal/refund">Refund Policy</a>);
          </li>
          <li>
            disclose information to law enforcement, regulators, courts, or
            third-party platforms as required by law or to prevent harm;
          </li>
          <li>
            seek reimbursement for fines, takedown costs, chargeback fees, or
            legal fees that we incur as a result of your violation.
          </li>
        </ul>

        <h2>11. Changes to this AUP</h2>
        <p>
          We may update this AUP from time to time to reflect new threats,
          legal requirements, or product capabilities. The updated AUP takes
          effect when posted; the “Last updated” date will be revised
          accordingly.
        </p>

        <h2>12. Contact</h2>
        <ul>
          <li>
            <strong>Abuse reports &amp; AUP queries:</strong>{' '}
            <a href="mailto:founder@magnatex.co">founder@magnatex.co</a>
          </li>
          <li>
            <strong>Support:</strong>{' '}
            <a href="mailto:support@magnatex.co">support@magnatex.co</a>
          </li>
          <li>
            <strong>Postal:</strong> MAGNATEX LLP (LLPIN: ACU-5689), 111,
            Fortune Business Hub, Sola, Nr. Satyamev Elysium, Ahmedabad,
            Gujarat 380060, India
          </li>
        </ul>
      </LegalDocument>
    </LegalPage>
  );
}
