'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Lightbulb, Sparkles, Trophy } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  getWhatToPostNext,
  type PostBrief,
  type PostBriefKind,
  type WhatToPostNextPayload,
} from '@/src/service/api/analyticService';
import { useWhatToPostNextCache } from '@/src/stores/whatToPostNextCache';
import { WORKSPACE_NAV_HREFS } from '@/lib/workspace-nav';

import { platformLabel, type GrowthStudioPlatform } from './_common';

/**
 * Growth Studio A1 — What to post next.
 *
 * Renders two idea cards generated by the backend (OpenAI):
 *   • Recreate the winner    — recreates the top-performing recent post.
 *   • Plug a content gap     — a pillar/format the user hasn't covered.
 *
 * The card body shows title / description / hint plus a prompt preview.
 * "Generate" opens Quick Create or Carousel Create with the prompt prefilled
 * depending on the brief and platform.
 */

const ACTIVE_BRIEF_KEYS = new Set<PostBriefKind>([
  'recreate-winner',
  'plug-a-gap',
]);

const ICONS: Record<PostBriefKind, typeof Trophy> = {
  'recreate-winner': Trophy,
  'plug-a-gap': Lightbulb,
};

function resolveSuggestedFormat(
  brief: PostBrief
): NonNullable<PostBrief['suggestedFormat']> {
  if (brief.suggestedFormat) return brief.suggestedFormat;
  return 'single image';
}

function generateLabel(brief: PostBrief): string {
  if (resolveSuggestedFormat(brief) === 'carousel') return 'Generate carousel';
  return 'Generate this post';
}

function generationPath(
  brief: PostBrief,
  platform: GrowthStudioPlatform
): string {
  const params = new URLSearchParams({
    prompt: brief.prompt,
    platform,
  });
  if (resolveSuggestedFormat(brief) === 'carousel') {
    return `${WORKSPACE_NAV_HREFS.carouselCreate}?${params.toString()}`;
  }
  return `${WORKSPACE_NAV_HREFS.quickCreate}?${params.toString()}`;
}

function filterBriefs(payload: WhatToPostNextPayload): WhatToPostNextPayload {
  return {
    ...payload,
    briefs: (payload.briefs ?? []).filter((b) =>
      ACTIVE_BRIEF_KEYS.has(b.key as PostBriefKind)
    ),
  };
}

type FetchState =
  | { status: 'loading' }
  | { status: 'success'; payload: WhatToPostNextPayload }
  | { status: 'error'; error: string };

function initialStateFor(platform: GrowthStudioPlatform): FetchState {
  const cached = useWhatToPostNextCache.getState().getFresh(platform);
  return cached
    ? { status: 'success', payload: filterBriefs(cached) }
    : { status: 'loading' };
}

function BriefCard({
  brief,
  onGenerate,
}: {
  brief: PostBrief;
  onGenerate: (brief: PostBrief) => void;
}) {
  const Icon = ICONS[brief.key] ?? Lightbulb;
  return (
    <div className="flex h-full flex-col gap-3 rounded-xl border border-default bg-default p-4">
      <div className="flex items-start gap-2">
        <div className="rounded-lg bg-success p-1.5" aria-hidden>
          <Icon className="h-4 w-4 text-success" />
        </div>
        <div className="flex-1 space-y-1">
          <p className="text-sm font-semibold text-default">{brief.title}</p>
          <p className="text-xs leading-relaxed text-secondary">
            {brief.description}
          </p>
        </div>
      </div>

      <div className="rounded-md border border-dashed border-default bg-element px-2.5 py-2 text-[11px] text-secondary">
        {brief.hint}
      </div>

      {/*
        Surface the actual prompt that will be sent to /instant-generation
        so the user can read it before tapping Generate. Clamped to 4 lines
        with title on hover for the full text.
      */}
      {brief.prompt ? (
        <div
          className="rounded-md border border-success bg-success px-2.5 py-2 text-[11px] leading-relaxed text-success"
          title={brief.prompt}
        >
          <p className="mb-0.5 text-[10px] font-semibold uppercase tracking-wide text-success">
            Prompt preview
          </p>
          <p className="line-clamp-4 whitespace-pre-wrap text-default">
            {brief.prompt}
          </p>
        </div>
      ) : null}

      <Button
        type="button"
        size="sm"
        variant="outline"
        className="mt-auto justify-center"
        onClick={() => onGenerate(brief)}
      >
        {generateLabel(brief)}
      </Button>
    </div>
  );
}

function SkeletonCard() {
  return (
    <div
      role="status"
      aria-label="Loading post idea"
      className="h-44 animate-pulse rounded-xl border border-success bg-success"
    />
  );
}

export function WhatToPostNextSection({
  platform,
}: {
  platform: GrowthStudioPlatform;
}) {
  const router = useRouter();
  const [state, setState] = useState<FetchState>(() =>
    initialStateFor(platform)
  );

  useEffect(() => {
    const cache = useWhatToPostNextCache.getState();
    const fresh = cache.getFresh(platform);
    if (fresh) {
      setState({ status: 'success', payload: filterBriefs(fresh) });
      return;
    }
    let cancelled = false;
    getWhatToPostNext(platform)
      .then((res) => {
        if (cancelled) return;
        const next = filterBriefs(res.data);
        useWhatToPostNextCache.getState().set(platform, next);
        setState({ status: 'success', payload: next });
      })
      .catch(() => {
        if (cancelled) return;
        setState({
          status: 'error',
          error: 'Something went wrong',
        });
      });
    return () => {
      cancelled = true;
    };
  }, [platform]);

  const handleGenerate = (brief: PostBrief) => {
    router.push(generationPath(brief, platform));
  };

  return (
    <section
      aria-labelledby="growth-studio-what-to-post-heading"
      className="space-y-3"
    >
      <header className="flex flex-wrap items-center justify-between gap-2">
        <h2
          id="growth-studio-what-to-post-heading"
          className="text-section text-default flex items-center gap-2"
        >
          <Sparkles className="h-4 w-4 text-success" aria-hidden />
          What to post next
        </h2>
      </header>
      <p className="text-xs leading-relaxed text-secondary">
        Two {platformLabel(platform)} idea cards tuned to your analytics — your
        best winner, and a gap you&apos;ve been avoiding.
      </p>

      {state.status === 'loading' ? (
        <div className="grid gap-3 sm:grid-cols-2">
          <SkeletonCard />
          <SkeletonCard />
        </div>
      ) : state.status === 'error' ? (
        <p className="rounded-lg border border-warning bg-warning px-3 py-2 text-xs text-warning">
          Couldn&apos;t load post ideas: {state.error}
        </p>
      ) : state.payload.visible && state.payload.briefs.length > 0 ? (
        <div className="grid gap-3 sm:grid-cols-2">
          {state.payload.briefs.map((brief) => (
            <BriefCard
              key={brief.key}
              brief={brief}
              onGenerate={handleGenerate}
            />
          ))}
        </div>
      ) : (
        <p className="rounded-lg border border-default bg-element px-3 py-3 text-xs text-secondary">
          {state.payload.reason ??
            'Post idea cards will appear here once we have enough data.'}
        </p>
      )}
    </section>
  );
}
