'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { LayoutGrid, Lightbulb, Sparkles, Trophy } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  getWhatToPostNext,
  type PostBrief,
  type PostBriefKind,
  type WhatToPostNextPayload,
} from '@/src/service/api/analyticService';
import { useWhatToPostNextCache } from '@/src/stores/whatToPostNextCache';

import { platformLabel, type GrowthStudioPlatform } from './_common';

/**
 * Growth Studio A1 — What to post next.
 *
 * Renders three idea cards generated by the backend (OpenAI):
 *   • Recreate the winner    — recreates the top-performing recent post.
 *   • Plug a content gap     — a pillar/format the user hasn't covered.
 *   • Try a new format       — a format the user hasn't published.
 *
 * The card body shows only the title / description / hint — the raw
 * `prompt` is intentionally hidden. When the user clicks "Generate this
 * post" we navigate to `/instant-generation` with the prompt + the active
 * analytics platform encoded in the query string. The instant-generation
 * page then populates its prompt textarea and pre-selects the platform.
 */

const ICONS: Record<PostBriefKind, typeof Trophy> = {
  'recreate-winner': Trophy,
  'plug-a-gap': Lightbulb,
  'try-a-new-format': LayoutGrid,
};

type FetchState =
  | { status: 'loading' }
  | { status: 'success'; payload: WhatToPostNextPayload }
  | { status: 'error'; error: string };

function initialStateFor(platform: GrowthStudioPlatform): FetchState {
  const cached = useWhatToPostNextCache.getState().getFresh(platform);
  return cached
    ? { status: 'success', payload: cached }
    : { status: 'loading' };
}

function BriefCard({
  brief,
  onGenerate,
}: {
  brief: PostBrief;
  onGenerate: (brief: PostBrief) => void;
}) {
  const Icon = ICONS[brief.key];
  return (
    <div className="flex h-full flex-col gap-3 rounded-xl border border-emerald-200 bg-white p-4 shadow-sm">
      <div className="flex items-start gap-2">
        <div className="rounded-lg bg-emerald-100 p-1.5" aria-hidden>
          <Icon className="h-4 w-4 text-emerald-700" />
        </div>
        <div className="flex-1 space-y-1">
          <p className="text-sm font-semibold text-zinc-900">{brief.title}</p>
          <p className="text-xs leading-relaxed text-zinc-600">
            {brief.description}
          </p>
        </div>
      </div>

      <div className="rounded-md border border-dashed border-zinc-200 bg-zinc-50/60 px-2.5 py-2 text-[11px] text-zinc-500">
        {brief.hint}
      </div>

      <Button
        type="button"
        size="sm"
        variant="outline"
        className="mt-auto justify-center"
        onClick={() => onGenerate(brief)}
      >
        Generate this post
      </Button>
    </div>
  );
}

function SkeletonCard() {
  return (
    <div
      role="status"
      aria-label="Loading post idea"
      className="h-44 animate-pulse rounded-xl border border-emerald-100 bg-emerald-50/40"
    />
  );
}

export function WhatToPostNextSection({
  platform,
}: {
  platform: GrowthStudioPlatform;
}) {
  const router = useRouter();
  const [state, setState] = useState<FetchState>(() => initialStateFor(platform));

  useEffect(() => {
    const cache = useWhatToPostNextCache.getState();
    if (cache.getFresh(platform)) return;
    let cancelled = false;
    getWhatToPostNext(platform)
      .then((res) => {
        if (cancelled) return;
        useWhatToPostNextCache.getState().set(platform, res.data);
        setState({ status: 'success', payload: res.data });
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setState({
          status: 'error',
          error: err instanceof Error ? err.message : 'Something went wrong',
        });
      });
    return () => {
      cancelled = true;
    };
  }, [platform]);

  const handleGenerate = (brief: PostBrief) => {
    const params = new URLSearchParams({
      prompt: brief.prompt,
      platform,
    });
    router.push(`/instant-generation?${params.toString()}`);
  };

  return (
    <section
      aria-labelledby="growth-studio-what-to-post-heading"
      className="space-y-3"
    >
      <header className="flex flex-wrap items-center justify-between gap-2">
        <h2
          id="growth-studio-what-to-post-heading"
          className="flex items-center gap-2 text-sm font-semibold text-zinc-900"
        >
          <Sparkles className="h-4 w-4 text-emerald-600" aria-hidden />
          What to post next
        </h2>
      </header>
      <p className="text-xs leading-relaxed text-zinc-600">
        Three {platformLabel(platform)} idea cards tuned to your analytics —
        your best winner, a gap you’ve been avoiding, and a format you haven’t
        tried yet.
      </p>

      {state.status === 'loading' ? (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
        </div>
      ) : state.status === 'error' ? (
        <p className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">
          Couldn’t load post ideas: {state.error}
        </p>
      ) : state.payload.visible && state.payload.briefs.length > 0 ? (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {state.payload.briefs.map((brief) => (
            <BriefCard
              key={brief.key}
              brief={brief}
              onGenerate={handleGenerate}
            />
          ))}
        </div>
      ) : (
        <p className="rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-3 text-xs text-zinc-600">
          {state.payload.reason ??
            'Post idea cards will appear here once we have enough data.'}
        </p>
      )}
    </section>
  );
}
