'use client';

import { PageLoadingState } from '@/components/shared/PageLoadingState';
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
} from 'react';
import { createPortal } from 'react-dom';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  WORKSPACE_NAV_HREFS,
  workspacePageTitle,
} from '@/lib/workspace-nav';
import {
  useTimestampFormatter,
  type TimestampInput,
} from '@/lib/user-timezone';
import {
  Calendar,
  CalendarPlus,
  ExternalLink,
  ImageIcon,
  ImageOff,
  Loader2,
  Search,
  Sparkles,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { generatedByLabel } from '@/lib/scheduled-post-status';
import {
  getGeneratedMediaLibraryApi,
  type GeneratedMediaLibraryItem,
  type GeneratedMediaSource,
  type MediaSource,
} from '@/src/service/api/generated-media-library.service';
import { Button } from '@/components/ui/button';
import { DownloadPngButton } from '@/components/download-png-button';
import { SharePostButton } from '@/components/share-post-button';
import {
  ImagePreviewButton,
  ImagePreviewOverlay,
  useImagePreview,
} from '@/components/image-preview';
import { useUserPlanCredits } from '../_components/UserPlanCreditsProvider';
import { isPlanInactive } from '@/lib/plan-access';
import {
  galleryItemCanSchedule,
  galleryItemToPrefillPost,
} from '@/lib/gallery-schedule';
import {
  hasSchedulableMediaPreview,
  resolveSchedulableMediaPreview,
} from '@/lib/post-media-preview';
import { PostMediaPreview } from '@/components/shared/PostMediaPreview';
import { CarouselSwipePreview } from '@/components/shared/CarouselSwipePreview';
import {
  setPostSchedulerPrefill,
  type PostSchedulerPrefillPayload,
} from '@/lib/post-scheduler-prefill-store';
import { scheduleCampaignDraftApi } from '@/src/service/api/campaign.service';
import { showErrorToast } from '@/lib/show-error-toast';
import { toast } from 'sonner';
import { GenerationResearchDialog } from '@/components/generation-research-dialog';
import {
  hasViewableResearch,
  mergeGenerationResearch,
} from '@/lib/generation-research';

const SOURCE_OPTIONS: {
  value: 'all' | GeneratedMediaSource;
  label: string;
  description: string;
}[] = [
  {
    value: 'all',
    label: 'All',
    description: 'Everything you have generated',
  },
  {
    value: 'instant-generation',
    label: 'Content Studio',
    description: 'Posts from Content Studio',
  },
  {
    value: 'productadvert',
    label: 'Product Ads',
    description: 'Creatives from Product Ads',
  },
  {
    value: 'videoGeneration',
    label: 'Video Generator',
    description: 'Videos from Video Generator',
  },
  {
    value: 'eventPosts',
    label: 'Event Studio',
    description: 'Posts from Event Studio',
  },
  {
    value: 'campaignDrafts',
    label: 'Campaigns',
    description: 'Drafts from Campaigns',
  },
  {
    value: 'carouselGeneratedPosts',
    label: 'Carousel Posts',
    description: 'Carousels from Carousel Posts',
  },
  {
    value: 'aiEnginePosts',
    label: 'AI Engine',
    description: 'Posts from AI Engine',
  },
];

/**
 * Map each media-library collection onto the pipeline tag the Post Queue's
 * `generatedByLabel` understands, so the gallery surfaces the EXACT same
 * "Generated by …" wording as `/scheduled-posts` (e.g. "Content Studio",
 * "AI Engine"). Campaign drafts have no native generatedBy
 * pipeline yet — fall back to a friendly literal.
 */
function generatedByForCollection(collection: MediaSource): string | null {
  switch (collection) {
    case 'instant-generation':
      return generatedByLabel('instant-generation');
    case 'batchGeneratedPosts':
      return generatedByLabel('batch-generation');
    case 'productadvert':
      return generatedByLabel('product-advert');
    case 'videoGeneration':
      return 'Video Generator';
    case 'carouselGeneratedPosts':
      return generatedByLabel('carousel-engine');
    case 'eventPosts':
      return generatedByLabel('events-post');
    case 'aiEnginePosts':
      return generatedByLabel('ai-engine');
    case 'campaignDrafts':
      return 'Campaigns';
    default:
      return null;
  }
}

/** Normalize caption for display; some stored docs use non-string captions. */
function mediaCaptionLabel(caption: unknown): string {
  if (caption == null) return '';
  if (typeof caption === 'string') return caption.trim();
  if (typeof caption === 'number' || typeof caption === 'boolean') {
    return String(caption).trim();
  }
  if (typeof caption === 'object') {
    const o = caption as Record<string, unknown>;
    for (const key of ['text', 'caption', 'message', 'body'] as const) {
      const v = o[key];
      if (typeof v === 'string') return v.trim();
    }
    try {
      return JSON.stringify(caption);
    } catch {
      return String(caption);
    }
  }
  return String(caption).trim();
}

function contentTypeDisplayLabel(item: GeneratedMediaLibraryItem): string {
  const label = item.contentTypeLabel?.trim();
  if (label) return label;
  const key = item.contentType?.trim();
  if (!key) return '';
  return key
    .toLowerCase()
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function DetailRow({
  label,
  value,
  long,
}: {
  label: string;
  value: string;
  long?: boolean;
}) {
  return (
    <div className={long ? 'min-w-0' : undefined}>
      <p className="text-xs font-medium text-muted-foreground mb-0.5">{label}</p>
      <p
        className={
          long
            ? 'text-sm text-foreground min-w-0 whitespace-pre-wrap wrap-break-word break-words [overflow-wrap:anywhere]'
            : 'text-sm text-foreground'
        }
      >
        {value}
      </p>
    </div>
  );
}

function MediaDetailModal({
  item,
  onClose,
  formatWhen,
  onSchedule,
  canSchedule,
  onPreviewImage,
}: {
  item: GeneratedMediaLibraryItem;
  onClose: () => void;
  formatWhen: (ts: TimestampInput) => string;
  onSchedule: () => void;
  canSchedule: boolean;
  onPreviewImage: (url: string, alt?: string) => void;
}) {
  const [researchOpen, setResearchOpen] = useState(false);
  const mediaPreview = resolveSchedulableMediaPreview({
    mediaType: item.mediaType,
    imageUrl: item.imageUrl,
    videoUrl: item.videoUrl,
    posterUrl: item.posterUrl,
  });
  const carouselSlides = Array.isArray(item.carouselSlides)
    ? item.carouselSlides
        .map((s, i) => ({
          index: s.index ?? i + 1,
          imageUrl: String(s.imageUrl ?? '').trim(),
          headline: s.headline ?? null,
        }))
        .filter((s) => s.imageUrl)
    : [];
  const isCarousel =
    item.mediaType === 'carousel' ||
    item.collection === 'carouselGeneratedPosts' ||
    carouselSlides.length >= 2;
  const generatedBy = generatedByForCollection(item.collection);
  const contentTypeLabel = contentTypeDisplayLabel(item);
  const researchDetails = mergeGenerationResearch(item.research, {
    contentType: item.contentType,
    contentTypeLabel: item.contentTypeLabel ?? (contentTypeLabel || null),
    contentAngle: item.research?.contentAngle ?? null,
  });
  const showResearch = hasViewableResearch(researchDetails);

  useEffect(() => {
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = previousOverflow;
    };
  }, []);

  return createPortal(
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4 sm:p-6 bg-black/50 backdrop-blur-sm"
      style={{ minHeight: '100dvh', height: '100dvh' }}
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="media-detail-modal-title"
    >
      <div
        className="rounded-2xl border border-border bg-card text-foreground shadow-xl max-w-lg w-full max-h-[90vh] flex flex-col min-h-0 overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="shrink-0 p-4 border-b border-border flex items-center justify-between gap-3">
          <h2 id="media-detail-modal-title" className="text-lg font-semibold">
            Media details
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground focus:outline-none focus:ring-2 focus:ring-primary/40"
            aria-label="Close"
          >
            <svg
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
        <div className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden px-4 pt-4 pb-10 space-y-4 overscroll-contain">
          {isCarousel && carouselSlides.length > 0 ? (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">
                Carousel
                {item.slideCount
                  ? ` · ${item.slideCount} slides`
                  : ` · ${carouselSlides.length} slides`}
              </p>
              <CarouselSwipePreview
                slides={carouselSlides}
                showCaptions
                onImageClick={onPreviewImage}
              />
              <div className="flex flex-col sm:flex-row flex-wrap gap-3 mt-4">
                {canSchedule ? (
                  <Button
                    type="button"
                    className="rounded-lg bg-gradient-primary text-white shadow-lg shadow-primary/20"
                    onClick={onSchedule}
                  >
                    <Calendar className="mr-2 h-4 w-4" />
                    Schedule post
                  </Button>
                ) : null}
              </div>
            </div>
          ) : mediaPreview.isVideo && mediaPreview.videoUrl ? (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Video</p>
              <PostMediaPreview
                preview={mediaPreview}
                controls
                muted={false}
                videoClassName="w-full max-h-64 rounded-xl bg-black border border-border"
              />
              <div className="flex flex-col sm:flex-row flex-wrap gap-3 mt-4">
                <a
                  href={mediaPreview.videoUrl}
                  download={`media-library-${item.collection}-${item.id}.mp4`}
                  className="inline-flex items-center justify-center rounded-lg border border-primary/30 bg-card px-4 py-2 text-sm font-medium text-primary hover:bg-primary/10"
                >
                  Download video
                </a>
                {canSchedule ? (
                  <Button
                    type="button"
                    className="rounded-lg bg-gradient-primary text-white shadow-lg shadow-primary/20"
                    onClick={onSchedule}
                  >
                    <Calendar className="mr-2 h-4 w-4" />
                    Schedule post
                  </Button>
                ) : null}
              </div>
            </div>
          ) : mediaPreview.imageUrl ? (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Image</p>
              <button
                type="button"
                onClick={() =>
                  onPreviewImage(mediaPreview.imageUrl as string, 'Gallery image')
                }
                className="group relative block w-full overflow-hidden rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-primary"
                aria-label="Open image preview"
              >
                <PostMediaPreview
                  preview={mediaPreview}
                  imageClassName="w-full max-h-64 object-contain rounded-xl bg-muted border border-border transition-transform duration-200 group-hover:scale-[1.01]"
                />
              </button>
              <div className="flex flex-col sm:flex-row flex-wrap gap-3 mt-4">
                <ImagePreviewButton
                  onClick={() =>
                    onPreviewImage(
                      mediaPreview.imageUrl as string,
                      'Gallery image'
                    )
                  }
                  className="rounded-lg border border-primary/30 bg-card text-primary hover:bg-primary/10 hover:opacity-100 px-4 py-2"
                />
                <DownloadPngButton
                  url={mediaPreview.imageUrl as string}
                  getFilename={() =>
                    `media-library-${item.collection}-${item.id}-${Date.now()}.png`
                  }
                />
                <SharePostButton
                  imageUrl={mediaPreview.imageUrl}
                  caption={mediaCaptionLabel(item.caption)}
                  platform={item.platform}
                  getFilename={() =>
                    `media-library-${item.collection}-${item.id}-${Date.now()}.png`
                  }
                  className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:opacity-90 transition disabled:opacity-60"
                />
                {canSchedule ? (
                  <Button
                    type="button"
                    className="rounded-lg bg-gradient-primary text-white shadow-lg shadow-primary/20"
                    onClick={onSchedule}
                  >
                    <Calendar className="mr-2 h-4 w-4" />
                    Schedule post
                  </Button>
                ) : null}
              </div>
              <div className="flex w-full justify-end">
                <a
                  href={mediaPreview.imageUrl ?? '#'}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-2 inline-flex items-center gap-2 rounded-lg bg-gradient-primary px-3 py-2 text-sm font-medium text-white shadow-lg shadow-primary/20"
                >
                  Open in new tab
                  <ExternalLink className="h-4 w-4" />
                </a>
              </div>
            </div>
          ) : (
            <div className="rounded-xl border border-dashed border-border bg-muted/40 px-4 py-8 text-center text-sm text-muted-foreground">
              Preview unavailable. Refresh the library or regenerate if the file
              was removed.
            </div>
          )}
          <DetailRow
            label="Caption / Message"
            value={mediaCaptionLabel(item.caption) || '—'}
            long
          />
          {item.scheduleAt ? (
            <DetailRow label="Schedule at" value={formatWhen(item.scheduleAt)} />
          ) : null}
          <DetailRow label="Created at" value={formatWhen(item.createdAt)} />
          <DetailRow
            label="Platform"
            value={
              item.platform
                ? item.platform.replace(/_/g, ' ')
                : '—'
            }
          />
          {generatedBy ? (
            <DetailRow label="Generated by" value={generatedBy} />
          ) : null}
          {showResearch ? (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-2">
                Research
              </p>
              <Button
                type="button"
                variant="outline"
                className="rounded-lg border-primary/30 text-primary hover:bg-primary/10"
                onClick={() => setResearchOpen(true)}
              >
                <Search className="mr-2 h-4 w-4" />
                View research
              </Button>
            </div>
          ) : null}
          {!item.scheduleAt && item.targetCalendarDate ? (
            <DetailRow
              label="Scheduled date"
              value={item.targetCalendarDate}
            />
          ) : null}
          {item.scheduledPostId && !canSchedule ? (
            <DetailRow label="Status" value="Scheduled" />
          ) : null}
        </div>
      </div>
      <GenerationResearchDialog
        open={researchOpen}
        onClose={() => setResearchOpen(false)}
        research={researchDetails}
      />
    </div>,
    document.body
  );
}

/**
 * Campaign drafts ride a separate Firestore collection and have their own
 * scheduling endpoint (the date is locked to whatever the user picked when
 * generating the campaign — only the time of day is editable here).
 */
function isSchedulableCampaignDraft(
  item: GeneratedMediaLibraryItem
): item is GeneratedMediaLibraryItem & {
  campaignDraftId: string;
  targetCalendarDate: string;
} {
  const now = new Date();
  const today = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(
    now.getDate()
  ).padStart(2, '0')}`;
  return (
    item.collection === 'campaignDrafts' &&
    !item.earlierScheduled &&
    !item.scheduledPostId &&
    !!item.campaignDraftId &&
    !!item.targetCalendarDate &&
    item.targetCalendarDate >= today
  );
}

type CampaignDraftScheduleModalProps = {
  draftId: string;
  /** Locked YYYY-MM-DD — the user already committed to this date when
   *  generating the campaign. Surfaced as a disabled input. */
  targetDate: string;
  onClose: () => void;
  onScheduled: () => void;
};

function CampaignDraftScheduleModal({
  draftId,
  targetDate,
  onClose,
  onScheduled,
}: CampaignDraftScheduleModalProps) {
  const [time, setTime] = useState<string>('09:00');
  const [scheduling, setScheduling] = useState(false);

  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const onKey = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  const handleSchedule = useCallback(async () => {
    if (scheduling) return;
    if (!time) {
      showErrorToast('Pick a time first.');
      return;
    }
    const iso = new Date(`${targetDate}T${time}`);
    if (Number.isNaN(iso.getTime())) {
      showErrorToast('Invalid time.');
      return;
    }
    if (iso.getTime() < Date.now()) {
      showErrorToast('Pick a time in the future.');
      return;
    }
    try {
      setScheduling(true);
      await scheduleCampaignDraftApi({
        draftId,
        scheduleAt: iso.toISOString(),
      });
      toast.success('Draft scheduled.');
      onScheduled();
      onClose();
    } catch (err) {
      showErrorToast('Could not schedule this draft.');
    } finally {
      setScheduling(false);
    }
  }, [draftId, onClose, onScheduled, scheduling, targetDate, time]);

  return createPortal(
    <div
      className="fixed inset-0 z-[250] flex items-center justify-center bg-black/55 p-4 backdrop-blur-sm"
      style={{ minHeight: '100dvh' }}
      role="dialog"
      aria-modal="true"
      aria-labelledby="campaign-draft-schedule-title"
      onClick={onClose}
    >
      <div
        className="w-full max-w-sm rounded-2xl border border-border bg-card p-5 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <h3
          id="campaign-draft-schedule-title"
          className="text-base font-semibold text-foreground"
        >
          Schedule campaign draft
        </h3>
        <p className="mt-1 text-xs text-muted-foreground">
          The date was locked when you created the campaign. Pick a time of day
          and we&apos;ll queue it for publishing.
        </p>

        <div className="mt-4 grid grid-cols-2 gap-3">
          <label className="flex flex-col text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            Date <span className="ml-1 normal-case text-muted-foreground/70">(locked)</span>
            <input
              type="date"
              value={targetDate}
              disabled
              readOnly
              aria-readonly="true"
              className="mt-1 rounded-lg border border-border bg-muted px-2 py-1.5 text-xs font-medium text-muted-foreground cursor-not-allowed"
            />
          </label>
          <label className="flex flex-col text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            Time
            <input
              type="time"
              value={time}
              onChange={(e) => setTime(e.target.value)}
              className="mt-1 rounded-lg border border-border bg-card px-2 py-1.5 text-xs font-medium text-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none"
            />
          </label>
        </div>

        <div className="mt-5 flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            disabled={scheduling}
            className="rounded-lg px-3 py-1.5 text-xs font-semibold text-muted-foreground hover:bg-accent hover:text-foreground disabled:opacity-60"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSchedule}
            disabled={scheduling}
            className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-bold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {scheduling ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : (
              <CalendarPlus className="h-3.5 w-3.5" />
            )}
            Schedule
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}

export default function MediaLibraryPage() {
  const router = useRouter();
  const { billing } = useUserPlanCredits();
  const planActionsAllowed = !isPlanInactive(billing);
  const fmtTimestamp = useTimestampFormatter();
  // 24-hour, in the user's preferred timezone (DST handled automatically).
  // Format mirrors the previous "MMM d, yyyy · h:mm a" but in HH:mm.
  const formatWhen = (ts: TimestampInput) =>
    fmtTimestamp(ts, { format: 'MMM d, yyyy · HH:mm' });
  const [source, setSource] = useState<'all' | GeneratedMediaSource>('all');
  const [items, setItems] = useState<GeneratedMediaLibraryItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState('');
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);
  const [selectedItem, setSelectedItem] =
    useState<GeneratedMediaLibraryItem | null>(null);
  /** Campaign draft currently being scheduled via the inline modal. Lives
   *  alongside `selectedItem` so the schedule modal can stack over the
   *  detail modal without unmounting it. */
  const [schedulingDraft, setSchedulingDraft] = useState<
    | (GeneratedMediaLibraryItem & {
        campaignDraftId: string;
        targetCalendarDate: string;
      })
    | null
  >(null);
  const sentinelRef = useRef<HTMLDivElement>(null);
  const imagePreview = useImagePreview();
  /** Bumped on every fresh `load` so late responses cannot overwrite a newer tab. */
  const loadGenerationRef = useRef(0);

  const load = useCallback(async () => {
    const generation = ++loadGenerationRef.current;
    setLoading(true);
    setError('');
    setItems([]);
    setNextCursor(null);
    setHasMore(false);
    try {
      const data = await getGeneratedMediaLibraryApi({ source });
      if (generation !== loadGenerationRef.current) return;
      setItems(data?.items ?? []);
      setNextCursor(data?.nextCursor ?? null);
      setHasMore(data?.hasMore ?? false);
    } catch (e) {
      if (generation !== loadGenerationRef.current) return;
      setError('Could not load your library.');
    } finally {
      if (generation === loadGenerationRef.current) {
        setLoading(false);
      }
    }
  }, [source]);

  useEffect(() => {
    void load();
  }, [load]);

  const loadMore = useCallback(async () => {
    if (!hasMore || !nextCursor || loadingMore) return;
    const generation = loadGenerationRef.current;
    const cursor = nextCursor;
    setLoadingMore(true);
    try {
      const data = await getGeneratedMediaLibraryApi({
        source,
        cursor,
      });
      if (generation !== loadGenerationRef.current) return;
      setItems((prev) => [...prev, ...(data?.items ?? [])]);
      setNextCursor(data?.nextCursor ?? null);
      setHasMore(data?.hasMore ?? false);
    } catch (e) {
      if (generation !== loadGenerationRef.current) return;
      setError('Could not load more items.');
    } finally {
      if (generation === loadGenerationRef.current) {
        setLoadingMore(false);
      }
    }
  }, [source, nextCursor, hasMore, loadingMore]);

  useEffect(() => {
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) void loadMore();
      },
      { threshold: 0.1 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [loadMore]);

  const handleScheduleFromGallery = useCallback(
    (item: GeneratedMediaLibraryItem) => {
      if (!planActionsAllowed) {
        showErrorToast('Your plan has expired. Renew to schedule posts.');
        return;
      }
      // Campaign drafts have their own scheduling endpoint and the date is
      // fixed by the campaign generator. Open the inline modal instead of
      // routing to the generic post scheduler.
      if (isSchedulableCampaignDraft(item)) {
        setSchedulingDraft(item);
        return;
      }
      const post = galleryItemToPrefillPost(item);
      if (!post) return;
      const prefillPayload: PostSchedulerPrefillPayload = {
        source: 'gallery',
        createdAt: Date.now(),
        lockedPlatform: post.platform,
        posts: [post],
      };
      setPostSchedulerPrefill(prefillPayload);
      setSelectedItem(null);
      router.push(`${WORKSPACE_NAV_HREFS.schedulePost}?prefill=gallery`);
    },
    [router, planActionsAllowed]
  );

  const handleDraftScheduled = useCallback(() => {
    setSelectedItem(null);
    void load();
  }, [load]);

  const emptyCopy = useMemo(() => {
    if (source === 'all') {
      return 'Generated images from Content Studio, Carousel Posts, and Product Ads will appear here.';
    }
    if (source === 'instant-generation') {
      return 'New Content Studio runs save images here automatically. Older runs may not have stored files.';
    }
    if (source === 'carouselGeneratedPosts') {
      return 'Carousels from Carousel Posts appear here until you schedule them.';
    }
    if (source === 'videoGeneration') {
      return 'Videos from Video Generator appear here after generation.';
    }
    if (source === 'eventPosts') {
      return 'Event Studio posts with images are listed here.';
    }
    if (source === 'campaignDrafts') {
      return 'Campaign drafts appear here until you schedule them.';
    }
    if (source === 'aiEnginePosts') {
      return 'AI Engine posts with images are listed here.';
    }
    return 'Product Ads generations with images are listed here.';
  }, [source]);

  return (
    <div
      id="tour-gl-grid"
      className="mx-auto max-w-6xl space-y-8 pb-12"
    >
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">
          {workspacePageTitle(WORKSPACE_NAV_HREFS.gallery)}
        </h1>
        <p className="text-sm text-muted-foreground max-w-2xl">
          A single place for images produced across SocioGenie. Each Content Studio or Product Ads image can be
          scheduled once from the media library. Links expire after about an hour—refresh
          if an image stops loading.
        </p>
      </header>

      <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
        <div className="flex flex-wrap gap-2">
          {SOURCE_OPTIONS.map((opt) => {
            const active = source === opt.value;
            return (
              <Button
                key={opt.value}
                type="button"
                variant={active ? 'default' : 'outline'}
                size="sm"
                className={cn('rounded-full', active && 'shadow-sm')}
                onClick={() => {
                  if (opt.value === source) return;
                  loadGenerationRef.current += 1;
                  setSelectedItem(null);
                  setItems([]);
                  setNextCursor(null);
                  setHasMore(false);
                  setError('');
                  setLoading(true);
                  setSource(opt.value);
                }}
              >
                {opt.label}
              </Button>
            );
          })}
        </div>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          disabled={loading}
          onClick={() => void load()}
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Loading
            </>
          ) : (
            'Refresh'
          )}
        </Button>
      </div>

      {error ? (
        <div
          role="alert"
          className="rounded-xl border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm text-destructive"
        >
          {error}
        </div>
      ) : null}

      {loading ? (
        <PageLoadingState
          className="min-h-[40vh]"
          message="Loading your images…"
        />
      ) : null}

      {!loading && items.length === 0 ? (
        <div className="flex min-h-[36vh] flex-col items-center justify-center gap-4 rounded-2xl border border-dashed border-border/80 bg-muted/20 px-6 py-16 text-center">
          <div className="rounded-full bg-muted p-4">
            <ImageIcon className="h-8 w-8 text-muted-foreground" />
          </div>
          <div className="space-y-2 max-w-md">
            <p className="font-medium text-foreground">No images yet</p>
            <p className="text-sm text-muted-foreground">{emptyCopy}</p>
          </div>
          <div className="flex flex-wrap items-center justify-center gap-2 pt-2">
            <Button asChild variant="secondary" size="sm">
              <Link href={WORKSPACE_NAV_HREFS.quickCreate}>
                {workspacePageTitle(WORKSPACE_NAV_HREFS.quickCreate)}
              </Link>
            </Button>
            <Button asChild variant="outline" size="sm">
              <Link href={WORKSPACE_NAV_HREFS.productAdvert}>
                {workspacePageTitle(WORKSPACE_NAV_HREFS.productAdvert)}
              </Link>
            </Button>
            <Button asChild variant="outline" size="sm">
              <Link href={WORKSPACE_NAV_HREFS.carouselCreate}>
                {workspacePageTitle(WORKSPACE_NAV_HREFS.carouselCreate)}
              </Link>
            </Button>
            <Button asChild variant="outline" size="sm">
              <Link href={WORKSPACE_NAV_HREFS.festivePost}>
                {workspacePageTitle(WORKSPACE_NAV_HREFS.festivePost)}
              </Link>
            </Button>
          </div>
        </div>
      ) : null}

      {!loading && items.length > 0 ? (
        <ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {items.map((item) => {
            const generatedBy = generatedByForCollection(item.collection);
            const mediaPreview = resolveSchedulableMediaPreview({
              mediaType: item.mediaType,
              imageUrl: item.imageUrl,
              videoUrl: item.videoUrl,
              posterUrl: item.posterUrl,
            });
            const hasMedia = hasSchedulableMediaPreview(mediaPreview);
            const captionLabel = mediaCaptionLabel(item.caption);
            const contentTypeLabel = contentTypeDisplayLabel(item);
            const canSchedule =
              planActionsAllowed &&
              (galleryItemCanSchedule(item) ||
                isSchedulableCampaignDraft(item));
            const whenLabel = formatWhen(item.scheduleAt ?? item.createdAt);
            const slideCount =
              item.mediaType === 'carousel' ||
              item.collection === 'carouselGeneratedPosts'
                ? item.slideCount ??
                  (Array.isArray(item.carouselSlides)
                    ? item.carouselSlides.length
                    : null)
                : null;
            return (
              <li
                key={item.id}
                role="button"
                tabIndex={0}
                onClick={() => setSelectedItem(item)}
                onKeyDown={(e: KeyboardEvent<HTMLLIElement>) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    setSelectedItem(item);
                  }
                }}
                className={cn(
                  'group relative flex min-w-0 flex-col rounded-2xl border border-border bg-card p-4 shadow-sm',
                  'transition-all duration-300 cursor-pointer',
                  'hover:border-primary/35 hover:bg-accent/40',
                  'hover:shadow-md hover:shadow-primary/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30'
                )}
              >
                <div className="relative mb-3 overflow-hidden rounded-xl border border-border bg-muted aspect-4/3">
                  {hasMedia ? (
                    <PostMediaPreview
                      preview={mediaPreview}
                      videoClassName="h-full w-full object-cover bg-black"
                      imageClassName="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]"
                    />
                  ) : (
                    <div className="flex h-full min-h-[140px] flex-col items-center justify-center gap-2 px-4 text-center text-sm text-muted-foreground">
                      <ImageOff
                        className="h-8 w-8 text-muted-foreground/70"
                        aria-hidden
                      />
                      <span>Preview unavailable</span>
                    </div>
                  )}
                  {slideCount && slideCount > 1 ? (
                    <div className="absolute left-2 bottom-2">
                      <span className="inline-flex items-center rounded-md border border-border bg-card/95 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-foreground shadow-sm backdrop-blur">
                        {slideCount} slides
                      </span>
                    </div>
                  ) : null}
                  {!mediaPreview.isVideo && mediaPreview.imageUrl ? (
                    <div className="absolute bottom-2 right-2">
                      <ImagePreviewButton
                        variant="overlay-icon"
                        stopPropagation
                        onClick={() =>
                          imagePreview.open(
                            mediaPreview.imageUrl as string,
                            'Gallery image'
                          )
                        }
                      />
                    </div>
                  ) : null}
                  {generatedBy ? (
                    <div className="absolute right-2 top-2 max-w-[60%]">
                      <span
                        className="inline-flex items-center gap-1 rounded-md border border-border bg-card/95 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-foreground shadow-sm backdrop-blur"
                        title={`Generated by: ${generatedBy}`}
                      >
                        <Sparkles className="h-3 w-3 text-primary" />
                        <span className="truncate">{generatedBy}</span>
                      </span>
                    </div>
                  ) : null}
                </div>

                <p className="line-clamp-3 text-sm font-medium leading-snug text-foreground">
                  {captionLabel ? (
                    captionLabel
                  ) : (
                    <span className="text-muted-foreground italic">No caption</span>
                  )}
                </p>

                <div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
                  <span className="inline-flex items-center gap-1.5">
                    <Calendar className="h-3.5 w-3.5 text-primary" />
                    <span className="truncate">{whenLabel}</span>
                  </span>
                  {item.platform ? (
                    <>
                      <span className="text-muted-foreground/60">·</span>
                      <span className="capitalize text-muted-foreground">
                        {item.platform.replace(/_/g, ' ')}
                      </span>
                    </>
                  ) : null}
                  {item.creditsCharged != null && item.creditsCharged > 0 ? (
                    <>
                      <span className="text-muted-foreground/60">·</span>
                      <span
                        className="tabular-nums text-muted-foreground"
                        title="Credits charged for this generation"
                      >
                        {item.creditsCharged}{' '}
                        {item.creditsCharged === 1 ? 'credit' : 'credits'}
                      </span>
                    </>
                  ) : null}
                </div>

                <div className="mt-2 space-y-1">
                  {canSchedule ? (
                    <p className="text-[11px] font-medium text-primary">
                      Ready to schedule
                    </p>
                  ) : item.earlierScheduled ? (
                    <p className="text-[11px] text-muted-foreground">
                      Already scheduled
                    </p>
                  ) : null}
                  <p className="text-[11px] text-muted-foreground/70 group-hover:text-muted-foreground">
                    Click for full details
                  </p>
                </div>
              </li>
            );
          })}
        </ul>
      ) : null}
      {selectedItem ? (
        <MediaDetailModal
          item={selectedItem}
          onClose={() => setSelectedItem(null)}
          formatWhen={formatWhen}
          canSchedule={
            planActionsAllowed &&
            (galleryItemCanSchedule(selectedItem) ||
              isSchedulableCampaignDraft(selectedItem))
          }
          onSchedule={() => handleScheduleFromGallery(selectedItem)}
          onPreviewImage={imagePreview.open}
        />
      ) : null}
      {schedulingDraft && planActionsAllowed ? (
        <CampaignDraftScheduleModal
          draftId={schedulingDraft.campaignDraftId}
          targetDate={schedulingDraft.targetCalendarDate}
          onClose={() => setSchedulingDraft(null)}
          onScheduled={handleDraftScheduled}
        />
      ) : null}
      <div ref={sentinelRef} style={{ height: 1 }} />
      <ImagePreviewOverlay
        src={imagePreview.previewUrl}
        alt={imagePreview.previewAlt}
        onClose={imagePreview.close}
      />
    </div>
  );
}
