import axiosClient from '@/lib/axios';

/** Hard cap on how many days a single campaign can plan. Mirrors the
 *  backend constant so the two layers can never drift. Used for the
 *  date-picker window; AI idea length defaults to {@link DEFAULT_CAMPAIGN_PLAN_DAYS}. */
export const MAX_CAMPAIGN_DAYS = 7;
/** Default AI campaign idea length (manual + auto-mode). */
export const DEFAULT_CAMPAIGN_PLAN_DAYS = 5;
/** Default suggestion-set size when the page first loads. */
export const DEFAULT_CAMPAIGN_SET_SIZE = 5;
/** Credit cost per (day × platform) — mirrors backend
 *  `CAMPAIGN_CREDIT_PER_DAY`. Update both in lockstep. */
export const CAMPAIGN_CREDIT_PER_DAY = 3;
/** Credit cost per paid regeneration. Mirrors backend
 *  `CAMPAIGN_REGENERATE_CREDIT`. Max 2 regens per draft: 1st free, 2nd paid. */
export const CAMPAIGN_REGENERATE_CREDIT = 1;
export const MAX_CAMPAIGN_REGENERATIONS = 2;

export type CampaignDayPlan = {
  dayNumber: number;
  title: string;
  reference: string;
  caption?: string;
};

export type CampaignSuggestion = {
  id: string;
  theme: string;
  description: string;
  goal?: string;
  generatedAt: string;
  days: CampaignDayPlan[];
};

export type CampaignSuggestionSet = {
  suggestions: CampaignSuggestion[];
  /** Server-clamped max days for THIS user (capped by plan window + 5-day
   *  campaign plan default). When null, the saved set predates this field —
   *  treat as the default 5-day plan length. */
  maxDays: number | null;
  /** Goal the set was generated against. Null when the user did not supply
   *  one. */
  goal: string | null;
  /** `true` when this set was generated by the auto-mode campaign seed
   *  (NOT the user clicking "Generate ideas"). Drives the
   *  "AI picked this idea for you" badge + reason on the UI. */
  autoSeeded?: boolean;
  /** When `autoSeeded`, the id of the suggestion the auto-mode picker
   *  selected to actually run. Always present alongside `autoSeeded`. */
  pickedSuggestionId?: string | null;
  /** 1\u20132 sentence justification the picker returned. Surfaced verbatim
   *  beneath the picked card. */
  pickedReason?: string | null;
};

// -----------------------------------------------------------------------------
// Suggestion lifecycle
// -----------------------------------------------------------------------------

/**
 * Generate a fresh set of N campaign suggestions. The backend clamps `count`
 * to `[1..5]` and sizes `maxDays` to the user's remaining plan window.
 */
export async function suggestCampaignSetApi(params: {
  goal?: string;
  count?: number;
}): Promise<CampaignSuggestionSet> {
  const response = await axiosClient.post<{
    success: boolean;
    data: CampaignSuggestionSet;
    message?: string;
  }>('/api/v1/campaign/suggest-set', {
    goal: params.goal?.trim() || undefined,
    count: params.count,
  });
  return response.data.data;
}

/**
 * Fetch the user's currently-saved suggestion set. Returns an empty
 * `{ suggestions: [] }` envelope when there's nothing saved yet.
 */
export async function getCampaignSuggestionsApi(): Promise<CampaignSuggestionSet> {
  const response = await axiosClient.get<{
    success: boolean;
    data: CampaignSuggestionSet;
    message?: string;
  }>('/api/v1/campaign/suggestions');
  return response.data.data;
}

/**
 * Regenerate ONE card in the saved suggestion set. Returns the replacement
 * suggestion (same `id` as the one it replaced, fresh `generatedAt`).
 */
export async function regenerateCampaignApi(
  suggestionId: string
): Promise<CampaignSuggestion> {
  const response = await axiosClient.post<{
    success: boolean;
    data: { suggestion: CampaignSuggestion };
    message?: string;
  }>('/api/v1/campaign/regenerate', { suggestionId });
  return response.data.data.suggestion;
}

// -----------------------------------------------------------------------------
// Create / draft lifecycle
// -----------------------------------------------------------------------------

export type CreateCampaignDayInput = {
  /** YYYY-MM-DD in the caller's timezone — server validates against the
   *  user's account timezone before enqueueing. */
  date: string;
  title: string;
  reference: string;
  caption?: string;
  dayNumber?: number;
};

export type CreateCampaignParams = {
  theme: string;
  description?: string;
  goal?: string;
  days: CreateCampaignDayInput[];
  /** Inclusive builder window (`YYYY-MM-DD`) — wider than drafted day dates. */
  windowStart?: string;
  windowEnd?: string;
  /** Optional explicit platform list. When omitted the server uses the
   *  caller's `selected` accounts (same default as festive-post). */
  platforms?: string[];
  /** Optional reference to the saved suggestion that seeded this campaign —
   *  helps server-side analytics tie drafts back to a card. */
  suggestionId?: string;
};

/** Response from `POST /api/v1/campaign/create` (queued to Cloud Tasks). */
export type CreateCampaignResponse = {
  accepted?: boolean;
  parentJobId?: string;
  successCount: number;
  failedCount: number;
  dayCount: number;
  platforms: string[];
  /** Total credits charged when every (day × platform) succeeds. */
  requiredCredits: number;
  /** Number of draft docs expected for this enqueue (platform × day). */
  expectedDraftCount?: number;
};

export async function createCampaignApi(
  params: CreateCampaignParams
): Promise<CreateCampaignResponse> {
  const response = await axiosClient.post<{
    success: boolean;
    data: CreateCampaignResponse;
    message?: string;
  }>('/api/v1/campaign/create', {
    theme: params.theme,
    description: params.description,
    goal: params.goal,
    days: params.days,
    windowStart: params.windowStart,
    windowEnd: params.windowEnd,
    platforms: params.platforms,
    suggestionId: params.suggestionId,
  });
  return response.data.data;
}

// -----------------------------------------------------------------------------
// Drafts
// -----------------------------------------------------------------------------

/** Firestore-typed shape returned from `GET /campaign/drafts`. */
export type CampaignDraft = {
  draftId: string;
  status: 'draft' | 'scheduled' | string;
  platform: string | null;
  message: string | null;
  imageUrl: string | null;
  imageFilePath: string | null;
  /** YYYY-MM-DD the campaign generator was targeting for this day. */
  targetDate: string | null;
  eventName: string | null;
  campaignTheme: string | null;
  campaignGoal: string | null;
  /** Shared across every draft from one campaign generation run. */
  parentJobId: string | null;
  /** Inclusive calendar window from the campaign builder anchor. */
  campaignWindowStart: string | null;
  campaignWindowEnd: string | null;
  /** Number of times this draft has been successfully regenerated.
   *  `0` => the next regen is FREE; anything `>= 1` => 1 credit. */
  regenerationCount: number;
  scheduledPostId: string | null;
  /** Firestore timestamp objects come back as `{ _seconds, _nanoseconds }`.
   *  Kept loosely-typed so the UI can format defensively. */
  scheduledAt: unknown;
  createdAt: unknown;
  /** True when this draft was produced by auto-mode campaign seed. */
  autoSeeded?: boolean;
  /** Soft-removed by the user — stays visible as "Removed by you". */
  userRemoved?: boolean;
};

export async function listCampaignDraftsApi(params?: {
  status?: 'draft' | 'scheduled';
  limit?: number;
}): Promise<CampaignDraft[]> {
  const response = await axiosClient.get<{
    success: boolean;
    data: { drafts: CampaignDraft[] };
    message?: string;
  }>('/api/v1/campaign/drafts', {
    params: {
      status: params?.status,
      limit: params?.limit,
    },
  });
  return response.data.data.drafts;
}

export type ScheduleCampaignDraftResponse = {
  draftId: string;
  scheduledPostId: string;
  scheduledAt: string;
};

export async function scheduleCampaignDraftApi(params: {
  draftId: string;
  /** ISO-8601 string. Server treats `<now` as an error. */
  scheduleAt: string;
}): Promise<ScheduleCampaignDraftResponse> {
  const response = await axiosClient.post<{
    success: boolean;
    data: ScheduleCampaignDraftResponse;
    message?: string;
  }>(`/api/v1/campaign/drafts/${encodeURIComponent(params.draftId)}/schedule`, {
    scheduleAt: params.scheduleAt,
  });
  return response.data.data;
}

export async function deleteCampaignDraftApi(params: {
  draftId: string;
}): Promise<{ draftId: string; userRemoved?: boolean }> {
  const response = await axiosClient.delete<{
    success: boolean;
    data: { draftId: string; userRemoved?: boolean };
    message?: string;
  }>(`/api/v1/campaign/drafts/${encodeURIComponent(params.draftId)}`);
  return response.data.data;
}

export type RegenerateCampaignDraftResponse = {
  accepted?: boolean;
  parentJobId?: string;
  draftId: string;
  /** Exact credit amount the worker will deduct on success. `0` for the
   *  user's free first regen. */
  chargeCredits: number;
  /** `regenerationCount` BEFORE this run — UI shows it for transparency. */
  regenerationCountBefore: number;
  successCount?: number;
  failedCount?: number;
  regeneratedDraftId?: string;
};

/**
 * Regenerate a single campaign draft synchronously (worker overwrites in place).
 *
 * Pricing: free for the first regen of any given draft, then 1 credit
 * for every regen after that. The exact charge for THIS attempt is in
 * `chargeCredits` on the response.
 */
export async function regenerateCampaignDraftApi(params: {
  draftId: string;
}): Promise<RegenerateCampaignDraftResponse> {
  const response = await axiosClient.post<{
    success: boolean;
    data: RegenerateCampaignDraftResponse;
    message?: string;
  }>(
    `/api/v1/campaign/drafts/${encodeURIComponent(params.draftId)}/regenerate`,
    {}
  );
  return response.data.data;
}

/**
 * Convenience helper: the dollar-cost of the NEXT regen for a draft. Free
 * on the first attempt (`regenerationCount === 0`), `CAMPAIGN_REGENERATE_CREDIT`
 * on the second (`=== 1`). No further regens after that.
 */
export function canRegenerateDraft(regenerationCount: number): boolean {
  const count =
    typeof regenerationCount === 'number' && Number.isFinite(regenerationCount)
      ? Math.max(0, Math.floor(regenerationCount))
      : 0;
  return count < MAX_CAMPAIGN_REGENERATIONS;
}

export function nextRegenerationCost(regenerationCount: number): number {
  const count =
    typeof regenerationCount === 'number' && Number.isFinite(regenerationCount)
      ? Math.max(0, Math.floor(regenerationCount))
      : 0;
  return count === 1 ? CAMPAIGN_REGENERATE_CREDIT : 0;
}
