// Auto-generated by scripts/bundle-legal-content.mjs — do not edit.

export type LicenseNoticeEntry = {
  name: string;
  repository: string;
};

export type LicenseNoticeSection = {
  license: string;
  count: number;
  entries: LicenseNoticeEntry[];
};

export const licensesNotices = {
  "generatedDate": "2026-05-29",
  "total": 685,
  "summary": [
    {
      "license": "MIT",
      "count": 516
    },
    {
      "license": "Apache-2.0",
      "count": 81
    },
    {
      "license": "ISC",
      "count": 48
    },
    {
      "license": "BSD-3-Clause",
      "count": 22
    },
    {
      "license": "BlueOak-1.0.0",
      "count": 6
    },
    {
      "license": "BSD-2-Clause",
      "count": 5
    },
    {
      "license": "Apache-2.0 AND LGPL-3.0-or-later",
      "count": 1
    },
    {
      "license": "Python-2.0",
      "count": 1
    },
    {
      "license": "CC-BY-4.0",
      "count": 1
    },
    {
      "license": "(BSD-3-Clause OR GPL-2.0)",
      "count": 1
    },
    {
      "license": "0BSD",
      "count": 1
    },
    {
      "license": "(MIT OR CC0-1.0)",
      "count": 1
    },
    {
      "license": "MIT AND ISC",
      "count": 1
    }
  ],
  "sections": [
    {
      "license": "MIT",
      "count": 516,
      "entries": [
        {
          "name": "@antfu/ni@25.0.0",
          "repository": "https://github.com/antfu-collective/ni"
        },
        {
          "name": "@babel/code-frame@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/compat-data@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/core@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/generator@7.29.1",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-annotate-as-pure@7.27.3",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-compilation-targets@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-create-class-features-plugin@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-globals@7.28.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-member-expression-to-functions@7.28.5",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-module-imports@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-module-transforms@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-optimise-call-expression@7.27.1",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-plugin-utils@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-replace-supers@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-skip-transparent-expression-wrappers@7.27.1",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-string-parser@7.27.1",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-validator-identifier@7.28.5",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helper-validator-option@7.27.1",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/helpers@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/parser@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/plugin-syntax-jsx@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/plugin-syntax-typescript@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/plugin-transform-modules-commonjs@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/plugin-transform-typescript@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/preset-typescript@7.28.5",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/runtime@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/template@7.28.6",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/traverse@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@babel/types@7.29.0",
          "repository": "https://github.com/babel/babel"
        },
        {
          "name": "@base-ui/react@1.3.0",
          "repository": "https://github.com/mui/base-ui"
        },
        {
          "name": "@base-ui/utils@0.2.6",
          "repository": "https://github.com/mui/base-ui"
        },
        {
          "name": "@date-fns/tz@1.4.1",
          "repository": "https://github.com/date-fns/tz"
        },
        {
          "name": "@ecies/ciphers@0.2.5",
          "repository": "https://github.com/ecies/js-ciphers"
        },
        {
          "name": "@fastify/busboy@3.2.0",
          "repository": "https://github.com/fastify/busboy"
        },
        {
          "name": "@floating-ui/core@1.7.5",
          "repository": "https://github.com/floating-ui/floating-ui"
        },
        {
          "name": "@floating-ui/dom@1.7.6",
          "repository": "https://github.com/floating-ui/floating-ui"
        },
        {
          "name": "@floating-ui/react-dom@2.1.8",
          "repository": "https://github.com/floating-ui/floating-ui"
        },
        {
          "name": "@floating-ui/utils@0.2.11",
          "repository": "https://github.com/floating-ui/floating-ui"
        },
        {
          "name": "@hono/node-server@1.19.11",
          "repository": "https://github.com/honojs/node-server"
        },
        {
          "name": "@img/colour@1.0.0",
          "repository": "https://github.com/lovell/colour"
        },
        {
          "name": "@inquirer/ansi@1.0.2",
          "repository": "https://github.com/SBoudrias/Inquirer.js"
        },
        {
          "name": "@inquirer/confirm@5.1.21",
          "repository": "https://github.com/SBoudrias/Inquirer.js"
        },
        {
          "name": "@inquirer/core@10.3.2",
          "repository": "https://github.com/SBoudrias/Inquirer.js"
        },
        {
          "name": "@inquirer/figures@1.0.15",
          "repository": "https://github.com/SBoudrias/Inquirer.js"
        },
        {
          "name": "@inquirer/type@3.0.10",
          "repository": "https://github.com/SBoudrias/Inquirer.js"
        },
        {
          "name": "@jridgewell/gen-mapping@0.3.13",
          "repository": "https://github.com/jridgewell/sourcemaps"
        },
        {
          "name": "@jridgewell/remapping@2.3.5",
          "repository": "https://github.com/jridgewell/sourcemaps"
        },
        {
          "name": "@jridgewell/resolve-uri@3.1.2",
          "repository": "https://github.com/jridgewell/resolve-uri"
        },
        {
          "name": "@jridgewell/sourcemap-codec@1.5.5",
          "repository": "https://github.com/jridgewell/sourcemaps"
        },
        {
          "name": "@jridgewell/trace-mapping@0.3.31",
          "repository": "https://github.com/jridgewell/sourcemaps"
        },
        {
          "name": "@js-sdsl/ordered-map@4.4.2",
          "repository": "https://github.com/js-sdsl/js-sdsl"
        },
        {
          "name": "@mendable/firecrawl-js@4.15.0",
          "repository": "https://github.com/firecrawl/firecrawl"
        },
        {
          "name": "@modelcontextprotocol/sdk@1.27.1",
          "repository": "https://github.com/modelcontextprotocol/typescript-sdk"
        },
        {
          "name": "@mswjs/interceptors@0.41.3",
          "repository": "https://github.com/mswjs/interceptors"
        },
        {
          "name": "@next/env@16.1.6",
          "repository": "https://github.com/vercel/next.js"
        },
        {
          "name": "@next/swc-win32-x64-msvc@16.1.6",
          "repository": "https://github.com/vercel/next.js"
        },
        {
          "name": "@noble/ciphers@1.3.0",
          "repository": "https://github.com/paulmillr/noble-ciphers"
        },
        {
          "name": "@noble/curves@1.9.7",
          "repository": "https://github.com/paulmillr/noble-curves"
        },
        {
          "name": "@noble/hashes@1.8.0",
          "repository": "https://github.com/paulmillr/noble-hashes"
        },
        {
          "name": "@nodelib/fs.scandir@2.1.5",
          "repository": "https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.scandir"
        },
        {
          "name": "@nodelib/fs.stat@2.0.5",
          "repository": "https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.stat"
        },
        {
          "name": "@nodelib/fs.walk@1.2.8",
          "repository": "https://github.com/nodelib/nodelib/tree/master/packages/fs/fs.walk"
        },
        {
          "name": "@open-draft/deferred-promise@2.2.0",
          "repository": "https://github.com/open-draft/deferred-promise"
        },
        {
          "name": "@open-draft/logger@0.3.0",
          "repository": "https://github.com/open-draft/logger"
        },
        {
          "name": "@open-draft/until@2.1.0",
          "repository": "https://github.com/open-draft/until"
        },
        {
          "name": "@pkgjs/parseargs@0.11.0",
          "repository": "https://github.com/pkgjs/parseargs"
        },
        {
          "name": "@radix-ui/number@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/primitive@1.1.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-accessible-icon@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-accordion@1.2.12",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-alert-dialog@1.1.15",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-arrow@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-aspect-ratio@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-avatar@1.1.10",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-checkbox@1.3.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-collapsible@1.1.12",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-collection@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-compose-refs@1.1.2",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-context-menu@2.2.16",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-context@1.1.2",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-dialog@1.1.15",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-direction@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-dismissable-layer@1.1.11",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-dropdown-menu@2.1.16",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-focus-guards@1.1.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-focus-scope@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-form@0.1.8",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-hover-card@1.1.15",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-id@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-label@2.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-menu@2.1.16",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-menubar@1.1.16",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-navigation-menu@1.2.14",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-one-time-password-field@0.1.8",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-password-toggle-field@0.1.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-popover@1.1.15",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-popper@1.2.8",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-portal@1.1.9",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-presence@1.1.5",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-primitive@2.1.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-progress@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-radio-group@1.3.8",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-roving-focus@1.1.11",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-scroll-area@1.2.10",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-select@2.2.6",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-separator@1.1.7",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-slider@1.3.6",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-slot@1.2.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-switch@1.2.6",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-tabs@1.1.13",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-toast@1.2.15",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-toggle-group@1.1.11",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-toggle@1.1.10",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-toolbar@1.1.11",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-tooltip@1.2.8",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-callback-ref@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-controllable-state@1.2.2",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-effect-event@0.0.2",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-escape-keydown@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-is-hydrated@0.1.0",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-layout-effect@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-previous@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-rect@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-use-size@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/react-visually-hidden@1.2.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@radix-ui/rect@1.1.1",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "@sec-ant/readable-stream@0.4.1",
          "repository": "https://github.com/Sec-ant/readable-stream"
        },
        {
          "name": "@sindresorhus/merge-streams@4.0.0",
          "repository": "https://github.com/sindresorhus/merge-streams"
        },
        {
          "name": "@tabby_ai/hijri-converter@1.0.5",
          "repository": ""
        },
        {
          "name": "@tootallnate/once@2.0.0",
          "repository": "https://github.com/TooTallNate/once"
        },
        {
          "name": "@ts-morph/common@0.27.0",
          "repository": "https://github.com/dsherret/ts-morph"
        },
        {
          "name": "@types/caseless@0.12.5",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-array@3.2.2",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-color@3.1.3",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-ease@3.0.2",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-interpolate@3.0.4",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-path@3.1.1",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-scale@4.0.9",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-shape@3.1.8",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-time@3.0.4",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/d3-timer@3.0.2",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/jsonwebtoken@9.0.10",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/long@4.0.2",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/ms@2.1.0",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/node@20.19.35",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/react-dom@19.2.3",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/react@19.2.14",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/request@2.48.13",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/statuses@2.0.6",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/tough-cookie@4.0.5",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "@types/validate-npm-package-name@4.0.2",
          "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped"
        },
        {
          "name": "abort-controller@3.0.0",
          "repository": "https://github.com/mysticatea/abort-controller"
        },
        {
          "name": "accepts@2.0.0",
          "repository": "https://github.com/jshttp/accepts"
        },
        {
          "name": "agent-base@6.0.2",
          "repository": "https://github.com/TooTallNate/node-agent-base"
        },
        {
          "name": "agent-base@7.1.4",
          "repository": "https://github.com/TooTallNate/proxy-agents"
        },
        {
          "name": "ajv-formats@3.0.1",
          "repository": "https://github.com/ajv-validator/ajv-formats"
        },
        {
          "name": "ajv@8.18.0",
          "repository": "https://github.com/ajv-validator/ajv"
        },
        {
          "name": "ansi-regex@5.0.1",
          "repository": "https://github.com/chalk/ansi-regex"
        },
        {
          "name": "ansi-regex@6.2.2",
          "repository": "https://github.com/chalk/ansi-regex"
        },
        {
          "name": "ansi-styles@4.3.0",
          "repository": "https://github.com/chalk/ansi-styles"
        },
        {
          "name": "ansi-styles@6.2.3",
          "repository": "https://github.com/chalk/ansi-styles"
        },
        {
          "name": "aria-hidden@1.2.6",
          "repository": "https://github.com/theKashey/aria-hidden"
        },
        {
          "name": "arrify@2.0.1",
          "repository": "https://github.com/sindresorhus/arrify"
        },
        {
          "name": "ast-types@0.16.1",
          "repository": "https://github.com/benjamn/ast-types"
        },
        {
          "name": "async-retry@1.3.3",
          "repository": "https://github.com/vercel/async-retry"
        },
        {
          "name": "asynckit@0.4.0",
          "repository": "https://github.com/alexindigo/asynckit"
        },
        {
          "name": "axios@1.13.5",
          "repository": "https://github.com/axios/axios"
        },
        {
          "name": "balanced-match@1.0.2",
          "repository": "https://github.com/juliangruber/balanced-match"
        },
        {
          "name": "balanced-match@4.0.4",
          "repository": "https://github.com/juliangruber/balanced-match"
        },
        {
          "name": "base64-js@1.5.1",
          "repository": "https://github.com/beatgammit/base64-js"
        },
        {
          "name": "bignumber.js@9.3.1",
          "repository": "https://github.com/MikeMcl/bignumber.js"
        },
        {
          "name": "body-parser@2.2.2",
          "repository": "https://github.com/expressjs/body-parser"
        },
        {
          "name": "brace-expansion@2.0.2",
          "repository": "https://github.com/juliangruber/brace-expansion"
        },
        {
          "name": "brace-expansion@5.0.4",
          "repository": "https://github.com/juliangruber/brace-expansion"
        },
        {
          "name": "braces@3.0.3",
          "repository": "https://github.com/micromatch/braces"
        },
        {
          "name": "browserslist@4.28.1",
          "repository": "https://github.com/browserslist/browserslist"
        },
        {
          "name": "bundle-name@4.1.0",
          "repository": "https://github.com/sindresorhus/bundle-name"
        },
        {
          "name": "bytes@3.1.2",
          "repository": "https://github.com/visionmedia/bytes.js"
        },
        {
          "name": "call-bind-apply-helpers@1.0.2",
          "repository": "https://github.com/ljharb/call-bind-apply-helpers"
        },
        {
          "name": "call-bound@1.0.4",
          "repository": "https://github.com/ljharb/call-bound"
        },
        {
          "name": "callsites@3.1.0",
          "repository": "https://github.com/sindresorhus/callsites"
        },
        {
          "name": "chalk@5.6.2",
          "repository": "https://github.com/chalk/chalk"
        },
        {
          "name": "cli-cursor@5.0.0",
          "repository": "https://github.com/sindresorhus/cli-cursor"
        },
        {
          "name": "cli-spinners@2.9.2",
          "repository": "https://github.com/sindresorhus/cli-spinners"
        },
        {
          "name": "client-only@0.0.1",
          "repository": ""
        },
        {
          "name": "clsx@2.1.1",
          "repository": "https://github.com/lukeed/clsx"
        },
        {
          "name": "cmdk@1.1.1",
          "repository": "https://github.com/pacocoursey/cmdk"
        },
        {
          "name": "code-block-writer@13.0.3",
          "repository": "https://github.com/dsherret/code-block-writer"
        },
        {
          "name": "color-convert@2.0.1",
          "repository": "https://github.com/Qix-/color-convert"
        },
        {
          "name": "color-name@1.1.4",
          "repository": "https://github.com/colorjs/color-name"
        },
        {
          "name": "combined-stream@1.0.8",
          "repository": "https://github.com/felixge/node-combined-stream"
        },
        {
          "name": "commander@11.1.0",
          "repository": "https://github.com/tj/commander.js"
        },
        {
          "name": "commander@14.0.3",
          "repository": "https://github.com/tj/commander.js"
        },
        {
          "name": "content-disposition@1.0.1",
          "repository": "https://github.com/jshttp/content-disposition"
        },
        {
          "name": "content-type@1.0.5",
          "repository": "https://github.com/jshttp/content-type"
        },
        {
          "name": "convert-source-map@2.0.0",
          "repository": "https://github.com/thlorenz/convert-source-map"
        },
        {
          "name": "cookie-signature@1.2.2",
          "repository": "https://github.com/visionmedia/node-cookie-signature"
        },
        {
          "name": "cookie@0.7.2",
          "repository": "https://github.com/jshttp/cookie"
        },
        {
          "name": "cookie@1.1.1",
          "repository": "https://github.com/jshttp/cookie"
        },
        {
          "name": "cors@2.8.6",
          "repository": "https://github.com/expressjs/cors"
        },
        {
          "name": "cosmiconfig@9.0.1",
          "repository": "https://github.com/cosmiconfig/cosmiconfig"
        },
        {
          "name": "cross-spawn@7.0.6",
          "repository": "https://github.com/moxystudio/node-cross-spawn"
        },
        {
          "name": "cssesc@3.0.0",
          "repository": "https://github.com/mathiasbynens/cssesc"
        },
        {
          "name": "csstype@3.2.3",
          "repository": "https://github.com/frenic/csstype"
        },
        {
          "name": "data-uri-to-buffer@4.0.1",
          "repository": "https://github.com/TooTallNate/node-data-uri-to-buffer"
        },
        {
          "name": "date-fns-jalali@4.1.0-0",
          "repository": "https://github.com/date-fns-jalali/date-fns-jalali"
        },
        {
          "name": "date-fns@4.1.0",
          "repository": "https://github.com/date-fns/date-fns"
        },
        {
          "name": "debug@4.4.3",
          "repository": "https://github.com/debug-js/debug"
        },
        {
          "name": "decimal.js-light@2.5.1",
          "repository": "https://github.com/MikeMcl/decimal.js-light"
        },
        {
          "name": "dedent@1.7.2",
          "repository": "https://github.com/dmnd/dedent"
        },
        {
          "name": "deepmerge@4.3.1",
          "repository": "https://github.com/TehShrike/deepmerge"
        },
        {
          "name": "default-browser-id@5.0.1",
          "repository": "https://github.com/sindresorhus/default-browser-id"
        },
        {
          "name": "default-browser@5.5.0",
          "repository": "https://github.com/sindresorhus/default-browser"
        },
        {
          "name": "define-lazy-prop@3.0.0",
          "repository": "https://github.com/sindresorhus/define-lazy-prop"
        },
        {
          "name": "delayed-stream@1.0.0",
          "repository": "https://github.com/felixge/node-delayed-stream"
        },
        {
          "name": "depd@2.0.0",
          "repository": "https://github.com/dougwilson/nodejs-depd"
        },
        {
          "name": "detect-node-es@1.1.0",
          "repository": "https://github.com/thekashey/detect-node"
        },
        {
          "name": "dom-helpers@5.2.1",
          "repository": "https://github.com/react-bootstrap/dom-helpers"
        },
        {
          "name": "dunder-proto@1.0.1",
          "repository": "https://github.com/es-shims/dunder-proto"
        },
        {
          "name": "duplexify@4.1.3",
          "repository": "https://github.com/mafintosh/duplexify"
        },
        {
          "name": "eastasianwidth@0.2.0",
          "repository": "https://github.com/komagata/eastasianwidth"
        },
        {
          "name": "eciesjs@0.4.18",
          "repository": "https://github.com/ecies/js"
        },
        {
          "name": "ee-first@1.1.1",
          "repository": "https://github.com/jonathanong/ee-first"
        },
        {
          "name": "embla-carousel-react@8.6.0",
          "repository": "https://github.com/davidjerleke/embla-carousel"
        },
        {
          "name": "embla-carousel-reactive-utils@8.6.0",
          "repository": "https://github.com/davidjerleke/embla-carousel"
        },
        {
          "name": "embla-carousel@8.6.0",
          "repository": "https://github.com/davidjerleke/embla-carousel"
        },
        {
          "name": "emoji-regex@10.6.0",
          "repository": "https://github.com/mathiasbynens/emoji-regex"
        },
        {
          "name": "emoji-regex@8.0.0",
          "repository": "https://github.com/mathiasbynens/emoji-regex"
        },
        {
          "name": "emoji-regex@9.2.2",
          "repository": "https://github.com/mathiasbynens/emoji-regex"
        },
        {
          "name": "encodeurl@2.0.0",
          "repository": "https://github.com/pillarjs/encodeurl"
        },
        {
          "name": "end-of-stream@1.4.5",
          "repository": "https://github.com/mafintosh/end-of-stream"
        },
        {
          "name": "env-paths@2.2.1",
          "repository": "https://github.com/sindresorhus/env-paths"
        },
        {
          "name": "error-ex@1.3.4",
          "repository": "https://github.com/qix-/node-error-ex"
        },
        {
          "name": "es-define-property@1.0.1",
          "repository": "https://github.com/ljharb/es-define-property"
        },
        {
          "name": "es-errors@1.3.0",
          "repository": "https://github.com/ljharb/es-errors"
        },
        {
          "name": "es-object-atoms@1.1.1",
          "repository": "https://github.com/ljharb/es-object-atoms"
        },
        {
          "name": "es-set-tostringtag@2.1.0",
          "repository": "https://github.com/es-shims/es-set-tostringtag"
        },
        {
          "name": "escalade@3.2.0",
          "repository": "https://github.com/lukeed/escalade"
        },
        {
          "name": "escape-html@1.0.3",
          "repository": "https://github.com/component/escape-html"
        },
        {
          "name": "etag@1.8.1",
          "repository": "https://github.com/jshttp/etag"
        },
        {
          "name": "event-target-shim@5.0.1",
          "repository": "https://github.com/mysticatea/event-target-shim"
        },
        {
          "name": "eventemitter3@4.0.7",
          "repository": "https://github.com/primus/eventemitter3"
        },
        {
          "name": "eventsource-parser@3.0.6",
          "repository": "https://github.com/rexxars/eventsource-parser"
        },
        {
          "name": "eventsource@3.0.7",
          "repository": "git://git@github.com/EventSource/eventsource"
        },
        {
          "name": "execa@5.1.1",
          "repository": "https://github.com/sindresorhus/execa"
        },
        {
          "name": "execa@9.6.1",
          "repository": "https://github.com/sindresorhus/execa"
        },
        {
          "name": "express-rate-limit@8.3.1",
          "repository": "https://github.com/express-rate-limit/express-rate-limit"
        },
        {
          "name": "express@5.2.1",
          "repository": "https://github.com/expressjs/express"
        },
        {
          "name": "extend@3.0.2",
          "repository": "https://github.com/justmoon/node-extend"
        },
        {
          "name": "farmhash-modern@1.1.0",
          "repository": "https://github.com/ForbesLindesay/npm-package-template"
        },
        {
          "name": "fast-deep-equal@3.1.3",
          "repository": "https://github.com/epoberezkin/fast-deep-equal"
        },
        {
          "name": "fast-equals@5.4.0",
          "repository": "https://github.com/planttheidea/fast-equals"
        },
        {
          "name": "fast-glob@3.3.3",
          "repository": "https://github.com/mrmlnc/fast-glob"
        },
        {
          "name": "fast-xml-builder@1.0.0",
          "repository": "https://github.com/NaturalIntelligence/fast-xml-builder"
        },
        {
          "name": "fast-xml-parser@5.4.1",
          "repository": "https://github.com/NaturalIntelligence/fast-xml-parser"
        },
        {
          "name": "fdir@6.5.0",
          "repository": "https://github.com/thecodrr/fdir"
        },
        {
          "name": "fetch-blob@3.2.0",
          "repository": "https://github.com/node-fetch/fetch-blob"
        },
        {
          "name": "figures@6.1.0",
          "repository": "https://github.com/sindresorhus/figures"
        },
        {
          "name": "fill-range@7.1.1",
          "repository": "https://github.com/jonschlinkert/fill-range"
        },
        {
          "name": "finalhandler@2.1.1",
          "repository": "https://github.com/pillarjs/finalhandler"
        },
        {
          "name": "follow-redirects@1.15.11",
          "repository": "https://github.com/follow-redirects/follow-redirects"
        },
        {
          "name": "form-data@2.5.5",
          "repository": "https://github.com/form-data/form-data"
        },
        {
          "name": "form-data@4.0.5",
          "repository": "https://github.com/form-data/form-data"
        },
        {
          "name": "formdata-polyfill@4.0.10",
          "repository": "git+https://jimmywarting@github.com/jimmywarting/FormData"
        },
        {
          "name": "forwarded@0.2.0",
          "repository": "https://github.com/jshttp/forwarded"
        },
        {
          "name": "framer-motion@12.36.0",
          "repository": "https://github.com/motiondivision/motion"
        },
        {
          "name": "fresh@2.0.0",
          "repository": "https://github.com/jshttp/fresh"
        },
        {
          "name": "fs-extra@11.3.4",
          "repository": "https://github.com/jprichardson/node-fs-extra"
        },
        {
          "name": "function-bind@1.1.2",
          "repository": "https://github.com/Raynos/function-bind"
        },
        {
          "name": "functional-red-black-tree@1.0.1",
          "repository": "https://github.com/mikolalysenko/functional-red-black-tree"
        },
        {
          "name": "fuzzysort@3.1.0",
          "repository": "https://github.com/farzher/fuzzysort"
        },
        {
          "name": "gensync@1.0.0-beta.2",
          "repository": "https://github.com/loganfsmyth/gensync"
        },
        {
          "name": "get-east-asian-width@1.5.0",
          "repository": "https://github.com/sindresorhus/get-east-asian-width"
        },
        {
          "name": "get-intrinsic@1.3.0",
          "repository": "https://github.com/ljharb/get-intrinsic"
        },
        {
          "name": "get-nonce@1.0.1",
          "repository": "https://github.com/theKashey/get-nonce"
        },
        {
          "name": "get-own-enumerable-keys@1.0.0",
          "repository": "https://github.com/sindresorhus/get-own-enumerable-keys"
        },
        {
          "name": "get-proto@1.0.1",
          "repository": "https://github.com/ljharb/get-proto"
        },
        {
          "name": "get-stream@6.0.1",
          "repository": "https://github.com/sindresorhus/get-stream"
        },
        {
          "name": "get-stream@9.0.1",
          "repository": "https://github.com/sindresorhus/get-stream"
        },
        {
          "name": "gopd@1.2.0",
          "repository": "https://github.com/ljharb/gopd"
        },
        {
          "name": "graphql@16.13.1",
          "repository": "https://github.com/graphql/graphql-js"
        },
        {
          "name": "gtoken@7.1.0",
          "repository": "https://github.com/google/node-gtoken"
        },
        {
          "name": "has-symbols@1.1.0",
          "repository": "https://github.com/inspect-js/has-symbols"
        },
        {
          "name": "has-tostringtag@1.0.2",
          "repository": "https://github.com/inspect-js/has-tostringtag"
        },
        {
          "name": "hasown@2.0.2",
          "repository": "https://github.com/inspect-js/hasOwn"
        },
        {
          "name": "headers-polyfill@4.0.3",
          "repository": "https://github.com/mswjs/headers-polyfill"
        },
        {
          "name": "hono@4.12.7",
          "repository": "https://github.com/honojs/hono"
        },
        {
          "name": "html-entities@2.6.0",
          "repository": "https://github.com/mdevils/html-entities"
        },
        {
          "name": "http-errors@2.0.1",
          "repository": "https://github.com/jshttp/http-errors"
        },
        {
          "name": "http-parser-js@0.5.10",
          "repository": "https://github.com/creationix/http-parser-js"
        },
        {
          "name": "http-proxy-agent@5.0.0",
          "repository": "https://github.com/TooTallNate/node-http-proxy-agent"
        },
        {
          "name": "https-proxy-agent@5.0.1",
          "repository": "https://github.com/TooTallNate/node-https-proxy-agent"
        },
        {
          "name": "https-proxy-agent@7.0.6",
          "repository": "https://github.com/TooTallNate/proxy-agents"
        },
        {
          "name": "iconv-lite@0.7.2",
          "repository": "https://github.com/pillarjs/iconv-lite"
        },
        {
          "name": "ignore@5.3.2",
          "repository": "https://github.com/kaelzhang/node-ignore"
        },
        {
          "name": "import-fresh@3.3.1",
          "repository": "https://github.com/sindresorhus/import-fresh"
        },
        {
          "name": "input-otp@1.4.2",
          "repository": "https://github.com/guilhermerodz/input-otp"
        },
        {
          "name": "ip-address@10.1.0",
          "repository": "https://github.com/beaugunderson/ip-address"
        },
        {
          "name": "ipaddr.js@1.9.1",
          "repository": "https://github.com/whitequark/ipaddr.js"
        },
        {
          "name": "is-arrayish@0.2.1",
          "repository": "https://github.com/qix-/node-is-arrayish"
        },
        {
          "name": "is-docker@3.0.0",
          "repository": "https://github.com/sindresorhus/is-docker"
        },
        {
          "name": "is-extglob@2.1.1",
          "repository": "https://github.com/jonschlinkert/is-extglob"
        },
        {
          "name": "is-fullwidth-code-point@3.0.0",
          "repository": "https://github.com/sindresorhus/is-fullwidth-code-point"
        },
        {
          "name": "is-glob@4.0.3",
          "repository": "https://github.com/micromatch/is-glob"
        },
        {
          "name": "is-in-ssh@1.0.0",
          "repository": "https://github.com/sindresorhus/is-in-ssh"
        },
        {
          "name": "is-inside-container@1.0.0",
          "repository": "https://github.com/sindresorhus/is-inside-container"
        },
        {
          "name": "is-interactive@2.0.0",
          "repository": "https://github.com/sindresorhus/is-interactive"
        },
        {
          "name": "is-node-process@1.2.0",
          "repository": "https://github.com/mswjs/is-node-process"
        },
        {
          "name": "is-number@7.0.0",
          "repository": "https://github.com/jonschlinkert/is-number"
        },
        {
          "name": "is-obj@3.0.0",
          "repository": "https://github.com/sindresorhus/is-obj"
        },
        {
          "name": "is-plain-obj@4.1.0",
          "repository": "https://github.com/sindresorhus/is-plain-obj"
        },
        {
          "name": "is-promise@4.0.0",
          "repository": "https://github.com/then/is-promise"
        },
        {
          "name": "is-regexp@3.1.0",
          "repository": "https://github.com/sindresorhus/is-regexp"
        },
        {
          "name": "is-stream@2.0.1",
          "repository": "https://github.com/sindresorhus/is-stream"
        },
        {
          "name": "is-stream@4.0.1",
          "repository": "https://github.com/sindresorhus/is-stream"
        },
        {
          "name": "is-unicode-supported@1.3.0",
          "repository": "https://github.com/sindresorhus/is-unicode-supported"
        },
        {
          "name": "is-unicode-supported@2.1.0",
          "repository": "https://github.com/sindresorhus/is-unicode-supported"
        },
        {
          "name": "is-wsl@3.1.1",
          "repository": "https://github.com/sindresorhus/is-wsl"
        },
        {
          "name": "jose@4.15.9",
          "repository": "https://github.com/panva/jose"
        },
        {
          "name": "jose@6.2.1",
          "repository": "https://github.com/panva/jose"
        },
        {
          "name": "js-cookie@3.0.5",
          "repository": "https://github.com/js-cookie/js-cookie"
        },
        {
          "name": "js-tokens@4.0.0",
          "repository": "https://github.com/lydell/js-tokens"
        },
        {
          "name": "js-yaml@4.1.1",
          "repository": "https://github.com/nodeca/js-yaml"
        },
        {
          "name": "jsesc@3.1.0",
          "repository": "https://github.com/mathiasbynens/jsesc"
        },
        {
          "name": "json-bigint@1.0.0",
          "repository": "https://github.com/sidorares/json-bigint"
        },
        {
          "name": "json-parse-even-better-errors@2.3.1",
          "repository": "https://github.com/npm/json-parse-even-better-errors"
        },
        {
          "name": "json-schema-traverse@1.0.0",
          "repository": "https://github.com/epoberezkin/json-schema-traverse"
        },
        {
          "name": "json5@2.2.3",
          "repository": "https://github.com/json5/json5"
        },
        {
          "name": "jsonfile@6.2.0",
          "repository": "https://github.com/jprichardson/node-jsonfile"
        },
        {
          "name": "jsonwebtoken@9.0.3",
          "repository": "https://github.com/auth0/node-jsonwebtoken"
        },
        {
          "name": "jwa@2.0.1",
          "repository": "https://github.com/brianloveswords/node-jwa"
        },
        {
          "name": "jwks-rsa@3.2.2",
          "repository": "https://github.com/auth0/node-jwks-rsa"
        },
        {
          "name": "jws@4.0.1",
          "repository": "https://github.com/brianloveswords/node-jws"
        },
        {
          "name": "kleur@3.0.3",
          "repository": "https://github.com/lukeed/kleur"
        },
        {
          "name": "kleur@4.1.5",
          "repository": "https://github.com/lukeed/kleur"
        },
        {
          "name": "limiter@1.1.5",
          "repository": "https://github.com/jhurliman/node-rate-limiter"
        },
        {
          "name": "lines-and-columns@1.2.4",
          "repository": "https://github.com/eventualbuddha/lines-and-columns"
        },
        {
          "name": "lodash.camelcase@4.3.0",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.clonedeep@4.5.0",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.includes@4.3.0",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.isboolean@3.0.3",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.isinteger@4.0.4",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.isnumber@3.0.3",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.isplainobject@4.0.6",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.isstring@4.0.1",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash.once@4.1.1",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "lodash@4.17.23",
          "repository": "https://github.com/lodash/lodash"
        },
        {
          "name": "log-symbols@6.0.0",
          "repository": "https://github.com/sindresorhus/log-symbols"
        },
        {
          "name": "loose-envify@1.4.0",
          "repository": "https://github.com/zertosh/loose-envify"
        },
        {
          "name": "lru-memoizer@2.3.0",
          "repository": "https://github.com/jfromaniello/lru-memoizer"
        },
        {
          "name": "math-intrinsics@1.1.0",
          "repository": "https://github.com/es-shims/math-intrinsics"
        },
        {
          "name": "media-typer@1.1.0",
          "repository": "https://github.com/jshttp/media-typer"
        },
        {
          "name": "merge-descriptors@2.0.0",
          "repository": "https://github.com/sindresorhus/merge-descriptors"
        },
        {
          "name": "merge-stream@2.0.0",
          "repository": "https://github.com/grncdr/merge-stream"
        },
        {
          "name": "merge2@1.4.1",
          "repository": "https://github.com/teambition/merge2"
        },
        {
          "name": "micromatch@4.0.8",
          "repository": "https://github.com/micromatch/micromatch"
        },
        {
          "name": "mime-db@1.52.0",
          "repository": "https://github.com/jshttp/mime-db"
        },
        {
          "name": "mime-db@1.54.0",
          "repository": "https://github.com/jshttp/mime-db"
        },
        {
          "name": "mime-types@2.1.35",
          "repository": "https://github.com/jshttp/mime-types"
        },
        {
          "name": "mime-types@3.0.2",
          "repository": "https://github.com/jshttp/mime-types"
        },
        {
          "name": "mime@3.0.0",
          "repository": "https://github.com/broofa/mime"
        },
        {
          "name": "mimic-fn@2.1.0",
          "repository": "https://github.com/sindresorhus/mimic-fn"
        },
        {
          "name": "mimic-function@5.0.1",
          "repository": "https://github.com/sindresorhus/mimic-function"
        },
        {
          "name": "minimist@1.2.8",
          "repository": "https://github.com/minimistjs/minimist"
        },
        {
          "name": "motion-dom@12.36.0",
          "repository": "https://github.com/motiondivision/motion"
        },
        {
          "name": "motion-utils@12.36.0",
          "repository": "https://github.com/motiondivision/motion"
        },
        {
          "name": "ms@2.1.3",
          "repository": "https://github.com/vercel/ms"
        },
        {
          "name": "msw@2.12.10",
          "repository": "https://github.com/mswjs/msw"
        },
        {
          "name": "nanoid@3.3.11",
          "repository": "https://github.com/ai/nanoid"
        },
        {
          "name": "negotiator@1.0.0",
          "repository": "https://github.com/jshttp/negotiator"
        },
        {
          "name": "next-themes@0.4.6",
          "repository": "https://github.com/pacocoursey/next-themes"
        },
        {
          "name": "next@16.1.6",
          "repository": "https://github.com/vercel/next.js"
        },
        {
          "name": "node-domexception@1.0.0",
          "repository": "https://github.com/jimmywarting/node-domexception"
        },
        {
          "name": "node-fetch@2.7.0",
          "repository": "https://github.com/bitinn/node-fetch"
        },
        {
          "name": "node-fetch@3.3.2",
          "repository": "https://github.com/node-fetch/node-fetch"
        },
        {
          "name": "node-releases@2.0.27",
          "repository": "https://github.com/chicoxyzzy/node-releases"
        },
        {
          "name": "npm-run-path@4.0.1",
          "repository": "https://github.com/sindresorhus/npm-run-path"
        },
        {
          "name": "npm-run-path@6.0.0",
          "repository": "https://github.com/sindresorhus/npm-run-path"
        },
        {
          "name": "object-assign@4.1.1",
          "repository": "https://github.com/sindresorhus/object-assign"
        },
        {
          "name": "object-hash@3.0.0",
          "repository": "https://github.com/puleos/object-hash"
        },
        {
          "name": "object-inspect@1.13.4",
          "repository": "https://github.com/inspect-js/object-inspect"
        },
        {
          "name": "object-treeify@1.1.33",
          "repository": "https://github.com/blackflux/object-treeify"
        },
        {
          "name": "on-finished@2.4.1",
          "repository": "https://github.com/jshttp/on-finished"
        },
        {
          "name": "onetime@5.1.2",
          "repository": "https://github.com/sindresorhus/onetime"
        },
        {
          "name": "onetime@7.0.0",
          "repository": "https://github.com/sindresorhus/onetime"
        },
        {
          "name": "open@11.0.0",
          "repository": "https://github.com/sindresorhus/open"
        },
        {
          "name": "ora@8.2.0",
          "repository": "https://github.com/sindresorhus/ora"
        },
        {
          "name": "outvariant@1.4.3",
          "repository": "https://github.com/open-draft/outvariant"
        },
        {
          "name": "p-limit@3.1.0",
          "repository": "https://github.com/sindresorhus/p-limit"
        },
        {
          "name": "package-manager-detector@1.6.0",
          "repository": "https://github.com/antfu-collective/package-manager-detector"
        },
        {
          "name": "parent-module@1.0.1",
          "repository": "https://github.com/sindresorhus/parent-module"
        },
        {
          "name": "parse-json@5.2.0",
          "repository": "https://github.com/sindresorhus/parse-json"
        },
        {
          "name": "parse-ms@4.0.0",
          "repository": "https://github.com/sindresorhus/parse-ms"
        },
        {
          "name": "parseurl@1.3.3",
          "repository": "https://github.com/pillarjs/parseurl"
        },
        {
          "name": "path-browserify@1.0.1",
          "repository": "https://github.com/browserify/path-browserify"
        },
        {
          "name": "path-key@3.1.1",
          "repository": "https://github.com/sindresorhus/path-key"
        },
        {
          "name": "path-key@4.0.0",
          "repository": "https://github.com/sindresorhus/path-key"
        },
        {
          "name": "path-to-regexp@6.3.0",
          "repository": "https://github.com/pillarjs/path-to-regexp"
        },
        {
          "name": "path-to-regexp@8.3.0",
          "repository": "https://github.com/pillarjs/path-to-regexp"
        },
        {
          "name": "picomatch@2.3.1",
          "repository": "https://github.com/micromatch/picomatch"
        },
        {
          "name": "picomatch@4.0.3",
          "repository": "https://github.com/micromatch/picomatch"
        },
        {
          "name": "pkce-challenge@5.0.1",
          "repository": "https://github.com/crouchcd/pkce-challenge"
        },
        {
          "name": "postcss-selector-parser@7.1.1",
          "repository": "https://github.com/postcss/postcss-selector-parser"
        },
        {
          "name": "postcss@8.4.31",
          "repository": "https://github.com/postcss/postcss"
        },
        {
          "name": "postcss@8.5.6",
          "repository": "https://github.com/postcss/postcss"
        },
        {
          "name": "powershell-utils@0.1.0",
          "repository": "https://github.com/sindresorhus/powershell-utils"
        },
        {
          "name": "prettier@3.8.1",
          "repository": "https://github.com/prettier/prettier"
        },
        {
          "name": "pretty-ms@9.3.0",
          "repository": "https://github.com/sindresorhus/pretty-ms"
        },
        {
          "name": "prompts@2.4.2",
          "repository": "https://github.com/terkelg/prompts"
        },
        {
          "name": "prop-types@15.8.1",
          "repository": "https://github.com/facebook/prop-types"
        },
        {
          "name": "proxy-addr@2.0.7",
          "repository": "https://github.com/jshttp/proxy-addr"
        },
        {
          "name": "proxy-from-env@1.1.0",
          "repository": "https://github.com/Rob--W/proxy-from-env"
        },
        {
          "name": "queue-microtask@1.2.3",
          "repository": "https://github.com/feross/queue-microtask"
        },
        {
          "name": "radix-ui@1.4.3",
          "repository": "https://github.com/radix-ui/primitives"
        },
        {
          "name": "range-parser@1.2.1",
          "repository": "https://github.com/jshttp/range-parser"
        },
        {
          "name": "raw-body@3.0.2",
          "repository": "https://github.com/stream-utils/raw-body"
        },
        {
          "name": "react-day-picker@9.14.0",
          "repository": "https://github.com/gpbl/react-day-picker"
        },
        {
          "name": "react-dom@19.2.3",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "react-is@16.13.1",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "react-is@18.3.1",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "react-remove-scroll-bar@2.3.8",
          "repository": "https://github.com/theKashey/react-remove-scroll-bar"
        },
        {
          "name": "react-remove-scroll@2.7.2",
          "repository": "https://github.com/theKashey/react-remove-scroll"
        },
        {
          "name": "react-resizable-panels@4.7.2",
          "repository": "https://github.com/bvaughn/react-resizable-panels"
        },
        {
          "name": "react-smooth@4.0.4",
          "repository": "https://github.com/recharts/react-smooth"
        },
        {
          "name": "react-style-singleton@2.2.3",
          "repository": "https://github.com/theKashey/react-style-singleton"
        },
        {
          "name": "react@19.2.3",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "readable-stream@3.6.2",
          "repository": "https://github.com/nodejs/readable-stream"
        },
        {
          "name": "recast@0.23.11",
          "repository": "https://github.com/benjamn/recast"
        },
        {
          "name": "recharts-scale@0.4.5",
          "repository": "https://github.com/recharts/recharts-scale"
        },
        {
          "name": "recharts@2.15.4",
          "repository": "https://github.com/recharts/recharts"
        },
        {
          "name": "require-directory@2.1.1",
          "repository": "https://github.com/troygoode/node-require-directory"
        },
        {
          "name": "require-from-string@2.0.2",
          "repository": "https://github.com/floatdrop/require-from-string"
        },
        {
          "name": "reselect@5.1.1",
          "repository": "https://github.com/reduxjs/reselect"
        },
        {
          "name": "resolve-from@4.0.0",
          "repository": "https://github.com/sindresorhus/resolve-from"
        },
        {
          "name": "restore-cursor@5.1.0",
          "repository": "https://github.com/sindresorhus/restore-cursor"
        },
        {
          "name": "retry-request@7.0.2",
          "repository": "https://github.com/stephenplusplus/retry-request"
        },
        {
          "name": "retry@0.13.1",
          "repository": "https://github.com/tim-kos/node-retry"
        },
        {
          "name": "rettime@0.10.1",
          "repository": "https://github.com/kettanaito/rettime"
        },
        {
          "name": "reusify@1.1.0",
          "repository": "https://github.com/mcollina/reusify"
        },
        {
          "name": "router@2.2.0",
          "repository": "https://github.com/pillarjs/router"
        },
        {
          "name": "run-applescript@7.1.0",
          "repository": "https://github.com/sindresorhus/run-applescript"
        },
        {
          "name": "run-parallel@1.2.0",
          "repository": "https://github.com/feross/run-parallel"
        },
        {
          "name": "safe-buffer@5.2.1",
          "repository": "https://github.com/feross/safe-buffer"
        },
        {
          "name": "safer-buffer@2.1.2",
          "repository": "https://github.com/ChALkeR/safer-buffer"
        },
        {
          "name": "scheduler@0.27.0",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "send@1.2.1",
          "repository": "https://github.com/pillarjs/send"
        },
        {
          "name": "serve-static@2.2.1",
          "repository": "https://github.com/expressjs/serve-static"
        },
        {
          "name": "shadcn@4.0.6",
          "repository": "https://github.com/shadcn-ui/ui"
        },
        {
          "name": "shebang-command@2.0.0",
          "repository": "https://github.com/kevva/shebang-command"
        },
        {
          "name": "shebang-regex@3.0.0",
          "repository": "https://github.com/sindresorhus/shebang-regex"
        },
        {
          "name": "side-channel-list@1.0.0",
          "repository": "https://github.com/ljharb/side-channel-list"
        },
        {
          "name": "side-channel-map@1.0.1",
          "repository": "https://github.com/ljharb/side-channel-map"
        },
        {
          "name": "side-channel-weakmap@1.0.2",
          "repository": "https://github.com/ljharb/side-channel-weakmap"
        },
        {
          "name": "side-channel@1.1.0",
          "repository": "https://github.com/ljharb/side-channel"
        },
        {
          "name": "sisteransi@1.0.5",
          "repository": "https://github.com/terkelg/sisteransi"
        },
        {
          "name": "sonner@2.0.7",
          "repository": "https://github.com/emilkowalski/sonner"
        },
        {
          "name": "statuses@2.0.2",
          "repository": "https://github.com/jshttp/statuses"
        },
        {
          "name": "stdin-discarder@0.2.2",
          "repository": "https://github.com/sindresorhus/stdin-discarder"
        },
        {
          "name": "stream-events@1.0.5",
          "repository": "https://github.com/stephenplusplus/stream-events"
        },
        {
          "name": "stream-shift@1.0.3",
          "repository": "https://github.com/mafintosh/stream-shift"
        },
        {
          "name": "strict-event-emitter@0.5.1",
          "repository": "https://github.com/open-draft/strict-event-emitter"
        },
        {
          "name": "string_decoder@1.3.0",
          "repository": "https://github.com/nodejs/string_decoder"
        },
        {
          "name": "string-width@4.2.3",
          "repository": "https://github.com/sindresorhus/string-width"
        },
        {
          "name": "string-width@5.1.2",
          "repository": "https://github.com/sindresorhus/string-width"
        },
        {
          "name": "string-width@7.2.0",
          "repository": "https://github.com/sindresorhus/string-width"
        },
        {
          "name": "strip-ansi@6.0.1",
          "repository": "https://github.com/chalk/strip-ansi"
        },
        {
          "name": "strip-ansi@7.2.0",
          "repository": "https://github.com/chalk/strip-ansi"
        },
        {
          "name": "strip-bom@3.0.0",
          "repository": "https://github.com/sindresorhus/strip-bom"
        },
        {
          "name": "strip-final-newline@2.0.0",
          "repository": "https://github.com/sindresorhus/strip-final-newline"
        },
        {
          "name": "strip-final-newline@4.0.0",
          "repository": "https://github.com/sindresorhus/strip-final-newline"
        },
        {
          "name": "strnum@2.1.2",
          "repository": "https://github.com/NaturalIntelligence/strnum"
        },
        {
          "name": "stubs@3.0.0",
          "repository": "https://github.com/stephenplusplus/stubs"
        },
        {
          "name": "styled-jsx@5.1.6",
          "repository": "https://github.com/vercel/styled-jsx"
        },
        {
          "name": "tabbable@6.4.0",
          "repository": "https://github.com/focus-trap/tabbable"
        },
        {
          "name": "tagged-tag@1.0.0",
          "repository": "https://github.com/sindresorhus/tagged-tag"
        },
        {
          "name": "tailwind-merge@3.5.0",
          "repository": "https://github.com/dcastil/tailwind-merge"
        },
        {
          "name": "tiny-invariant@1.3.3",
          "repository": "https://github.com/alexreardon/tiny-invariant"
        },
        {
          "name": "tinyexec@1.0.4",
          "repository": "https://github.com/tinylibs/tinyexec"
        },
        {
          "name": "tldts-core@7.0.25",
          "repository": "https://github.com/remusao/tldts"
        },
        {
          "name": "tldts@7.0.25",
          "repository": "https://github.com/remusao/tldts"
        },
        {
          "name": "to-regex-range@5.0.1",
          "repository": "https://github.com/micromatch/to-regex-range"
        },
        {
          "name": "toidentifier@1.0.1",
          "repository": "https://github.com/component/toidentifier"
        },
        {
          "name": "tr46@0.0.3",
          "repository": "https://github.com/Sebmaster/tr46.js"
        },
        {
          "name": "ts-morph@26.0.0",
          "repository": "https://github.com/dsherret/ts-morph"
        },
        {
          "name": "tsconfig-paths@4.2.0",
          "repository": "https://github.com/dividab/tsconfig-paths"
        },
        {
          "name": "tw-animate-css@1.4.0",
          "repository": "https://github.com/Wombosvideo/tw-animate-css"
        },
        {
          "name": "type-is@2.0.1",
          "repository": "https://github.com/jshttp/type-is"
        },
        {
          "name": "typescript-event-target@1.1.2",
          "repository": "https://github.com/DerZade/typescript-event-target"
        },
        {
          "name": "undici-types@6.21.0",
          "repository": "https://github.com/nodejs/undici"
        },
        {
          "name": "unicorn-magic@0.3.0",
          "repository": "https://github.com/sindresorhus/unicorn-magic"
        },
        {
          "name": "universalify@2.0.1",
          "repository": "https://github.com/RyanZim/universalify"
        },
        {
          "name": "unpipe@1.0.0",
          "repository": "https://github.com/stream-utils/unpipe"
        },
        {
          "name": "until-async@3.0.2",
          "repository": "https://github.com/kettanaito/until-async"
        },
        {
          "name": "update-browserslist-db@1.2.3",
          "repository": "https://github.com/browserslist/update-db"
        },
        {
          "name": "use-callback-ref@1.3.3",
          "repository": "https://github.com/theKashey/use-callback-ref"
        },
        {
          "name": "use-sidecar@1.1.3",
          "repository": "https://github.com/theKashey/use-sidecar"
        },
        {
          "name": "use-sync-external-store@1.6.0",
          "repository": "https://github.com/facebook/react"
        },
        {
          "name": "util-deprecate@1.0.2",
          "repository": "https://github.com/TooTallNate/util-deprecate"
        },
        {
          "name": "uuid@11.1.0",
          "repository": "https://github.com/uuidjs/uuid"
        },
        {
          "name": "uuid@8.3.2",
          "repository": "https://github.com/uuidjs/uuid"
        },
        {
          "name": "uuid@9.0.1",
          "repository": "https://github.com/uuidjs/uuid"
        },
        {
          "name": "vary@1.1.2",
          "repository": "https://github.com/jshttp/vary"
        },
        {
          "name": "vaul@1.1.2",
          "repository": "https://github.com/emilkowalski/vaul"
        },
        {
          "name": "web-streams-polyfill@3.3.3",
          "repository": "https://github.com/MattiasBuelens/web-streams-polyfill"
        },
        {
          "name": "whatwg-url@5.0.0",
          "repository": "https://github.com/jsdom/whatwg-url"
        },
        {
          "name": "wrap-ansi@6.2.0",
          "repository": "https://github.com/chalk/wrap-ansi"
        },
        {
          "name": "wrap-ansi@7.0.0",
          "repository": "https://github.com/chalk/wrap-ansi"
        },
        {
          "name": "wrap-ansi@8.1.0",
          "repository": "https://github.com/chalk/wrap-ansi"
        },
        {
          "name": "wsl-utils@0.3.1",
          "repository": "https://github.com/sindresorhus/wsl-utils"
        },
        {
          "name": "yargs@17.7.2",
          "repository": "https://github.com/yargs/yargs"
        },
        {
          "name": "yocto-queue@0.1.0",
          "repository": "https://github.com/sindresorhus/yocto-queue"
        },
        {
          "name": "yoctocolors-cjs@2.1.3",
          "repository": "https://github.com/sindresorhus/yoctocolors"
        },
        {
          "name": "yoctocolors@2.1.2",
          "repository": "https://github.com/sindresorhus/yoctocolors"
        },
        {
          "name": "zod@3.25.76",
          "repository": "https://github.com/colinhacks/zod"
        },
        {
          "name": "zustand@5.0.12",
          "repository": "https://github.com/pmndrs/zustand"
        }
      ]
    },
    {
      "license": "Apache-2.0",
      "count": 81,
      "entries": [
        {
          "name": "@firebase/ai@2.8.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/analytics-compat@0.2.25",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/analytics-types@0.8.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/analytics@0.10.19",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-check-compat@0.4.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-check-interop-types@0.3.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-check-types@0.5.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-check@0.11.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-compat@0.5.8",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app-types@0.9.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/app@0.14.8",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/auth-compat@0.6.2",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/auth-interop-types@0.2.4",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/auth-types@0.13.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/auth@1.12.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/component@0.7.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/data-connect@0.3.12",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/database-compat@2.1.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/database-types@1.0.16",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/database@1.1.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/firestore-compat@0.4.5",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/firestore-types@3.0.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/firestore@4.11.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/functions-compat@0.4.1",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/functions-types@0.6.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/functions@0.13.1",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/installations-compat@0.2.19",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/installations-types@0.5.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/installations@0.6.19",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/logger@0.5.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/messaging-compat@0.2.23",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/messaging-interop-types@0.2.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/messaging@0.12.23",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/performance-compat@0.2.22",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/performance-types@0.2.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/performance@0.7.9",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/remote-config-compat@0.2.21",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/remote-config-types@0.5.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/remote-config@0.8.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/storage-compat@0.4.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/storage-types@0.8.3",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/storage@0.14.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/util@1.13.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@firebase/webchannel-wrapper@1.0.5",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "@google-cloud/firestore@7.11.6",
          "repository": "https://github.com/googleapis/nodejs-firestore"
        },
        {
          "name": "@google-cloud/paginator@5.0.2",
          "repository": "https://github.com/googleapis/nodejs-paginator"
        },
        {
          "name": "@google-cloud/projectify@4.0.0",
          "repository": "https://github.com/googleapis/nodejs-projectify"
        },
        {
          "name": "@google-cloud/promisify@4.0.0",
          "repository": "https://github.com/googleapis/nodejs-promisify"
        },
        {
          "name": "@google-cloud/storage@7.19.0",
          "repository": "https://github.com/googleapis/nodejs-storage"
        },
        {
          "name": "@grpc/grpc-js@1.14.3",
          "repository": "https://github.com/grpc/grpc-node/tree/master/packages/grpc-js"
        },
        {
          "name": "@grpc/grpc-js@1.9.15",
          "repository": "https://github.com/grpc/grpc-node/tree/master/packages/grpc-js"
        },
        {
          "name": "@grpc/proto-loader@0.7.15",
          "repository": "https://github.com/grpc/grpc-node"
        },
        {
          "name": "@grpc/proto-loader@0.8.0",
          "repository": "https://github.com/grpc/grpc-node"
        },
        {
          "name": "@opentelemetry/api@1.9.0",
          "repository": "https://github.com/open-telemetry/opentelemetry-js"
        },
        {
          "name": "@swc/helpers@0.5.15",
          "repository": "https://github.com/swc-project/swc"
        },
        {
          "name": "baseline-browser-mapping@2.10.0",
          "repository": "https://github.com/web-platform-dx/baseline-browser-mapping"
        },
        {
          "name": "class-variance-authority@0.7.1",
          "repository": "https://github.com/joe-bell/cva"
        },
        {
          "name": "detect-libc@2.1.2",
          "repository": "https://github.com/lovell/detect-libc"
        },
        {
          "name": "ecdsa-sig-formatter@1.0.11",
          "repository": "https://github.com/Brightspace/node-ecdsa-sig-formatter"
        },
        {
          "name": "faye-websocket@0.11.4",
          "repository": "https://github.com/faye/faye-websocket-node"
        },
        {
          "name": "firebase-admin@13.7.0",
          "repository": "https://github.com/firebase/firebase-admin-node"
        },
        {
          "name": "firebase@12.9.0",
          "repository": "https://github.com/firebase/firebase-js-sdk"
        },
        {
          "name": "gaxios@6.7.1",
          "repository": "https://github.com/googleapis/gaxios"
        },
        {
          "name": "gaxios@7.1.3",
          "repository": "https://github.com/googleapis/google-cloud-node-core"
        },
        {
          "name": "gcp-metadata@6.1.1",
          "repository": "https://github.com/googleapis/gcp-metadata"
        },
        {
          "name": "gcp-metadata@8.1.2",
          "repository": "https://github.com/googleapis/google-cloud-node-core"
        },
        {
          "name": "google-auth-library@10.6.1",
          "repository": "https://github.com/googleapis/google-cloud-node-core"
        },
        {
          "name": "google-auth-library@9.15.1",
          "repository": "https://github.com/googleapis/google-auth-library-nodejs"
        },
        {
          "name": "google-gax@4.6.1",
          "repository": "https://github.com/googleapis/gax-nodejs"
        },
        {
          "name": "google-logging-utils@0.0.2",
          "repository": "https://github.com/googleapis/gax-nodejs"
        },
        {
          "name": "google-logging-utils@1.1.3",
          "repository": "https://github.com/googleapis/google-cloud-node-core"
        },
        {
          "name": "human-signals@2.1.0",
          "repository": "https://github.com/ehmicky/human-signals"
        },
        {
          "name": "human-signals@8.0.1",
          "repository": "https://github.com/ehmicky/human-signals"
        },
        {
          "name": "long@5.3.2",
          "repository": "https://github.com/dcodeIO/long.js"
        },
        {
          "name": "proto3-json-serializer@2.0.2",
          "repository": "https://github.com/googleapis/proto3-json-serializer-nodejs"
        },
        {
          "name": "sharp@0.34.5",
          "repository": "https://github.com/lovell/sharp"
        },
        {
          "name": "teeny-request@9.0.0",
          "repository": "https://github.com/googleapis/teeny-request"
        },
        {
          "name": "typescript@5.9.3",
          "repository": "https://github.com/microsoft/TypeScript"
        },
        {
          "name": "web-vitals@4.2.4",
          "repository": "https://github.com/GoogleChrome/web-vitals"
        },
        {
          "name": "websocket-driver@0.7.4",
          "repository": "https://github.com/faye/websocket-driver-node"
        },
        {
          "name": "websocket-extensions@0.1.4",
          "repository": "https://github.com/faye/websocket-extensions-node"
        }
      ]
    },
    {
      "license": "ISC",
      "count": 48,
      "entries": [
        {
          "name": "@isaacs/cliui@8.0.2",
          "repository": "https://github.com/yargs/cliui"
        },
        {
          "name": "ansis@4.2.0",
          "repository": "https://github.com/webdiscus/ansis"
        },
        {
          "name": "cli-width@4.1.0",
          "repository": "https://github.com/knownasilya/cli-width"
        },
        {
          "name": "cliui@8.0.1",
          "repository": "https://github.com/yargs/cliui"
        },
        {
          "name": "d3-array@3.2.4",
          "repository": "https://github.com/d3/d3-array"
        },
        {
          "name": "d3-color@3.1.0",
          "repository": "https://github.com/d3/d3-color"
        },
        {
          "name": "d3-format@3.1.2",
          "repository": "https://github.com/d3/d3-format"
        },
        {
          "name": "d3-interpolate@3.0.1",
          "repository": "https://github.com/d3/d3-interpolate"
        },
        {
          "name": "d3-path@3.1.0",
          "repository": "https://github.com/d3/d3-path"
        },
        {
          "name": "d3-scale@4.0.2",
          "repository": "https://github.com/d3/d3-scale"
        },
        {
          "name": "d3-shape@3.2.0",
          "repository": "https://github.com/d3/d3-shape"
        },
        {
          "name": "d3-time-format@4.1.0",
          "repository": "https://github.com/d3/d3-time-format"
        },
        {
          "name": "d3-time@3.1.0",
          "repository": "https://github.com/d3/d3-time"
        },
        {
          "name": "d3-timer@3.0.1",
          "repository": "https://github.com/d3/d3-timer"
        },
        {
          "name": "electron-to-chromium@1.5.302",
          "repository": "https://github.com/kilian/electron-to-chromium"
        },
        {
          "name": "fastq@1.20.1",
          "repository": "https://github.com/mcollina/fastq"
        },
        {
          "name": "foreground-child@3.3.1",
          "repository": "https://github.com/tapjs/foreground-child"
        },
        {
          "name": "get-caller-file@2.0.5",
          "repository": "https://github.com/stefanpenner/get-caller-file"
        },
        {
          "name": "glob-parent@5.1.2",
          "repository": "https://github.com/gulpjs/glob-parent"
        },
        {
          "name": "glob@10.5.0",
          "repository": "https://github.com/isaacs/node-glob"
        },
        {
          "name": "graceful-fs@4.2.11",
          "repository": "https://github.com/isaacs/node-graceful-fs"
        },
        {
          "name": "idb@7.1.1",
          "repository": "https://github.com/jakearchibald/idb"
        },
        {
          "name": "inherits@2.0.4",
          "repository": "https://github.com/isaacs/inherits"
        },
        {
          "name": "internmap@2.0.3",
          "repository": "https://github.com/mbostock/internmap"
        },
        {
          "name": "isexe@2.0.0",
          "repository": "https://github.com/isaacs/isexe"
        },
        {
          "name": "lru-cache@10.4.3",
          "repository": "https://github.com/isaacs/node-lru-cache"
        },
        {
          "name": "lru-cache@5.1.1",
          "repository": "https://github.com/isaacs/node-lru-cache"
        },
        {
          "name": "lru-cache@6.0.0",
          "repository": "https://github.com/isaacs/node-lru-cache"
        },
        {
          "name": "lucide-react@0.577.0",
          "repository": "https://github.com/lucide-icons/lucide"
        },
        {
          "name": "minimatch@9.0.9",
          "repository": "https://github.com/isaacs/minimatch"
        },
        {
          "name": "mute-stream@2.0.0",
          "repository": "https://github.com/npm/mute-stream"
        },
        {
          "name": "once@1.4.0",
          "repository": "https://github.com/isaacs/once"
        },
        {
          "name": "picocolors@1.1.1",
          "repository": "https://github.com/alexeyraspopov/picocolors"
        },
        {
          "name": "rimraf@5.0.10",
          "repository": "https://github.com/isaacs/rimraf"
        },
        {
          "name": "semver@6.3.1",
          "repository": "https://github.com/npm/node-semver"
        },
        {
          "name": "semver@7.7.4",
          "repository": "https://github.com/npm/node-semver"
        },
        {
          "name": "setprototypeof@1.2.0",
          "repository": "https://github.com/wesleytodd/setprototypeof"
        },
        {
          "name": "signal-exit@3.0.7",
          "repository": "https://github.com/tapjs/signal-exit"
        },
        {
          "name": "signal-exit@4.1.0",
          "repository": "https://github.com/tapjs/signal-exit"
        },
        {
          "name": "validate-npm-package-name@7.0.2",
          "repository": "https://github.com/npm/validate-npm-package-name"
        },
        {
          "name": "which@2.0.2",
          "repository": "https://github.com/isaacs/node-which"
        },
        {
          "name": "which@4.0.0",
          "repository": "https://github.com/npm/node-which"
        },
        {
          "name": "wrappy@1.0.2",
          "repository": "https://github.com/npm/wrappy"
        },
        {
          "name": "y18n@5.0.8",
          "repository": "https://github.com/yargs/y18n"
        },
        {
          "name": "yallist@3.1.1",
          "repository": "https://github.com/isaacs/yallist"
        },
        {
          "name": "yallist@4.0.0",
          "repository": "https://github.com/isaacs/yallist"
        },
        {
          "name": "yargs-parser@21.1.1",
          "repository": "https://github.com/yargs/yargs-parser"
        },
        {
          "name": "zod-to-json-schema@3.25.1",
          "repository": "https://github.com/StefanTerdell/zod-to-json-schema"
        }
      ]
    },
    {
      "license": "BSD-3-Clause",
      "count": 22,
      "entries": [
        {
          "name": "@dotenvx/dotenvx@1.55.1",
          "repository": "https://github.com/dotenvx/dotenvx"
        },
        {
          "name": "@protobufjs/aspromise@1.1.2",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/base64@1.1.2",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/codegen@2.0.4",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/eventemitter@1.1.0",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/fetch@1.1.0",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/float@1.0.2",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/inquire@1.1.0",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/path@1.1.2",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/pool@1.1.0",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "@protobufjs/utf8@1.1.0",
          "repository": "https://github.com/dcodeIO/protobuf.js"
        },
        {
          "name": "buffer-equal-constant-time@1.0.1",
          "repository": "https://github.com/goinstant/buffer-equal-constant-time"
        },
        {
          "name": "d3-ease@3.0.1",
          "repository": "https://github.com/d3/d3-ease"
        },
        {
          "name": "diff@8.0.3",
          "repository": "https://github.com/kpdecker/jsdiff"
        },
        {
          "name": "fast-uri@3.1.0",
          "repository": "https://github.com/fastify/fast-uri"
        },
        {
          "name": "fzf@0.5.2",
          "repository": "https://github.com/ajitid/fzf-for-js"
        },
        {
          "name": "protobufjs@7.5.4",
          "repository": "https://github.com/protobufjs/protobuf.js"
        },
        {
          "name": "qs@6.15.0",
          "repository": "https://github.com/ljharb/qs"
        },
        {
          "name": "react-transition-group@4.4.5",
          "repository": "https://github.com/reactjs/react-transition-group"
        },
        {
          "name": "source-map-js@1.2.1",
          "repository": "https://github.com/7rulnik/source-map-js"
        },
        {
          "name": "source-map@0.6.1",
          "repository": "https://github.com/mozilla/source-map"
        },
        {
          "name": "tough-cookie@6.0.1",
          "repository": "https://github.com/salesforce/tough-cookie"
        }
      ]
    },
    {
      "license": "BlueOak-1.0.0",
      "count": 6,
      "entries": [
        {
          "name": "isexe@3.1.5",
          "repository": "https://github.com/isaacs/isexe"
        },
        {
          "name": "jackspeak@3.4.3",
          "repository": "https://github.com/isaacs/jackspeak"
        },
        {
          "name": "minimatch@10.2.4",
          "repository": "https://github.com/isaacs/minimatch"
        },
        {
          "name": "minipass@7.1.3",
          "repository": "https://github.com/isaacs/minipass"
        },
        {
          "name": "package-json-from-dist@1.0.1",
          "repository": "https://github.com/isaacs/package-json-from-dist"
        },
        {
          "name": "path-scurry@1.11.1",
          "repository": "https://github.com/isaacs/path-scurry"
        }
      ]
    },
    {
      "license": "BSD-2-Clause",
      "count": 5,
      "entries": [
        {
          "name": "dotenv@17.3.1",
          "repository": "https://github.com/motdotla/dotenv"
        },
        {
          "name": "esprima@4.0.1",
          "repository": "https://github.com/jquery/esprima"
        },
        {
          "name": "json-schema-typed@8.0.2",
          "repository": "https://github.com/RemyRylan/json-schema-typed"
        },
        {
          "name": "stringify-object@5.0.0",
          "repository": "https://github.com/yeoman/stringify-object"
        },
        {
          "name": "webidl-conversions@3.0.1",
          "repository": "https://github.com/jsdom/webidl-conversions"
        }
      ]
    },
    {
      "license": "Apache-2.0 AND LGPL-3.0-or-later",
      "count": 1,
      "entries": [
        {
          "name": "@img/sharp-win32-x64@0.34.5",
          "repository": "https://github.com/lovell/sharp"
        }
      ]
    },
    {
      "license": "Python-2.0",
      "count": 1,
      "entries": [
        {
          "name": "argparse@2.0.1",
          "repository": "https://github.com/nodeca/argparse"
        }
      ]
    },
    {
      "license": "CC-BY-4.0",
      "count": 1,
      "entries": [
        {
          "name": "caniuse-lite@1.0.30001774",
          "repository": "https://github.com/browserslist/caniuse-lite"
        }
      ]
    },
    {
      "license": "(BSD-3-Clause OR GPL-2.0)",
      "count": 1,
      "entries": [
        {
          "name": "node-forge@1.3.3",
          "repository": "https://github.com/digitalbazaar/forge"
        }
      ]
    },
    {
      "license": "0BSD",
      "count": 1,
      "entries": [
        {
          "name": "tslib@2.8.1",
          "repository": "https://github.com/Microsoft/tslib"
        }
      ]
    },
    {
      "license": "(MIT OR CC0-1.0)",
      "count": 1,
      "entries": [
        {
          "name": "type-fest@5.4.4",
          "repository": "https://github.com/sindresorhus/type-fest"
        }
      ]
    },
    {
      "license": "MIT AND ISC",
      "count": 1,
      "entries": [
        {
          "name": "victory-vendor@36.9.2",
          "repository": "https://github.com/FormidableLabs/victory"
        }
      ]
    }
  ]
} as {
  generatedDate: string | null;
  total: number | null;
  summary: { license: string; count: number }[];
  sections: LicenseNoticeSection[];
};
