import { Bot } from 'lucide-react';
import { LegalDocument, LegalPage } from '../_components/legal-page';

export default function AIDisclosurePage() {
  return (
    <LegalPage
      title="AI Disclosure & Transparency Notice"
      subtitle="Effective date: 28 May 2026 · Last updated: 28 May 2026"
      icon={Bot}
      iconTone="sky"
    >
      <LegalDocument>
        <p>
          SocioGenie is an AI-powered social-media operating system operated by{' '}
          <strong>MAGNATEX LLP</strong>. This Notice describes how generative
          AI is used inside SocioGenie, what users can expect, and how we
          comply with applicable AI-transparency obligations including{' '}
          <strong>EU AI Act Regulation (EU) 2024/1689</strong>, the{' '}
          <strong>UK&apos;s Online Safety Act 2023</strong>, the{' '}
          <strong>U.S. FTC Act</strong> guidance on AI-generated endorsements,
          and India&apos;s evolving AI-advisory framework under the MeitY.
        </p>

        <h2>1. AI is Central to SocioGenie</h2>
        <p>
          Most of the content shown to you or published from your account
          through SocioGenie is <strong>generated by artificial-intelligence
          models</strong>. This includes captions, post creatives, festival
          posts, product adverts, content strategies, AI Memory Layer
          suggestions, and chatbot responses. SocioGenie is therefore an{' '}
          <em>AI system</em> for the purposes of EU AI Act Article 3(1) and is
          subject to the transparency obligations of EU AI Act Article 50.
        </p>

        <h2>2. Which AI Providers We Use</h2>
        <p>
          SocioGenie does not train its own foundation models. We orchestrate
          and prompt large-language and image-generation models operated by
          third-party providers:
        </p>
        <ul>
          <li>
            <strong>OpenAI, L.L.C.</strong> — text and image generation.
          </li>
          <li>
            <strong>Anthropic, PBC</strong> — text generation and content
            reasoning.
          </li>
          <li>
            <strong>Google LLC (Gemini / Vertex AI)</strong> — text, image, and
            multi-modal generation.
          </li>
        </ul>
        <p>
          These providers act as our sub-processors. They are subject to their
          own usage policies, and we configure their APIs to opt out of using
          your data for training their public models wherever the option is
          available. See our{' '}
          <a href="/legal/sub-processors">Sub-processors</a> page for details.
        </p>

        <h2>3. What We Do Not Use Your Data For</h2>
        <p>
          <strong>
            We do not use customer data — including brand assets, AI Memory
            Layer content, uploaded products, prompts, generated outputs, or
            social-media analytics — to train, fine-tune, or evaluate our own
            AI models, nor do we permit our AI providers to train their
            public models on your data under our standard configuration.
          </strong>{' '}
          This commitment is also reflected in our{' '}
          <a href="/legal/privacy">Privacy Policy</a> and{' '}
          <a href="/legal/terms">Terms of Service</a>.
        </p>

        <h2>4. Synthetic Content &amp; AI Labelling</h2>
        <p>
          Content created using SocioGenie is{' '}
          <strong>synthetic, machine-generated content</strong> within the
          meaning of EU AI Act Article 50(2). You are the deployer of that
          content. To meet your obligations under Article 50(4), you should:
        </p>
        <ul>
          <li>
            disclose, where required by law or by the destination platform,
            that the content was generated or assisted by AI;
          </li>
          <li>
            use the platform&apos;s native AI-disclosure tools (e.g., Meta&apos;s
            “AI info” label, LinkedIn&apos;s “AI-generated content” disclosure)
            where applicable;
          </li>
          <li>
            include a visible AI disclosure (such as “Generated with AI” or a
            statement in the caption) when posting deepfake, illustrative, or
            non-photographic content depicting real events or people, in
            accordance with EU AI Act Article 50(4) and your local law.
          </li>
        </ul>
        <p>
          Where technically feasible, AI-generated images produced through
          providers that support it may include content-provenance signals
          (such as C2PA metadata or invisible watermarks) inserted by the
          provider. We do not strip those signals. Note that some social
          networks recompress or transcode media on upload and may remove
          provenance metadata; we are not responsible for that downstream
          behaviour.
        </p>

        <h2>5. AI Outputs Are Not Always Accurate</h2>
        <p>
          AI outputs are produced algorithmically and may:
        </p>
        <ul>
          <li>
            contain factual inaccuracies, hallucinations, fabricated quotations,
            or outdated information;
          </li>
          <li>
            reflect biases present in the underlying training data of the
            providers;
          </li>
          <li>
            generate content that is similar or identical to outputs produced
            for other SocioGenie users with similar inputs;
          </li>
          <li>
            be unsuitable for use in regulated industries (medical, legal,
            financial, safety-critical) without review by a qualified
            professional.
          </li>
        </ul>
        <p>
          <strong>
            You are solely responsible for reviewing AI-generated content
            before publishing it.
          </strong>{' '}
          Human review under our Managed Approval Mode is limited to branding
          consistency, caption quality, creative presentation, and posting
          readiness; it is <em>not</em> a fact-check, legal review, or
          regulatory clearance.
        </p>

        <h2>6. Automated Decision-Making (GDPR Art. 22 &amp; DPDP)</h2>
        <p>
          The AI Engine schedules and (subject to your approval-mode setting)
          publishes content automatically. These decisions are based on your
          configured preferences (timezone, posting frequency, audience
          targeting), historical engagement, and platform best-practice
          heuristics. They do not produce legal effects on you within the
          meaning of GDPR Article 22(1) and are not solely-automated decisions
          of that kind. You can at any time:
        </p>
        <ul>
          <li>
            switch from automatic publication to <strong>User Approval Mode</strong>{' '}
            to manually review every post before it goes live;
          </li>
          <li>disable the AI Engine entirely;</li>
          <li>delete your AI Memory Layer and Brand DNA.</li>
        </ul>

        <h2>7. Content That Is Not Permitted</h2>
        <p>
          You must not use the AI features of SocioGenie to create content
          that is prohibited under our{' '}
          <a href="/legal/acceptable-use">Acceptable Use Policy</a>, including
          (without limitation):
        </p>
        <ul>
          <li>
            sexual or sexualised depictions of real, identifiable people without
            their documented consent;
          </li>
          <li>any sexualised depiction of minors (CSAM);</li>
          <li>
            deepfake impersonation of public figures intended to deceive,
            defame, or influence elections;
          </li>
          <li>
            manipulated media of identifiable individuals likely to cause
            serious harm to their reputation, business, or safety;
          </li>
          <li>
            health, legal, or financial advice presented as professional
            advice;
          </li>
          <li>
            content designed to circumvent the moderation policies of OpenAI,
            Anthropic, Google AI, Meta, or LinkedIn.
          </li>
        </ul>

        <h2>8. Safeguards We Apply</h2>
        <p>To reduce harm from AI misuse, we:</p>
        <ul>
          <li>
            apply provider-side moderation filters (OpenAI Moderation API,
            equivalent provider filters);
          </li>
          <li>
            block prompts that match our internal disallow-lists for hate,
            sexual minors, terrorism, weapons of mass destruction, and CSAM;
          </li>
          <li>
            log AI generation events for incident response and abuse
            investigations (logs are retained per our Privacy Policy);
          </li>
          <li>
            reserve the right to refuse, throttle, or terminate any account
            that attempts to generate prohibited content.
          </li>
        </ul>

        <h2>9. Your Rights Regarding AI Processing</h2>
        <p>
          Under the GDPR, the UK GDPR, the DPDP Act, the CCPA, and other
          applicable data-protection laws, you have rights regarding the
          personal data processed by AI in connection with the Services. These
          include the right to access, rectify, restrict, delete, and (where
          applicable) port your data, and the right to object to processing
          based on legitimate interest. Full details and how to exercise these
          rights are set out in our{' '}
          <a href="/legal/privacy">Privacy Policy</a>.
        </p>

        <h2>10. Contact &amp; AI-Related Complaints</h2>
        <p>
          If you have concerns about how AI is used in SocioGenie, or if you
          believe you have encountered AI-generated content that violates this
          Notice or applicable law, please contact:
        </p>
        <ul>
          <li>
            <strong>AI &amp; trust queries:</strong>{' '}
            <a href="mailto:founder@magnatex.co">founder@magnatex.co</a>
          </li>
          <li>
            <strong>General support:</strong>{' '}
            <a href="mailto:support@magnatex.co">support@magnatex.co</a>
          </li>
          <li>
            <strong>Postal:</strong> MAGNATEX LLP (LLPIN: ACU-5689), 111,
            Fortune Business Hub, Sola, Nr. Satyamev Elysium, Ahmedabad,
            Gujarat 380060, India
          </li>
        </ul>
      </LegalDocument>
    </LegalPage>
  );
}
