/* eslint-disable */
/**
 * AUTO-GENERATED by export-how-it-looks.ts — do not edit by hand.
 * Brand: clothing
 * Captions come from scheduledPosts.message on the demo user.
 * Re-run: pnpm export-how-it-looks -- --brand=clothing
 *   or:   pnpm export-how-it-looks -- --brand=clothing --uid=DynbPemyk4ay3TDOFexiZ7lSj763
 */
export const GENERATED_SHOWCASE_BRAND_ID = "clothing" as const;

export const GENERATED_SHOWCASE_BRAND = {
  "name": "Neon Clothes",
  "handle": "neon_clothes",
  "tagline": "Fashion",
  "followersLabel": "1.2K",
  "followingLabel": "186"
} as const;

export const GENERATED_SHOWCASE_POSTS = [
  {
    "id": "UQqAAFOGwFujs1PPELap",
    "platform": "facebook",
    "scheduleAt": "2026-09-08T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Why does this shirt hit different? Tailored fit + dopamine energy in one piece. From afternoon to night out — it just works. 90% of our community agrees. Questions about your size or how to style it? DM us.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/UQqAAFOGwFujs1PPELap/image.png"
  },
  {
    "id": "nrB6ZPYNZbSF0k2NFLMC",
    "platform": "linkedin",
    "scheduleAt": "2026-09-07T20:00:00.000Z",
    "mediaType": "image",
    "caption": "Transitioning from summer heat to cooler days doesn't mean ditching your vibrant energy. Our latest neon t-shirts layer seamlessly with our casual hoodies, giving you the confidence to dress bold in any season.\n\nWhat makes the difference? Precision fit. 90% of our community loves how our pieces hug and drape—no bunching, no awkward gaps. Whether you're styling for a night out or casual weekend plans, the versatility is real.\n\nHow are *you* layering these this season? Drop your go-to combo below—we're collecting the best style moves. 🔥\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/nrB6ZPYNZbSF0k2NFLMC/image.png"
  },
  {
    "id": "QKuMdsJkBDpdhI7IuRMz",
    "platform": "instagram",
    "scheduleAt": "2026-09-07T20:00:00.000Z",
    "mediaType": "image",
    "caption": "Would you rather? Timeless, crisp versatility that works every occasion—or full energy with bold neon to turn heads? Our signature white button-down delivers quiet luxury with modern fit perfection. Drop your aesthetic below. What's your vibe?\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/QKuMdsJkBDpdhI7IuRMz/image.png"
  },
  {
    "id": "XO2SBrdgI1mkBc3dpB4o",
    "platform": "instagram",
    "scheduleAt": "2026-09-07T11:30:00.000Z",
    "mediaType": "image",
    "caption": "90% of our community confirms it: our signature white hoodie delivers the perfect fit for every body type. Versatile, comfortable, bold—your go-to layer from casual daytime to vibrant evening moments. When fit is trusted, style follows. Share this with someone who deserves the fit that works.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/XO2SBrdgI1mkBc3dpB4o/image.png"
  },
  {
    "id": "VADAYpMCJ12FwVdqYaeN",
    "platform": "facebook",
    "scheduleAt": "2026-09-07T11:30:00.000Z",
    "mediaType": "image",
    "caption": "Red flag: Bored by your closet, settling for basic. Green flag: Wildflower tee that turns heads at every event—90% love our fit. Which one do you choose?\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/VADAYpMCJ12FwVdqYaeN/image.png"
  },
  {
    "id": "6UmEYJh0JJkRGIRPrpo7",
    "platform": "linkedin",
    "scheduleAt": "2026-09-07T11:30:00.000Z",
    "mediaType": "image",
    "caption": "Summer's energy fades, but your style shouldn't follow suit.\n\nThat gap between \"works for August\" and \"works for September\"? Our distressed denim bridges it. Precision fit that 90% of our community trusts—relaxed, lived-in, intentional. The text-printed details? They're a conversation, not an afterthought.\n\nPair these with our vibrant tees, and you've solved the real struggle: durable, professional versatility *and* personal edge. No compromise as the season shifts.\n\nSave this for your wardrobe refresh.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/6UmEYJh0JJkRGIRPrpo7/image.png"
  },
  {
    "id": "phu0HNGKifWxkuC0Yvk1",
    "platform": "facebook",
    "scheduleAt": "2026-09-05T08:30:00.000Z",
    "mediaType": "image",
    "caption": "A teacher's radiant smile, vibrant attire, and patient hand guiding curious minds—this is Teachers' Day. Neon Clothes celebrates the educators who shape our world with color, care, and endless inspiration. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/phu0HNGKifWxkuC0Yvk1/image.png"
  },
  {
    "id": "em7N6I4yyFc0B1STxYLy",
    "platform": "instagram",
    "scheduleAt": "2026-09-05T08:30:00.000Z",
    "mediaType": "image",
    "caption": "Teaching shapes futures. Neon Clothes honors every educator who illuminates minds with passion and purpose. Your vibrant spirit inspires us all. Happy Teachers' Day! 🌟 #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/em7N6I4yyFc0B1STxYLy/image.png"
  },
  {
    "id": "Xee07VY75hBT8BQr4ZlM",
    "platform": "linkedin",
    "scheduleAt": "2026-09-05T08:30:00.000Z",
    "mediaType": "image",
    "caption": "Today, we honor the architects of tomorrow—the educators who light the path of learning with patience, passion, and purpose.\n\nTeachers' Day is a moment to celebrate mentorship in all its forms: the guidance that shapes character, the wisdom shared in classrooms and open spaces, the quiet strength of those who believe in every student's potential.\n\nAt Neon Clothes, we believe great style and great teaching share something vital—authenticity and confidence. Just as our vibrant fabrics empower you to express who you are, educators empower minds to discover their voice.\n\nHere's to the teachers who make the difference. Thank you for everything.\n\n#NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/Xee07VY75hBT8BQr4ZlM/image.png"
  },
  {
    "id": "pdIV3OJBsl9QAMHtuJKP",
    "platform": "linkedin",
    "scheduleAt": "2026-09-01T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Your style is your story. At Neon Clothes, we believe fashion is the most authentic form of self-expression—where vibrant color meets everyday comfort, and individuality shines brightest.\n\nThis season, celebrate the unique energy you bring to every room, every street, every moment. Wear what makes you feel alive.\n\n#NeonFashion #VibrantStyles #TrendyWear\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/pdIV3OJBsl9QAMHtuJKP/image.png"
  },
  {
    "id": "FDYV3zxzbcNTiruGFJLR",
    "platform": "instagram",
    "scheduleAt": "2026-09-01T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Every outfit tells your story. Neon Clothes celebrates the individuals who wear their confidence loud and proud. Find your vibrant edge. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/FDYV3zxzbcNTiruGFJLR/image.png"
  },
  {
    "id": "15e9MlAcPs10aLfTjzIg",
    "platform": "facebook",
    "scheduleAt": "2026-09-01T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Express yourself boldly. Neon Clothes celebrates your unique style with vibrant fashion designed for everyday confidence. Discover where color meets comfort. #NeonFashion #VibrantStyles #TrendyWear\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/15e9MlAcPs10aLfTjzIg/image.png"
  },
  {
    "id": "mT6HZ3VDI69ofWeL7Nsn",
    "platform": "facebook",
    "scheduleAt": "2026-08-31T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Weekend adventures demand color. Neon Clothes brings vibrant style to every escape—where bold fashion meets outdoor joy. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/mT6HZ3VDI69ofWeL7Nsn/image.png"
  },
  {
    "id": "j1saiY6c662mqOdfnacH",
    "platform": "instagram",
    "scheduleAt": "2026-08-31T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Weekends call for bold style and brighter moments. Neon Clothes brings vibrant fashion to every adventure—where comfort meets color. Dress to celebrate life. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/j1saiY6c662mqOdfnacH/image.png"
  },
  {
    "id": "56NX5dIpogoN4CpvrInm",
    "platform": "linkedin",
    "scheduleAt": "2026-08-31T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Weekends are made for color. Whether you're gathering with friends in nature or simply stepping away from the ordinary, Neon Clothes helps you celebrate every moment in bold, vibrant style. Our premium neon pieces transform everyday adventures into statements of joy and confidence.\n\nWhere vibrant fashion meets everyday comfort — that's the Neon Clothes promise.\n\n#NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/56NX5dIpogoN4CpvrInm/image.png"
  },
  {
    "id": "txxAijPpyQgZYdSkgiQt",
    "platform": "facebook",
    "scheduleAt": "2026-08-30T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Let your style shine as the sun sets. Neon Clothes: where vibrant fashion meets everyday comfort. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/txxAijPpyQgZYdSkgiQt/image.png"
  },
  {
    "id": "WvaF3ky3Y750ts0HPgUR",
    "platform": "instagram",
    "scheduleAt": "2026-08-30T03:00:00.000Z",
    "mediaType": "image",
    "caption": "As the sun sets, let your vibrant edge shine. Neon Clothes celebrates the magic where bold distressed denim meets the glow of everyday confidence. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/WvaF3ky3Y750ts0HPgUR/image.png"
  },
  {
    "id": "7g2deNnGXThYZMwJUZXa",
    "platform": "linkedin",
    "scheduleAt": "2026-08-30T03:00:00.000Z",
    "mediaType": "image",
    "caption": "As daylight fades, your style becomes the focal point. The white hoodie—a timeless essential from Neon Clothes—proves that vibrant living isn't about loud colors alone. It's about confidence, comfort, and pieces that transition seamlessly from day to evening. Whether styled solo or layered, this hoodie embodies where vibrant fashion meets everyday comfort. Let the glow of your personal style shine brightest as the sun sets. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/7g2deNnGXThYZMwJUZXa/image.png"
  },
  {
    "id": "pfMGPQNKvNB9kWzZ4K2C",
    "platform": "facebook",
    "scheduleAt": "2026-08-29T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Start your day with vibrant energy. Friends, coffee, and bold style—where Neon Clothes meets everyday comfort. #NeonFashion #VibrantStyles #TrendyWear\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/pfMGPQNKvNB9kWzZ4K2C/image.png"
  },
  {
    "id": "jxg320Frotw15ROvlCCo",
    "platform": "instagram",
    "scheduleAt": "2026-08-29T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Start your day with vibrant energy. Neon Clothes celebrates everyday comfort wrapped in bold color. Where vibrant fashion meets real life, real laughter, real you. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/jxg320Frotw15ROvlCCo/image.png"
  },
  {
    "id": "dOdI2Bz1R2t5MSNwDM3M",
    "platform": "linkedin",
    "scheduleAt": "2026-08-29T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Your morning just got brighter. There's something electric about stepping into the day wearing a color that feels like *you*—confidence in every fiber, comfort in every moment. At Neon Clothes, we believe vibrant fashion isn't just what you wear; it's how you show up for yourself and the people around you. That bold red tee, the lime-green shirt, the electric purple—each one a statement of individuality that turns a simple café coffee into a celebration of living unapologetically.\n\nWhere vibrant fashion meets everyday comfort.\n\n#NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/dOdI2Bz1R2t5MSNwDM3M/image.png"
  },
  {
    "id": "OKPxh7NUpAd53dffiQX8",
    "platform": "facebook",
    "scheduleAt": "2026-08-28T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Comfort meets color at home. Neon Clothes brings vibrant style to your everyday moments. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/OKPxh7NUpAd53dffiQX8/image.png"
  },
  {
    "id": "NnRich3AJdSN7aDTvK1Q",
    "platform": "instagram",
    "scheduleAt": "2026-08-28T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Where vibrant fashion meets everyday comfort. Neon Clothes celebrates the art of lounging in color—bold style that feels effortless, serene spaces that spark joy. Embrace your vibrant living. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/NnRich3AJdSN7aDTvK1Q/image.png"
  },
  {
    "id": "MhFIZZwQkJtlbKMbhaTJ",
    "platform": "linkedin",
    "scheduleAt": "2026-08-28T03:00:00.000Z",
    "mediaType": "image",
    "caption": "Where vibrant fashion meets everyday comfort. Neon Clothes celebrates the art of living boldly—choosing color and style that feels as good as it looks. Your wardrobe should energize you, inspire confidence, and make every moment feel intentional. From sunrise lounging to evening adventures, wrap yourself in pieces that radiate joy and comfort. Embrace the vibrant life you deserve. Discover what comfort in color truly means. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/MhFIZZwQkJtlbKMbhaTJ/image.png"
  },
  {
    "id": "Qz35ydNUU0lBwGDpkWDh",
    "platform": "instagram",
    "scheduleAt": "2026-08-26T14:30:00.000Z",
    "mediaType": "video",
    "caption": "Looking for jeans that work as hard as you do? Our blue denim pairs comfort with timeless style—ready for everything from casual workdays to nights out. Tap to explore what everyday bold looks like.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "videoUrl": "/landing/how-it-looks/clothing/instagram/Qz35ydNUU0lBwGDpkWDh/video.mp4",
    "posterUrl": "/landing/how-it-looks/clothing/instagram/Qz35ydNUU0lBwGDpkWDh/poster.png"
  },
  {
    "id": "OlN2A34LE3TkjWix9Pqr",
    "platform": "linkedin",
    "scheduleAt": "2026-08-26T14:30:00.000Z",
    "mediaType": "video",
    "caption": "Vibrant cloth isn't just what you wear—it's how you show up in the world.\n\nOur latest collection brings color and confidence together. Whether it's a crisp white polo or a bold statement piece, every garment is designed for the modern Indian lifestyle: quality that holds up, colors that last, and style that turns heads.\n\nSee how our pieces work for real life. What's your go-to power piece?\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "videoUrl": "/landing/how-it-looks/clothing/linkedin/OlN2A34LE3TkjWix9Pqr/video.mp4",
    "posterUrl": "/landing/how-it-looks/clothing/linkedin/OlN2A34LE3TkjWix9Pqr/poster.png"
  },
  {
    "id": "Yr1J1BQijFnfE6kOn4EM",
    "platform": "instagram",
    "scheduleAt": "2026-08-23T14:30:00.000Z",
    "mediaType": "carousel",
    "caption": "The white hoodie you love just became your secret weapon for any night out. Layer it over vibrant neons, throw it open for a pop color, or wear it solo—three simple ways to get heads turning at every event. Our fit speaks for itself: 90% our customers can't stop wearing them. Ready to glow this season? Explore vibrant styles for every occasion.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "carouselSlides": [
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/Yr1J1BQijFnfE6kOn4EM/slide-0.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/Yr1J1BQijFnfE6kOn4EM/slide-1.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/Yr1J1BQijFnfE6kOn4EM/slide-2.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/Yr1J1BQijFnfE6kOn4EM/slide-3.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/Yr1J1BQijFnfE6kOn4EM/slide-4.jpg"
      }
    ]
  },
  {
    "id": "Cw3AFvtUQ0nIIfNgQcNd",
    "platform": "linkedin",
    "scheduleAt": "2026-08-23T14:30:00.000Z",
    "mediaType": "carousel",
    "caption": "Neutral minimalism is safe. It's also invisible. In India's fashion landscape right now, vibrant isn't a trend—it's a strategy. Our neon collection launches this summer on one simple belief: the right fit plus bold color equals confidence. 90% our customers say they love our fit, and they wear it everywhere—from weekend hangouts to the center the room at every event. Summer's about standing out, not blending in. Your wardrobe should have a pulse. Explore our vibrant styles for every occasion.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "carouselSlides": [
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/Cw3AFvtUQ0nIIfNgQcNd/slide-0.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/Cw3AFvtUQ0nIIfNgQcNd/slide-1.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/Cw3AFvtUQ0nIIfNgQcNd/slide-2.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/Cw3AFvtUQ0nIIfNgQcNd/slide-3.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/Cw3AFvtUQ0nIIfNgQcNd/slide-4.jpg"
      }
    ]
  },
  {
    "id": "CpFvfftMygEgrhxe4yOs",
    "platform": "facebook",
    "scheduleAt": "2026-08-21T14:30:00.000Z",
    "mediaType": "video",
    "caption": "What's your take on bold prints that double as personality? Our latest collection proves colorful design and everyday comfort aren't mutually exclusive. Drop your view below — what draws you to pieces like this?\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "videoUrl": "/landing/how-it-looks/clothing/facebook/CpFvfftMygEgrhxe4yOs/video.mp4",
    "posterUrl": "/landing/how-it-looks/clothing/facebook/CpFvfftMygEgrhxe4yOs/poster.png"
  },
  {
    "id": "zeeVs9m3c6qbSZZzS5mq",
    "platform": "instagram",
    "scheduleAt": "2026-08-20T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Stop hiding bold style in your closet. This guitar-graphic tee demands to be worn now—not saved for someday. Our community agrees: 90% love the fit. Bold energy every day, not just weekends. Are you team 'wear it now' or team 'special occasions'? Drop your take below.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/zeeVs9m3c6qbSZZzS5mq/image.png"
  },
  {
    "id": "XnX2YFfIMLgxCvm8dNvW",
    "platform": "facebook",
    "scheduleAt": "2026-08-19T14:30:00.000Z",
    "mediaType": "carousel",
    "caption": "At Neon Clothes, we design every piece to lift your mood and your confidence. Our new summer collection is all about vibrant styles for every occasion—whether you're heading to a beach hangout or a night out with friends. Like our customers say, the fit is everything, and we've perfected it. Dopamine dressing is real, and color is your best accessory. Explore our collection and find the neon vibes that speak to you.\n\nWebsite:- neonclothes.in",
    "carouselSlides": [
      {
        "imageUrl": "/landing/how-it-looks/clothing/facebook/XnX2YFfIMLgxCvm8dNvW/slide-0.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/facebook/XnX2YFfIMLgxCvm8dNvW/slide-1.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/facebook/XnX2YFfIMLgxCvm8dNvW/slide-2.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/facebook/XnX2YFfIMLgxCvm8dNvW/slide-3.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/facebook/XnX2YFfIMLgxCvm8dNvW/slide-4.jpg"
      }
    ]
  },
  {
    "id": "ncCsMN0kZuTSlFudunwG",
    "platform": "linkedin",
    "scheduleAt": "2026-08-19T03:00:00.000Z",
    "mediaType": "carousel",
    "caption": "Summer isn't just a season—it's a mood. Our vibrant graphic tees are designed to lift your spirit and transition seamlessly from lazy afternoons to unforgettable evenings. With 90% customers raving about our fit, we've perfected the balance between comfort and style. Whether you're styling for a party or casual hangout, these pieces work harder than you'd expect. Discover how our summer collection is redefining casual wear for young adults who refuse to compromise on quality or vibrancy. Explore our latest drops and find your perfect fit.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "carouselSlides": [
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/ncCsMN0kZuTSlFudunwG/slide-0.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/ncCsMN0kZuTSlFudunwG/slide-1.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/ncCsMN0kZuTSlFudunwG/slide-2.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/ncCsMN0kZuTSlFudunwG/slide-3.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/linkedin/ncCsMN0kZuTSlFudunwG/slide-4.jpg"
      }
    ]
  },
  {
    "id": "06VmZH7vQlO4ZbYlm5NN",
    "platform": "instagram",
    "scheduleAt": "2026-08-19T03:00:00.000Z",
    "mediaType": "carousel",
    "caption": "Vibrant styles for every occasion—from festival nights to casual days. Our Summer collection is here to elevate your wardrobe with bold, statement-making pieces that fit the way you move. See how real customers are turning heads at events. Discover your next favorite at Neon Clothes.\n\nWebsite:- neonclothes.in\nContact:- +919498103210\nEmail:- clothes@neon.com",
    "carouselSlides": [
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/06VmZH7vQlO4ZbYlm5NN/slide-0.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/06VmZH7vQlO4ZbYlm5NN/slide-1.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/06VmZH7vQlO4ZbYlm5NN/slide-2.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/06VmZH7vQlO4ZbYlm5NN/slide-3.jpg"
      },
      {
        "imageUrl": "/landing/how-it-looks/clothing/instagram/06VmZH7vQlO4ZbYlm5NN/slide-4.jpg"
      }
    ]
  },
  {
    "id": "ZSZ5RZNgfnqdk4DFWtUJ",
    "platform": "linkedin",
    "scheduleAt": "2026-08-17T14:30:00.000Z",
    "mediaType": "image",
    "caption": "We used to think loud color was everything. Turns out, versatility lives in the fit itself.\n\nOur white polo isn't a basic—it's the anchor. Pair it with neon for parties, layer it for polish, wear it solo for timeless ease. 90% of our community trusts this fit to ground their boldest looks.\n\nThe secret to real style? Master the foundation. Everything else becomes possible.\n\nSave this for your next wardrobe strategy.\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/ZSZ5RZNgfnqdk4DFWtUJ/image.png"
  },
  {
    "id": "A6Cf6wjiO4qIDAd1TGY4",
    "platform": "facebook",
    "scheduleAt": "2026-08-17T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Late-summer staple alert. Our white long-sleeve shirt brings effortless polish to any look—tailored fit, button-down collar, premium construction. 90% of our customers love how it feels. Make it yours today. Link in bio.\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/A6Cf6wjiO4qIDAd1TGY4/image.png"
  },
  {
    "id": "vyRSHdN3ZEjZc7SvdQVO",
    "platform": "facebook",
    "scheduleAt": "2026-08-15T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Neon Clothes celebrates India's freedom and the spirit of patriotism this Independence Day. Vibrant fashion, timeless pride. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/facebook/vyRSHdN3ZEjZc7SvdQVO/image.png"
  },
  {
    "id": "jGgEo7O4FIVWg996mO9m",
    "platform": "linkedin",
    "scheduleAt": "2026-08-15T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Today, we celebrate the spirit of freedom and the courage of those who fought for India's independence. At Neon Clothes, we honor this pride with vibrant style — because true patriotism shines brightest when we wear it with confidence and joy.\n\nFrom the tricolor that waves in our hearts to the colors we choose to wear, Independence Day reminds us that every thread of our nation's fabric is woven with sacrifice and hope. Let's celebrate together, wrapped in the pride of our heritage.\n\nHappy Independence Day! 🇮🇳\n\n#NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/linkedin/jGgEo7O4FIVWg996mO9m/image.png"
  },
  {
    "id": "VsNpRYb6vnNbxVws3gRT",
    "platform": "instagram",
    "scheduleAt": "2026-08-15T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Drape yourself in patriotism this Independence Day. Neon Clothes celebrates the spirit of 1947 with vibrant hues that honor freedom, sacrifice, and national pride. Where vibrant fashion meets everyday comfort. #NeonFashion #TrendyWear #VibrantStyles\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/VsNpRYb6vnNbxVws3gRT/image.png"
  },
  {
    "id": "D8HhuHCEHa9CZZBsAuUr",
    "platform": "instagram",
    "scheduleAt": "2026-08-15T14:30:00.000Z",
    "mediaType": "image",
    "caption": "Behind the scenes of our summer studio flow — where every vibrant piece gets the creative attention it deserves. This is where the magic happens: bold colors, precise fit, real energy. What's your go-to neon style for a night out?\n\nWebsite:- neonclothes.in",
    "imageUrl": "/landing/how-it-looks/clothing/instagram/D8HhuHCEHa9CZZBsAuUr/image.png"
  }
] as const;
