/* eslint-disable */
/**
 * AUTO-GENERATED by export-how-it-looks.ts — do not edit by hand.
 * Brand: jewelry
 * Captions come from scheduledPosts.message on the demo user.
 * Re-run: pnpm export-how-it-looks -- --brand=jewelry
 *   or:   pnpm export-how-it-looks -- --brand=jewelry --uid=j4IpxqGSdiaVc3Vg8fWaE5mOIqE3
 */
export const GENERATED_SHOWCASE_BRAND_ID = 'jewelry' as const;

export const GENERATED_SHOWCASE_BRAND = {
  name: 'Neon Luxe',
  handle: 'neon_luxe',
  tagline: 'Jewellery',
  followersLabel: '1.2K',
  followingLabel: '186',
} as const;

export const GENERATED_SHOWCASE_POSTS = [
  {
    id: 'UzMLtjTRYuVy3TLl4YyJ',
    platform: 'facebook',
    scheduleAt: '2026-09-08T14:30:00.000Z',
    mediaType: 'video',
    caption:
      'Every detail matters when it comes to jewelry that tells your story. This piece combines the grace of pearls with precision craftsmanship—designed to be worn and treasured for a lifetime. What draws you to a piece like this? Share your thoughts below. ✨\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    videoUrl:
      '/landing/how-it-looks/jewelry/facebook/UzMLtjTRYuVy3TLl4YyJ/video.mp4',
    posterUrl:
      '/landing/how-it-looks/jewelry/facebook/UzMLtjTRYuVy3TLl4YyJ/poster.png',
  },
  {
    id: 'bfIWb6xauif7hRJL2y6W',
    platform: 'linkedin',
    scheduleAt: '2026-09-06T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "68% of luxury consumers now demand verifiable sourcing. At Neon Luxe, transparency isn't an afterthought—it's woven into every piece. Our handcrafted silver and purple gemstone collection embodies this shift: ethically sourced materials, meticulous craftsmanship, and a story you can trust. When you invest in heirloom jewellery, you deserve to know exactly where it comes from. This is modern bridal luxury—beauty paired with integrity. Share this with someone building a collection that mirrors their values.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/bfIWb6xauif7hRJL2y6W/image.png',
  },
  {
    id: 'KCK9KniWiyXLkrUJDBRL',
    platform: 'instagram',
    scheduleAt: '2026-09-06T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'The most sophisticated bridal style begins with one exceptional piece. Skip the matching set. Choose an ethically sourced, brilliant-cut diamond halo ring that reflects your personal journey—and stands the test of time. This is heirloom-quality investment in timeless elegance. Save this for your next bridal moment.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/KCK9KniWiyXLkrUJDBRL/image.png',
  },
  {
    id: '3SfVa9iLmJB25uwKL74E',
    platform: 'facebook',
    scheduleAt: '2026-09-06T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Myth: delicate jewels won't survive your big day. Fact: Our handcrafted ruby and pearl sets blend sophisticated design with heirloom durability. Ethically sourced gems + expert gold craftsmanship = jewelry that shines as bright on your anniversary as on day one. Save this.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/3SfVa9iLmJB25uwKL74E/image.png',
  },
  {
    id: 'z78eQ3hMi8bl1l4q9mKA',
    platform: 'facebook',
    scheduleAt: '2026-09-04T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Not all jewellery deserves a vault. This diamond cluster ring is built for everyday brilliance—designed to be worn, loved, and passed down. Conscious luxury that actually lives on your hand. Do you invest in pieces you can wear every day?\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/z78eQ3hMi8bl1l4q9mKA/image.png',
  },
  {
    id: 'nTKDZuqBUg6gFqonacPT',
    platform: 'linkedin',
    scheduleAt: '2026-09-04T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "In a sea of mass-produced sets, our intricately layered silver collections stand apart—each piece traceable, ethically sourced, and crafted to outlive the season. These aren't accessories you wear once; they're heirlooms you build. From your wedding day into your boardroom, boardroom into decades ahead. When you choose bespoke artistry over fleeting trends, you're choosing pieces that reflect your values and your story. That's the difference between owning jewelry and owning legacy.\n\nSave this for your next jewelry conversation.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/nTKDZuqBUg6gFqonacPT/image.png',
  },
  {
    id: 'JTOR4eUlBcwPNnIZJDvO',
    platform: 'instagram',
    scheduleAt: '2026-09-04T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'True beauty runs deeper than the surface. At Neon Luxe, we craft every gold necklace and statement set from ethically sourced materials—pieces designed to become treasured heirlooms, not fleeting trends. Integrity matters. What does craftsmanship mean to you?\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/JTOR4eUlBcwPNnIZJDvO/image.png',
  },
  {
    id: 'b4lZOSJicJHwUcYuMsJa',
    platform: 'linkedin',
    scheduleAt: '2026-09-01T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Trend cycles end. Investment pieces endure.\n\nThe luxury market conflates newness with desirability—but conscious couples are reclaiming a different standard. A handcrafted gold bangle or emerald-set ring isn't a seasonal purchase; it's a foundational asset that appreciates in meaning with every milestone. Ethically sourced materials and artisanal technique ensure these pieces work harder than trends ever could.\n\nAt Neon Luxe, we position wedding jewellery as what it truly is: wearable wealth. Not disposable fashion. Not a fleeting moment. A decision that honours both aesthetics and integrity.\n\nYour wedding collection should reflect who you are becoming, not who marketing wants you to be.\n\nWhat's your take on heirloom-grade jewellery as a wedding investment?\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/b4lZOSJicJHwUcYuMsJa/image.png',
  },
  {
    id: 'M1evhzZaVE2c54WOzp7l',
    platform: 'facebook',
    scheduleAt: '2026-09-01T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "72% of luxury brides prioritize provenance—and this multi-layered silver necklace with pink gemstones proves ethics and elegance aren't mutually exclusive. Every piece is a future heirloom. Pass this along.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/M1evhzZaVE2c54WOzp7l/image.png',
  },
  {
    id: '1ELViPi4Qray6L7mTGyV',
    platform: 'instagram',
    scheduleAt: '2026-09-01T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'A masterpiece designed to endure generations. This multi-layered necklace weaves intricate diamonds with lustrous pearls and ethically sourced golden accents—the heirloom every bride deserves. Timeless elegance for your most cherished moments. Explore our bridal collections in bio.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/1ELViPi4Qray6L7mTGyV/image.png',
  },
  {
    id: 'wW7zrsZ0fMyXNLY9UMWg',
    platform: 'linkedin',
    scheduleAt: '2026-08-29T14:30:00.000Z',
    mediaType: 'carousel',
    caption:
      "At Neon Luxe, we've spent years perfecting the art the heirloom. Every piece—from our floral silver sets to statement diamond rings—is designed with one promise in mind: jewellery that doesn't fade after the wedding day. We source ethically, we craft with intention, and we build for brides who understand the difference between trend and treasure. Whether it's the mandap or a decade later, your Neon Luxe collection grows with you. Visit one our locations across India for a curated bridal styling session, and discover why investment-grade craftsmanship matters. Your story deserves pieces as enduring as it is.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    carouselSlides: [
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/linkedin/wW7zrsZ0fMyXNLY9UMWg/slide-0.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/linkedin/wW7zrsZ0fMyXNLY9UMWg/slide-1.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/linkedin/wW7zrsZ0fMyXNLY9UMWg/slide-2.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/linkedin/wW7zrsZ0fMyXNLY9UMWg/slide-3.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/linkedin/wW7zrsZ0fMyXNLY9UMWg/slide-4.jpg',
      },
    ],
  },
  {
    id: 'd5sOi8h1qqoaaQSQYhRc',
    platform: 'facebook',
    scheduleAt: '2026-08-29T14:30:00.000Z',
    mediaType: 'carousel',
    caption:
      "Every bride deserves jewellery that tells her story—not just on her wedding day, but for generations to come. At Neon Luxe, we craft each piece from ethically sourced gold and diamonds, designed to become the heirloom she treasures. Whether it's a statement necklace that captures the light or rings that mark life's most sacred moments, our collections are built for brides who see beauty as an investment. Across India, brides choose Neon Luxe for craftsmanship that endures. Discover your perfect piece—custom or curated—and wear luxury with purpose. Your love story deserves jewellery as timeless as the commitment it celebrates.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    carouselSlides: [
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/facebook/d5sOi8h1qqoaaQSQYhRc/slide-0.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/facebook/d5sOi8h1qqoaaQSQYhRc/slide-1.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/facebook/d5sOi8h1qqoaaQSQYhRc/slide-2.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/facebook/d5sOi8h1qqoaaQSQYhRc/slide-3.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/facebook/d5sOi8h1qqoaaQSQYhRc/slide-4.jpg',
      },
    ],
  },
  {
    id: 'J6IhUtHti3ll5iiM6uPj',
    platform: 'instagram',
    scheduleAt: '2026-08-29T14:30:00.000Z',
    mediaType: 'carousel',
    caption:
      "At Neon Luxe, we've watched the modern bride evolve. She's moving beyond trends toward pieces that tell a story—diamonds that carry integrity, gold that's layered with intention, and designs that will be passed down for generations. This shift toward heirloom-first jewellery isn't just about beauty; it's about knowing exactly where every stone comes from and trusting the hands that craft it. Your wedding day deserves a collection that reflects who you are and stands the test time. If you're envisioning your wedding jewellery, let's create something timeless together.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    carouselSlides: [
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/instagram/J6IhUtHti3ll5iiM6uPj/slide-0.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/instagram/J6IhUtHti3ll5iiM6uPj/slide-1.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/instagram/J6IhUtHti3ll5iiM6uPj/slide-2.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/instagram/J6IhUtHti3ll5iiM6uPj/slide-3.jpg',
      },
      {
        imageUrl:
          '/landing/how-it-looks/jewelry/instagram/J6IhUtHti3ll5iiM6uPj/slide-4.jpg',
      },
    ],
  },
  {
    id: 'JEGEAz5X3X1APgLlkSVW',
    platform: 'facebook',
    scheduleAt: '2026-08-28T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "As the rakhi is prepared with care, Neon Luxe celebrates the bond of siblings. Where luxury meets craftsmanship, we honor Raksha Bandhan's timeless promise of love and protection. #Jewellery #PremiumJewels #RakshaBandhan\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/JEGEAz5X3X1APgLlkSVW/image.png',
  },
  {
    id: 'ESJXupADTtqT2k1lVD98',
    platform: 'instagram',
    scheduleAt: '2026-08-28T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "A sister's hands tie the sacred rakhi—threads of love, protection, and bond. At Neon Luxe, we celebrate the artistry in every gesture. This Raksha Bandhan, honor your sibling with jewels as timeless as your connection. #Jewellery #PremiumJewels #RakshaBandhan #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/ESJXupADTtqT2k1lVD98/image.png',
  },
  {
    id: '6Zs062FHRilfpATleTwK',
    platform: 'linkedin',
    scheduleAt: '2026-08-28T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "On Raksha Bandhan, we celebrate the sacred bond between siblings — a thread of love, protection, and lifelong connection. At Neon Luxe, we honor this cherished tradition by crafting jewellery that carries meaning through every moment of life's most important relationships. Just as the rakhi symbolizes a sister's care and a brother's promise, our handcrafted pieces become heirlooms that tell your family's story. Where luxury meets craftsmanship — and where family bonds shine brightest. Wishing every sibling pair a Raksha Bandhan filled with warmth, laughter, and treasured memories. #Jewellery #PremiumJewels #FashionJewelry #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/6Zs062FHRilfpATleTwK/image.png',
  },
  {
    id: 'paGyv9pRYw4BtswMBwdb',
    platform: 'instagram',
    scheduleAt: '2026-08-26T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Every piece tells a story. Neon Luxe diamonds are crafted to transcend moments—becoming treasured heirlooms that connect generations. Where luxury meets craftsmanship. #PremiumJewels #HandcraftedJewels #LuxuryAccessories #FashionJewelry #Jewellery\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/paGyv9pRYw4BtswMBwdb/image.png',
  },
  {
    id: 'TGJKRaIAym2tKgsfhTsa',
    platform: 'linkedin',
    scheduleAt: '2026-08-26T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "A piece of jewelry is never just an accessory—it becomes a story. At Neon Luxe, we craft heirlooms designed to be passed from one generation to the next. Each intricate detail, every carefully selected gemstone, every handcrafted element speaks to the legacy you'll leave behind.\n\nWhere luxury meets craftsmanship, timeless elegance is born.\n\n#Jewellery #PremiumJewels #LuxuryAccessories #HandcraftedJewels #FashionJewelry\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/TGJKRaIAym2tKgsfhTsa/image.png',
  },
  {
    id: 'JxCOKae30ug81TGmtmLe',
    platform: 'facebook',
    scheduleAt: '2026-08-26T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Timeless beauty deserves to be passed down. Neon Luxe crafts heirloom pieces where luxury meets craftsmanship, creating legacies that endure. #PremiumJewels #HandcraftedJewels #LuxuryAccessories\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/JxCOKae30ug81TGmtmLe/image.png',
  },
  {
    id: 'ryZNdwFpXtPvgfhYK94v',
    platform: 'facebook',
    scheduleAt: '2026-08-25T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Life's most radiant moments deserve jewelry as extraordinary as the occasion. Neon Luxe—where luxury meets craftsmanship. #PremiumJewels #HandcraftedJewels #LuxuryAccessories\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/ryZNdwFpXtPvgfhYK94v/image.png',
  },
  {
    id: 'EMiiGYiu7ZGAp3j2Z6YJ',
    platform: 'instagram',
    scheduleAt: '2026-08-25T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Every celebration deserves a moment that shines. Neon Luxe jewelry marks life's most radiant milestones with timeless craftsmanship. Where luxury meets the memories you'll treasure forever. #PremiumJewels #HandcraftedJewels #LuxuryAccessories\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/EMiiGYiu7ZGAp3j2Z6YJ/image.png',
  },
  {
    id: '4pd64oFD24xPXj1vuCMN',
    platform: 'linkedin',
    scheduleAt: '2026-08-25T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Life's most cherished moments deserve jewelry that captures their beauty. The Neon Luxe collection celebrates the radiance of your significant milestones—each piece meticulously crafted to honor what matters most. From intimate proposals to treasured celebrations, our handcrafted designs in ruby, pearl, and precious metals become part of your story. Where luxury meets craftsmanship, every moment becomes timeless.\n\n#Jewellery #PremiumJewels #FashionJewelry #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/4pd64oFD24xPXj1vuCMN/image.png',
  },
  {
    id: 'zGJfPXWfAKr59lyRhPlz',
    platform: 'linkedin',
    scheduleAt: '2026-08-24T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Every piece of jewelry tells a story of precision and passion. At Neon Luxe, our artisans dedicate themselves to the intricate craft of creating timeless pieces—each floral motif hand-detailed, every gemstone carefully set. This silver necklace with emerald accents exemplifies the meticulous care that defines our work. Where luxury meets craftsmanship, excellence is non-negotiable. Discover the artistry behind your treasures.\n\n#Jewellery #PremiumJewels #HandcraftedJewels #LuxuryAccessories #FashionJewelry\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/zGJfPXWfAKr59lyRhPlz/image.png',
  },
  {
    id: 'wVCpsy66IEzkCtaPWCV8',
    platform: 'instagram',
    scheduleAt: '2026-08-24T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Every diamond tells a story of precision and passion. At Neon Luxe, our master artisans dedicate countless hours to perfect each piece—hand-selecting stones, setting facets, and crafting bands that endure a lifetime. Where luxury meets craftsmanship. #PremiumJewels #HandcraftedJewels #LuxuryAccessories #FashionJewelry #Jewellery\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/wVCpsy66IEzkCtaPWCV8/image.png',
  },
  {
    id: 'srcG22mrj3mYnq2Z84Ky',
    platform: 'facebook',
    scheduleAt: '2026-08-24T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Each piece tells a story of dedication and artistry. Neon Luxe brings uncompromising craftsmanship to every creation. #HandcraftedJewels #LuxuryAccessories #PremiumJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/srcG22mrj3mYnq2Z84Ky/image.png',
  },
  {
    id: 'tgpJfdbO8r6M0EyHUTWj',
    platform: 'linkedin',
    scheduleAt: '2026-08-23T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Luxury is not just worn—it's embodied. Every piece from Neon Luxe is crafted to reflect the sophistication and confidence of those who understand true elegance. Our multi-layered silver necklaces, adorned with carefully selected gemstones, and our matching earrings and bracelets are more than accessories. They are statements of refined taste and timeless craftsmanship. Where luxury meets craftsmanship—that's the Neon Luxe promise. Discover jewelry that celebrates who you are. #Jewellery #PremiumJewels #FashionJewelry #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/tgpJfdbO8r6M0EyHUTWj/image.png',
  },
  {
    id: '5VX7awhq7jRzS0B16U2S',
    platform: 'instagram',
    scheduleAt: '2026-08-23T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Where luxury meets the moments that matter. Neon Luxe jewelry—handcrafted to embody elegance, designed for those who celebrate fine beauty. Discover timeless pieces that speak for themselves. #PremiumJewels #LuxuryAccessories #HandcraftedJewels #FashionJewelry\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/5VX7awhq7jRzS0B16U2S/image.png',
  },
  {
    id: '3aR8IE8nIsaT1eYbvaUh',
    platform: 'facebook',
    scheduleAt: '2026-08-23T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Every piece tells a story of masterful craftsmanship. Neon Luxe diamonds capture light, elegance, and the timeless luxury you deserve. #PremiumJewels #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/3aR8IE8nIsaT1eYbvaUh/image.png',
  },
  {
    id: 'yfckiXdcIXOBhrOPCUeN',
    platform: 'facebook',
    scheduleAt: '2026-08-22T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Discover the art of elegance with every piece. Neon Luxe celebrates timeless craftsmanship in silver. #PremiumJewels #HandcraftedJewels #LuxuryAccessories #FashionJewelry #Jewellery\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/yfckiXdcIXOBhrOPCUeN/image.png',
  },
  {
    id: 'f1ianYBpvuyURB14GfMa',
    platform: 'linkedin',
    scheduleAt: '2026-08-22T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Every piece tells a story of meticulous craftsmanship and timeless elegance. At Neon Luxe, we believe that true luxury lies in the details—the precision of each gemstone setting, the flow of hand-worked silver, the harmony of a complete collection. Our artisans pour passion into every creation, ensuring that when you wear Neon Luxe, you're wearing a masterpiece. Discover the art of elegance with every piece. Where luxury meets craftsmanship. #Jewellery #PremiumJewels #FashionJewelry #LuxuryAccessories #HandcraftedJewels\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/f1ianYBpvuyURB14GfMa/image.png',
  },
  {
    id: 'VxJUmzWH7yoGp8mEivzu',
    platform: 'instagram',
    scheduleAt: '2026-08-22T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Every piece tells a story of meticulous craftsmanship and timeless beauty. Discover the art of elegance with Neon Luxe—where luxury meets the finest artistry. #PremiumJewels #HandcraftedJewels #LuxuryAccessories #Jewellery\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/VxJUmzWH7yoGp8mEivzu/image.png',
  },
  {
    id: 'sEqkU5puTMc1L1Js9SUE',
    platform: 'instagram',
    scheduleAt: '2026-08-20T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Choosing jewellery that lasts generations starts with clarity. This circular cluster diamond ring transcends trends—its timeless architecture works for every season of your life. Ethically sourced, masterfully crafted, designed to become your legacy. Save this for your bridal journey. 💎\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/sEqkU5puTMc1L1Js9SUE/image.png',
  },
  {
    id: '8gYp4EzJ3syMXZSlsYrQ',
    platform: 'linkedin',
    scheduleAt: '2026-08-20T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Autumn brings the season of intention. For the modern bride, it's not just about the dress—it's about the pieces that become part of her story. Our gold collection embodies this moment: handcrafted statement necklaces, rings, and bangles that honor both timeless artistry and ethical sourcing. These are the heirlooms she'll pass forward. We'd love to hear yours. How did you find your perfect piece? Share your story with us—let's celebrate the brides building legacies, not just memories.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/8gYp4EzJ3syMXZSlsYrQ/image.png',
  },
  {
    id: '0UDp8j87cJ8yLPhUGapB',
    platform: 'facebook',
    scheduleAt: '2026-08-20T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Myth: silver lacks durability for heirlooms. Fact: ethically sourced silver with expert craftsmanship rivals gold in beauty and longevity. Your floral-motif set deserves a place in wedding day lore. Save this for your next bridal moment.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/0UDp8j87cJ8yLPhUGapB/image.png',
  },
  {
    id: 'hmY5Q4ebSbyjUj5JVhd3',
    platform: 'instagram',
    scheduleAt: '2026-08-18T14:30:00.000Z',
    mediaType: 'video',
    caption:
      "Every piece tells a story of precision and passion. Each gemstone, hand-selected and expertly set to capture light the way it's meant to be seen. This is what happens when masterful design meets uncompromising quality. What draws you to exceptional jewelry?\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    videoUrl:
      '/landing/how-it-looks/jewelry/instagram/hmY5Q4ebSbyjUj5JVhd3/video.mp4',
    posterUrl:
      '/landing/how-it-looks/jewelry/instagram/hmY5Q4ebSbyjUj5JVhd3/poster.png',
  },
  {
    id: 'F5yZMBupOc7FBASUilP5',
    platform: 'linkedin',
    scheduleAt: '2026-08-18T14:30:00.000Z',
    mediaType: 'video',
    caption:
      "Every piece tells a story. Behind each design lies meticulous craftsmanship, carefully selected gemstones, and decades of expertise. At Neon Luxe, we don't just create jewelry—we build heirlooms meant to be passed down, treasured across generations. From our workshops across India to your most precious moments, each creation is a commitment to timeless elegance and uncompromising quality. What draws you to fine jewelry? Share your story in the comments.\n\nWebsite:- neonluxe.com\nContact:- +916324589981\nEmail:- neon@luxe.com",
    videoUrl:
      '/landing/how-it-looks/jewelry/linkedin/F5yZMBupOc7FBASUilP5/video.mp4',
    posterUrl:
      '/landing/how-it-looks/jewelry/linkedin/F5yZMBupOc7FBASUilP5/poster.png',
  },
  {
    id: 'EmURAQj8X1WGfbo7StLD',
    platform: 'facebook',
    scheduleAt: '2026-08-18T14:30:00.000Z',
    mediaType: 'image',
    caption:
      'Your ring should reflect your values as much as it reflects light. This halo-set diamond is ethically sourced, brilliantly cut, and built to become a treasured heirloom. Save this if you believe beauty and integrity belong together.\n\nWebsite:- neonluxe.com',
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/EmURAQj8X1WGfbo7StLD/image.png',
  },
  {
    id: 'cAw9QQsbXEQGG0VT4hJX',
    platform: 'instagram',
    scheduleAt: '2026-08-16T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Quiet luxury whispers louder than any trend. Our silver layered collection—each bead hand-placed, every bangle precisely angled—is the bride's answer to enduring grace. How would you style these for your moment? Tell us below.\n\nWebsite:- neonluxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/instagram/cAw9QQsbXEQGG0VT4hJX/image.png',
  },
  {
    id: 'R3NYwWCKdb9WbInGSxRS',
    platform: 'facebook',
    scheduleAt: '2026-08-16T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "Trends fade. Heirlooms endure. Our ethically sourced gold necklace and matching set are crafted to be passed down for generations—not forgotten by next season. Which matters more to you: what's trendy now, or what lasts forever?\n\nWebsite:- neonluxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/facebook/R3NYwWCKdb9WbInGSxRS/image.png',
  },
  {
    id: '7vyZvaBCasLTpj1fHvXH',
    platform: 'linkedin',
    scheduleAt: '2026-08-16T14:30:00.000Z',
    mediaType: 'image',
    caption:
      "True luxury has evolved. In 2026, what matters most isn't the size of a gemstone—it's the story behind it. This statement ruby and pearl set represents more than aesthetic brilliance; it embodies our unwavering commitment to ethically sourced materials and transparent provenance. Each intricate design honors traditional craftsmanship while meeting modern accountability standards. When you wear Neon Luxe, you're not just adorning yourself—you're investing in a legacy that feels as good as it looks. Heritage, ethics, and elegance, woven together.\n\nWebsite:- neonluxe.com",
    imageUrl:
      '/landing/how-it-looks/jewelry/linkedin/7vyZvaBCasLTpj1fHvXH/image.png',
  },
] as const;
